/**
 * Controller classification map for @RouteClass annotation.
 *
 * Each entry maps a controller file path to its route class.
 * Paths are relative to backend/src/.
 */

export interface ControllerAnnotation {
  path: string;
  routeClass: string;
}

export const CONTROLLER_ANNOTATIONS: ControllerAnnotation[] = [
  // ── auth (10/min) ──
  { path: 'auth/auth.controller.ts', routeClass: 'auth' },
  { path: 'kyc/kyc.controller.ts', routeClass: 'auth' },
  { path: 'admin/auth/admin-auth.controller.ts', routeClass: 'auth' },

  // ── webhook (100/min) ──
  { path: 'webhooks/payment-webhook-stripe.controller.ts', routeClass: 'webhook' },
  { path: 'webhooks/payment-webhook-generic.controller.ts', routeClass: 'webhook' },
  { path: 'webhooks/webhooks.controller.ts', routeClass: 'webhook' },
  { path: 'webhooks/tiktok-webhook.controller.ts', routeClass: 'webhook' },
  { path: 'webhooks/whatsapp-api-webhook.controller.ts', routeClass: 'webhook' },
  { path: 'webhooks/webhook-settings.controller.ts', routeClass: 'webhook' },
  { path: 'meta/webhooks/meta-webhook.controller.ts', routeClass: 'webhook' },
  { path: 'checkout/mercado-pago-webhook.controller.ts', routeClass: 'webhook' },
  { path: 'marketing/email-marketing-webhook.controller.ts', routeClass: 'webhook' },
  { path: 'marketing/facebook-messenger.controller.ts', routeClass: 'webhook' },
  { path: 'meta/messenger/messenger.controller.ts', routeClass: 'webhook' },

  // ── public-checkout (30/min) ──
  { path: 'checkout/checkout-public.controller.ts', routeClass: 'public-checkout' },
  { path: 'member-area/member-area-public.controller.ts', routeClass: 'public-checkout' },
  { path: 'kloel/site-public.controller.ts', routeClass: 'public-checkout' },

  // ── ai (20/min) ──
  { path: 'ai-brain/knowledge-base.controller.ts', routeClass: 'ai' },
  { path: 'autopilot/autopilot.controller.ts', routeClass: 'ai' },
  { path: 'autopilot/segmentation.controller.ts', routeClass: 'ai' },
  { path: 'cia/cia.controller.ts', routeClass: 'ai' },
  { path: 'kloel/kloel.controller.ts', routeClass: 'ai' },
  { path: 'kloel/unified-agent.controller.ts', routeClass: 'ai' },
  { path: 'kloel/whatsapp-brain.controller.ts', routeClass: 'ai' },
  { path: 'kloel/ad-rules.controller.ts', routeClass: 'ai' },
  { path: 'kloel/guest-chat.controller.ts', routeClass: 'ai' },
  { path: 'kloel/onboarding-profile.controller.ts', routeClass: 'ai' },
  { path: 'kloel/memory.controller.ts', routeClass: 'ai' },
  { path: 'kloel/diagnostics.controller.ts', routeClass: 'ai' },
  { path: 'kloel/pdf-processor.controller.ts', routeClass: 'ai' },
  { path: 'flows/flow-optimizer.controller.ts', routeClass: 'ai' },
  { path: 'crm/neuro-crm.controller.ts', routeClass: 'ai' },
  { path: 'growth/money-machine.controller.ts', routeClass: 'ai' },

  // ── read (300/min) ──
  { path: 'dashboard/dashboard.controller.ts', routeClass: 'read' },
  { path: 'analytics/analytics.controller.ts', routeClass: 'read' },
  { path: 'reports/reports.controller.ts', routeClass: 'read' },
  { path: 'health/health.controller.ts', routeClass: 'read' },
  { path: 'health/system-health.controller.ts', routeClass: 'read' },
  { path: 'audit/audit.controller.ts', routeClass: 'read' },
  { path: 'metrics/metrics.controller.ts', routeClass: 'read' },
  { path: 'ops/ops.controller.ts', routeClass: 'read' },
  { path: 'pulse/pulse.controller.ts', routeClass: 'read' },
  { path: 'cookie-consent/cookie-consent.controller.ts', routeClass: 'read' },
  { path: 'compliance/compliance.controller.ts', routeClass: 'read' },
  { path: 'admin/dashboard/admin-dashboard.controller.ts', routeClass: 'read' },
  { path: 'admin/reports/admin-reports.controller.ts', routeClass: 'read' },
  { path: 'admin/audit/admin-audit.controller.ts', routeClass: 'read' },
  { path: 'admin/config/admin-config.controller.ts', routeClass: 'read' },
  { path: 'admin/notifications/admin-notifications.controller.ts', routeClass: 'read' },
  { path: 'admin/sessions/admin-sessions.controller.ts', routeClass: 'read' },
  { path: 'admin/transactions/admin-transactions.controller.ts', routeClass: 'read' },
  { path: 'admin/carteira/admin-carteira.controller.ts', routeClass: 'read' },
  { path: 'admin/support/admin-support.controller.ts', routeClass: 'read' },
  { path: 'admin/compliance/admin-compliance.controller.ts', routeClass: 'read' },
  { path: 'admin/clients/admin-clients.controller.ts', routeClass: 'read' },
  { path: 'growth/growth.controller.ts', routeClass: 'read' },
  { path: 'calendar/calendar.controller.ts', routeClass: 'read' },
  { path: 'launch/launch.controller.ts', routeClass: 'read' },
  { path: 'app.controller.ts', routeClass: 'read' },
  { path: 'pipeline/pipeline.controller.ts', routeClass: 'read' },
  { path: 'crm/crm.controller.ts', routeClass: 'read' },
  { path: 'public-api/public-api.controller.ts', routeClass: 'read' },
  { path: 'kloel/leads.controller.ts', routeClass: 'read' },
  { path: 'kloel/sales.controller.ts', routeClass: 'read' },
  { path: 'kloel/sales-orders.controller.ts', routeClass: 'read' },
  { path: 'kloel/sales-subscriptions.controller.ts', routeClass: 'read' },
  { path: 'marketing/marketing.controller.ts', routeClass: 'read' },
  { path: 'flows/flow-template.controller.ts', routeClass: 'read' },

  // ── mutate (60/min) ──
  { path: 'billing/billing.controller.ts', routeClass: 'mutate' },
  { path: 'billing/payment-method.controller.ts', routeClass: 'mutate' },
  { path: 'checkout/checkout.controller.ts', routeClass: 'mutate' },
  { path: 'flows/flows.controller.ts', routeClass: 'mutate' },
  { path: 'inbox/inbox.controller.ts', routeClass: 'mutate' },
  { path: 'team/team.controller.ts', routeClass: 'mutate' },
  { path: 'campaigns/campaigns.controller.ts', routeClass: 'mutate' },
  { path: 'affiliate/affiliate.controller.ts', routeClass: 'mutate' },
  { path: 'affiliate/affiliate-marketplace.controller.ts', routeClass: 'mutate' },
  { path: 'marketing/email-marketing.controller.ts', routeClass: 'mutate' },
  { path: 'marketing/instagram/instagram-marketing.controller.ts', routeClass: 'mutate' },
  { path: 'marketing/tiktok-marketing.controller.ts', routeClass: 'mutate' },
  { path: 'marketing/marketing-connect.controller.ts', routeClass: 'mutate' },
  { path: 'media/media.controller.ts', routeClass: 'mutate' },
  { path: 'media/video.controller.ts', routeClass: 'mutate' },
  { path: 'notifications/notifications.controller.ts', routeClass: 'mutate' },
  { path: 'workspaces/workspace.controller.ts', routeClass: 'mutate' },
  { path: 'whatsapp/whatsapp.controller.ts', routeClass: 'mutate' },
  { path: 'whatsapp/controllers/whatsapp-api.controller.ts', routeClass: 'mutate' },
  { path: 'whatsapp/controllers/whatsapp-catalog.controller.ts', routeClass: 'mutate' },
  { path: 'whatsapp/controllers/whatsapp-meta-compat.controller.ts', routeClass: 'mutate' },
  { path: 'whatsapp/internal-whatsapp-runtime.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/product.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/payment.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/wallet.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/smart-payment.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/site.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/canvas.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/webinar.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/upload.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/product-sub-resources/product-affiliate.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/product-sub-resources/product-ai-config.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/product-sub-resources/product-campaign.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/product-sub-resources/product-checkout.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/product-sub-resources/product-commission.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/product-sub-resources/product-coupon.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/product-sub-resources/product-plan.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/product-sub-resources/product-review.controller.ts', routeClass: 'mutate' },
  { path: 'kloel/product-sub-resources/product-url.controller.ts', routeClass: 'mutate' },
  { path: 'member-area/member-areas.controller.ts', routeClass: 'mutate' },
  { path: 'member-area/member-enrollments.controller.ts', routeClass: 'mutate' },
  { path: 'member-area/member-modules.controller.ts', routeClass: 'mutate' },
  { path: 'member-area/member-structure.controller.ts', routeClass: 'mutate' },
  { path: 'meta/meta-auth.controller.ts', routeClass: 'mutate' },
  { path: 'meta/ads/meta-ads.controller.ts', routeClass: 'mutate' },
  { path: 'meta/instagram/instagram.controller.ts', routeClass: 'mutate' },
  { path: 'partnerships/partnerships.controller.ts', routeClass: 'mutate' },
  { path: 'scrapers/scrapers.controller.ts', routeClass: 'mutate' },
  { path: 'gdpr/gdpr.controller.ts', routeClass: 'mutate' },
  { path: 'gdpr/data-delete.controller.ts', routeClass: 'mutate' },
  { path: 'gdpr/data-export.controller.ts', routeClass: 'mutate' },
  { path: 'voice/voice.controller.ts', routeClass: 'mutate' },
  { path: 'video/video.controller.ts', routeClass: 'mutate' },
  { path: 'chat/chat.controller.ts', routeClass: 'mutate' },
  { path: 'payments/split/split.controller.ts', routeClass: 'mutate' },
  { path: 'payments/connect/connect.controller.ts', routeClass: 'mutate' },
  { path: 'wallet/prepaid-wallet.controller.ts', routeClass: 'mutate' },
  { path: 'marketplace/marketplace.controller.ts', routeClass: 'mutate' },
  { path: 'product-categories/product-categories.controller.ts', routeClass: 'mutate' },
  { path: 'anuncios/anuncios.controller.ts', routeClass: 'mutate' },
  { path: 'api-keys/api-keys.controller.ts', routeClass: 'mutate' },
  { path: 'common/storage/storage.controller.ts', routeClass: 'mutate' },
  { path: 'followup/followup.controller.ts', routeClass: 'mutate' },
  { path: 'mass-send/mass-send.controller.ts', routeClass: 'mutate' },
  { path: 'admin/accounts/admin-accounts.controller.ts', routeClass: 'mutate' },
  { path: 'admin/products/admin-products.controller.ts', routeClass: 'mutate' },
  { path: 'admin/sales/admin-sales.controller.ts', routeClass: 'mutate' },
  { path: 'admin/users/admin-users.controller.ts', routeClass: 'mutate' },
  { path: 'admin/chat/admin-chat.controller.ts', routeClass: 'mutate' },
  { path: 'admin/marketing/admin-marketing.controller.ts', routeClass: 'mutate' },
  { path: 'admin/destructive/admin-destructive.controller.ts', routeClass: 'mutate' },
];
