export const COOKIE_TOKENS = {
  void: '#0A0A0C',
  surface: '#111113',
  border: '#222226',
  elevated: '#19191C',
  silver: '#E0DDD8',
  muted: '#6E6E73',
  dim: '#3A3A3F',
  ember: '#E85D30',
  emberBg: 'rgba(232,93,48,0.06)',
  emberGlow: 'rgba(232,93,48,0.1)',
  emberSelection: 'rgba(232,93,48,0.3)',
  font: "var(--font-sora), 'Sora', sans-serif",
  mono: "var(--font-jetbrains), 'JetBrains Mono', monospace",
  radius: 6,
} as const;

export const COOKIE_POLICY_UPDATED_AT = '4 de abril de 2026';

export const COOKIE_DATA = {
  necessary: [
    {
      origin: 'Kloel',
      name: 'kloel_session',
      duration: 'Sessão',
      purpose: 'Autenticação do usuário',
      domain: 'kloel.com',
    },
    {
      origin: 'Kloel',
      name: 'kloel_csrf',
      duration: 'Sessão',
      purpose: 'Segurança',
      domain: 'kloel.com',
    },
    {
      origin: 'Kloel',
      name: 'kloel_workspace',
      duration: '30 dias',
      purpose: 'Funcionalidade do serviço',
      domain: 'kloel.com',
    },
    {
      origin: 'Kloel',
      name: 'kloel_locale',
      duration: '1 ano',
      purpose: 'Funcionalidade do serviço',
      domain: 'kloel.com',
    },
    {
      origin: 'Kloel',
      name: 'kloel_consent',
      duration: '1 ano',
      purpose: 'Consentimento para cookies',
      domain: 'kloel.com',
    },
    {
      origin: 'Kloel',
      name: 'kloel_did',
      duration: '1 ano',
      purpose: 'Funcionalidade do serviço',
      domain: 'kloel.com',
    },
    {
      origin: 'Kloel',
      name: 'kloel_auth_provider',
      duration: '10 minutos',
      purpose: 'Autenticação do usuário',
      domain: 'auth.kloel.com',
    },
    {
      origin: 'Kloel',
      name: 'kloel_nav_state',
      duration: '2 anos',
      purpose: 'Funcionalidade do serviço',
      domain: 'kloel.com',
    },
    {
      origin: 'Kloel',
      name: 'kloel_sidebar',
      duration: '30 dias',
      purpose: 'Funcionalidade do serviço',
      domain: 'kloel.com',
    },
    {
      origin: 'Kloel',
      name: 'kloel_last_model',
      duration: '30 dias',
      purpose: 'Funcionalidade do serviço',
      domain: 'kloel.com',
    },
    {
      origin: 'Kloel',
      name: 'kloel_ip_country',
      duration: 'Sessão',
      purpose: 'Funcionalidade do serviço',
      domain: 'kloel.com',
    },
    {
      origin: 'Cloudflare',
      name: '__cf_bm',
      duration: '30 minutos',
      purpose: 'Segurança',
      domain: 'kloel.com',
    },
    {
      origin: 'Cloudflare',
      name: 'cf_clearance',
      duration: '1 ano',
      purpose: 'Segurança',
      domain: 'kloel.com',
    },
    {
      origin: 'Cloudflare',
      name: '_cfuvid',
      duration: 'Sessão',
      purpose: 'Segurança',
      domain: 'kloel.com',
    },
    {
      origin: 'Stripe',
      name: '__stripe_mid',
      duration: '1 ano',
      purpose: 'Pagamento',
      domain: 'kloel.com',
    },
    {
      origin: 'Stripe',
      name: '__stripe_sid',
      duration: '30 minutos',
      purpose: 'Pagamento',
      domain: 'kloel.com',
    },
  ],
  analytics: [
    {
      origin: 'Google Analytics',
      name: '_ga',
      duration: '6 meses',
      purpose: 'Análises',
      domain: 'kloel.com',
    },
    {
      origin: 'Google Analytics',
      name: '_ga_*',
      duration: '6 meses',
      purpose: 'Análises',
      domain: 'kloel.com',
    },
    {
      origin: 'Kloel',
      name: 'kloel_ab_test',
      duration: '30 dias',
      purpose: 'Análises',
      domain: 'kloel.com',
    },
    {
      origin: 'Kloel',
      name: 'kloel_funnel',
      duration: 'Sessão',
      purpose: 'Análises',
      domain: 'kloel.com',
    },
  ],
  marketing: [
    {
      origin: 'Meta',
      name: '_fbp',
      duration: '90 dias',
      purpose: 'Medição de marketing',
      domain: 'kloel.com',
    },
    {
      origin: 'Meta',
      name: '_fbc',
      duration: '90 dias',
      purpose: 'Medição de marketing',
      domain: 'kloel.com',
    },
    {
      origin: 'Meta',
      name: 'fbclid',
      duration: '24 horas',
      purpose: 'Medição de marketing',
      domain: 'kloel.com',
    },
    {
      origin: 'Google',
      name: '_gcl_au',
      duration: '90 dias',
      purpose: 'Medição de marketing',
      domain: 'kloel.com',
    },
    {
      origin: 'Google',
      name: '_gcl_aw',
      duration: '90 dias',
      purpose: 'Medição de marketing',
      domain: 'kloel.com',
    },
    {
      origin: 'Google',
      name: 'gclid',
      duration: '24 horas',
      purpose: 'Medição de marketing',
      domain: 'kloel.com',
    },
    {
      origin: 'TikTok',
      name: '_ttp',
      duration: '13 meses',
      purpose: 'Medição de marketing',
      domain: 'kloel.com',
    },
    {
      origin: 'TikTok',
      name: 'ttclid',
      duration: '13 meses',
      purpose: 'Medição de marketing',
      domain: 'kloel.com',
    },
  ],
} as const;

export const COOKIE_BROWSER_LINKS = [
  { name: 'Chrome', url: 'https://support.google.com/chrome/answer/95647' },
  { name: 'Safari', url: 'https://support.apple.com/guide/safari/manage-cookies-sfri11471' },
  {
    name: 'Firefox',
    url: 'https://support.mozilla.org/kb/cookies-information-websites-store-on-your-computer',
  },
  { name: 'Edge', url: 'https://support.microsoft.com/microsoft-edge/delete-cookies' },
  { name: 'Opera', url: 'https://help.opera.com/latest/web-preferences/#cookies' },
] as const;
