import type { CapabilityDefinition } from './capability-registry-v2.types';

export const CORE_CAPABILITY_DEFINITIONS: CapabilityDefinition[] = [
  // ═══════════ Tier 0 — Auto-consciência ═══════════
  {
    id: 'self.capabilities',
    title: 'Listar capacidades',
    description: 'Mostra o que o Kloel sabe fazer no contexto atual',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CapabilityRegistry.filterFor',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp', 'flow'],
  },
  {
    id: 'self.health',
    title: 'Saúde do sistema',
    description: 'Status de serviços, filas, integrações, banco',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'HealthService.snapshot',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },
  {
    id: 'self.gaps',
    title: 'Listar lacunas',
    description: 'Mostra quais capacidades ainda não estão disponíveis ou estão quebradas',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CapabilityRegistry.listGaps',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },
  {
    id: 'self.audit_log',
    title: 'Log de ações',
    description: 'Mostra as últimas ações executadas pelo Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['audit:read'],
    inputSchema: [
      {
        key: 'limit',
        type: 'number',
        label: 'Quantidade',
        required: false,
        description: 'Número de ações para mostrar',
      },
    ],
    domainService: 'AuditService.recent',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_products',
    title: 'Listar produtos',
    description: 'Lista todos os produtos do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ProductService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'self.explain',
    title: 'Explicar capacidade',
    description: 'Detalha uma capacidade: o que faz, como usar, status',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'capabilityId',
        type: 'string',
        label: 'ID',
        required: true,
        prompt: 'Qual capacidade você quer saber mais?',
      },
    ],
    domainService: 'CapabilityRegistry.describe',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },

  {
    id: 'list_orders',
    title: 'Listar vendas/pedidos',
    description: 'Lista vendas e pedidos do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'status',
        type: 'select',
        label: 'Status',
        required: false,
        enum: ['pending', 'paid', 'cancelled'],
      },
    ],
    domainService: 'OrderService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_sales_summary',
    title: 'Resumo de vendas',
    description: 'Mostra resumo de vendas: total, receita, ticket médio',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'SalesService.summary',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_leads',
    title: 'Listar leads',
    description: 'Lista leads do CRM com filtros',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CrmService.listLeads',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_wallet_balance',
    title: 'Saldo da carteira',
    description: 'Mostra saldo disponível, pendente e total',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getBalance',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_wallet_statement',
    title: 'Extrato da carteira',
    description: 'Mostra extrato de transações',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getStatement',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_abandonments',
    title: 'Carrinhos abandonados',
    description: 'Lista carrinhos abandonados recentes',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AbandonmentService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_plans',
    title: 'Planos do produto',
    description: 'Lista todos os planos de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'PlanService.listForProduct',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_reviews',
    title: 'Avaliações',
    description: 'Lista avaliações de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'ReviewService.listForProduct',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_urls',
    title: 'URLs do produto',
    description: 'Lista URLs cadastradas de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'ProductUrlService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'delete_coupon',
    title: 'Excluir cupom',
    description: 'Remove um cupom permanentemente',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'couponId', type: 'string', label: 'ID do cupom', required: true }],
    domainService: 'CouponService.delete',
    emits: ['coupon.deleted'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'validate_coupon',
    title: 'Validar cupom',
    description: 'Verifica se um cupom é válido para um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'code', type: 'string', label: 'Código', required: true },
      { key: 'productId', type: 'string', label: 'Produto', required: true },
    ],
    domainService: 'CouponService.validate',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'upload_document',
    title: 'Enviar documento',
    description: 'Anexa documento (PDF/imagem) aos documentos fiscais',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      {
        key: 'documentType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['identity', 'contract', 'cnpj_card'],
      },
    ],
    domainService: 'DocumentService.upload',
    emits: ['account.document_uploaded'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_subscriptions',
    title: 'Listar assinaturas',
    description: 'Lista assinaturas ativas do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'SubscriptionService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_shipping',
    title: 'Configurar frete',
    description: 'Configura frete e entrega de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'shippingType',
        type: 'select',
        label: 'Tipo',
        required: false,
        enum: ['free', 'fixed', 'variable'],
      },
    ],
    domainService: 'ShippingService.configure',
    emits: ['product.shipping_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_warranty',
    title: 'Configurar garantia',
    description: 'Define garantia em dias de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'warrantyDays', type: 'number', label: 'Dias de garantia', required: true },
    ],
    domainService: 'ProductService.update',
    emits: ['product.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_exit_intent',
    title: 'Popup de saída',
    description: 'Ativa/desativa popup de exit intent no checkout',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
  },
];
