import { type CapabilityDefinition } from './capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY — Single source of truth
 *
 * Every action the Kloel can perform is defined here.
 * This IS the registry. Adding a capability here = it is dispatchable.
 */
export const CAPABILITY_DEFINITIONS: CapabilityDefinition[] = [
  // ═══════════ Tier 0 — Auto-consciência ═══════════
  {
    id: 'self.capabilities',
    title: 'Listar capacidades',
    description: 'Mostra o que o Kloel sabe fazer no contexto atual',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CapabilityRegistry.filterFor',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp', 'flow'],
  },
  {
    id: 'self.health',
    title: 'Saúde do sistema',
    description: 'Status de serviços, filas, integrações, banco',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'HealthService.snapshot',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },
  {
    id: 'self.gaps',
    title: 'Listar lacunas',
    description: 'Mostra quais capacidades ainda não estão disponíveis ou estão quebradas',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CapabilityRegistry.listGaps',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },
  {
    id: 'self.audit_log',
    title: 'Log de ações',
    description: 'Mostra as últimas ações executadas pelo Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['audit:read'],
    inputSchema: [
      { key: 'limit', type: 'number', label: 'Quantidade', required: false, description: 'Número de ações para mostrar' },
    ],
    domainService: 'AuditService.recent',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_products',
    title: 'Listar produtos',
    description: 'Lista todos os produtos do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ProductService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'self.explain',
    title: 'Explicar capacidade',
    description: 'Detalha uma capacidade: o que faz, como usar, status',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'capabilityId', type: 'string', label: 'ID', required: true, prompt: 'Qual capacidade você quer saber mais?' },
    ],
    domainService: 'CapabilityRegistry.describe',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },

  // ═══════════ Tier 1 — Produtos: Criar ═══════════
  {
    id: 'products.create',
    title: 'Criar produto',
    description: 'Cria um novo produto no catálogo do workspace',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true, prompt: 'Qual o nome do produto?' },
      { key: 'description', type: 'string', label: 'Descrição', required: false },
      { key: 'category', type: 'string', label: 'Categoria', required: false },
      { key: 'format', type: 'select', label: 'Formato', required: false, enum: ['físico', 'digital', 'híbrido'] },
      { key: 'price', type: 'number', label: 'Preço (R$)', required: true, prompt: 'Qual o preço?' },
    ],
    domainService: 'ProductService.create',
    emits: ['product.created'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.upload_image',
    title: 'Upload imagem do produto',
    description: 'Anexa uma imagem enviada no chat ao produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'imageFile', type: 'file', label: 'Arquivo de imagem', required: true },
    ],
    domainService: 'MediaService.attach + ProductService.setImage',
    emits: ['product.image_updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.update',
    title: 'Editar produto',
    description: 'Edita dados gerais de um produto existente',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: false },
      { key: 'description', type: 'string', label: 'Descrição', required: false },
      { key: 'active', type: 'boolean', label: 'Disponível para venda', required: false },
      { key: 'salesPageUrl', type: 'string', label: 'URL da página de vendas', required: false },
    ],
    domainService: 'ProductService.update',
    emits: ['product.updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 2 — Planos ═══════════
  {
    id: 'plans.create',
    title: 'Criar plano',
    description: 'Cria um novo plano/variação para um produto',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome do plano', required: true, prompt: 'Nome do plano? (ex: "1 Frasco")' },
      { key: 'price', type: 'number', label: 'Valor (R$)', required: true, prompt: 'Qual o valor?' },
      { key: 'maxInstallments', type: 'number', label: 'Parcelas máx.', required: false },
      { key: 'acceptPix', type: 'boolean', label: 'Aceitar PIX', required: false },
      { key: 'acceptCard', type: 'boolean', label: 'Aceitar cartão', required: false },
      { key: 'acceptBoleto', type: 'boolean', label: 'Aceitar boleto', required: false },
    ],
    domainService: 'PlanService.create',
    emits: ['plan.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.update',
    title: 'Editar plano',
    description: 'Edita um plano existente: valor, parcelas, disponibilidade',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'ID do plano', required: true },
      { key: 'price', type: 'number', label: 'Valor', required: false },
      { key: 'active', type: 'boolean', label: 'Disponível para venda', required: false },
    ],
    domainService: 'PlanService.update',
    emits: ['plan.updated'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 3 — Checkouts ═══════════
  {
    id: 'checkouts.create',
    title: 'Criar checkout',
    description: 'Cria checkout vinculado a planos de um produto com personalização',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome do checkout', required: true, prompt: 'Nome do checkout?' },
      { key: 'acceptPix', type: 'boolean', label: 'Aceitar PIX', required: false },
      { key: 'acceptCard', type: 'boolean', label: 'Aceitar cartão', required: false },
      { key: 'acceptBoleto', type: 'boolean', label: 'Aceitar boleto', required: false },
      { key: 'buttonText', type: 'string', label: 'Texto do botão', required: false },
    ],
    domainService: 'CheckoutService.create',
    emits: ['checkout.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.update',
    title: 'Editar checkout',
    description: 'Edita checkout existente',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'buttonText', type: 'string', label: 'Texto do botão', required: false },
      { key: 'active', type: 'boolean', label: 'Ativo', required: false },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 4 — Cupons ═══════════
  {
    id: 'coupons.create',
    title: 'Criar cupom',
    description: 'Cria cupom de desconto para um produto',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'code', type: 'string', label: 'Código', required: true, prompt: 'Código do cupom?' },
      { key: 'discountType', type: 'select', label: 'Tipo', required: true, enum: ['percentage', 'fixed'] },
      { key: 'discountValue', type: 'number', label: 'Valor', required: true },
      { key: 'usageLimit', type: 'number', label: 'Limite de usos', required: false },
    ],
    domainService: 'CouponService.create',
    emits: ['coupon.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'coupons.delete',
    title: 'Excluir cupom',
    description: 'Remove um cupom de desconto',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'couponId', type: 'string', label: 'ID do cupom', required: true },
    ],
    domainService: 'CouponService.delete',
    emits: ['coupon.deleted'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 5 — Vendas reais (CRÍTICO) ═══════════
  {
    id: 'sales.create_pix',
    title: 'Gerar PIX',
    description: 'Cria venda real com PIX. Retorna copia-e-cola + QR Code.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productName', type: 'string', label: 'Produto', required: true, prompt: 'Qual produto?' },
      { key: 'amount', type: 'number', label: 'Valor (R$)', required: true, prompt: 'Valor?' },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true, prompt: 'Nome do comprador?' },
      { key: 'customerPhone', type: 'string', label: 'Telefone', required: true },
      { key: 'customerEmail', type: 'string', label: 'Email', required: false },
      { key: 'customerCpf', type: 'string', label: 'CPF', required: false },
    ],
    domainService: 'CheckoutService.createOrder + PaymentService.generatePix',
    emits: ['sale.created', 'payment.pix_generated'],
    evidenceUrlBuilder: '/vendas/${orderId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'sales.create_boleto',
    title: 'Gerar boleto',
    description: 'Cria venda real com boleto bancário. Retorna PDF + código.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productName', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true },
      { key: 'customerPhone', type: 'string', label: 'Telefone', required: true },
      { key: 'customerEmail', type: 'string', label: 'Email', required: true },
      { key: 'customerCpf', type: 'string', label: 'CPF', required: true },
    ],
    domainService: 'CheckoutService.createOrder + PaymentService.generateBoleto',
    emits: ['sale.created', 'payment.boleto_generated'],
    evidenceUrlBuilder: '/vendas/${orderId}',
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 6 — URLs ═══════════
  {
    id: 'urls.add',
    title: 'Adicionar URL',
    description: 'Adiciona URL (página de venda, landing page) a um produto',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'url', type: 'string', label: 'URL', required: true },
      { key: 'description', type: 'string', label: 'Descrição', required: true },
    ],
    domainService: 'ProductUrlService.add',
    emits: ['product.url_added'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 7 — Afiliados ═══════════
  {
    id: 'affiliates.configure',
    title: 'Configurar afiliados',
    description: 'Ativa/desativa e configura o programa de afiliados do produto',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar programa?', required: true },
      { key: 'commissionPercent', type: 'number', label: 'Comissão (%)', required: false },
    ],
    domainService: 'AffiliateService.configure',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 8 — CRM ═══════════
  {
    id: 'crm.pipeline',
    title: 'Pipeline CRM',
    description: 'Mostra o pipeline CRM com estágios e leads',
    category: 'QUERY',
    tier: 8,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CrmService.getPipeline',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'sales.list',
    title: 'Listar vendas',
    description: 'Lista as vendas do workspace',
    category: 'QUERY',
    tier: 8,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'status', type: 'select', label: 'Status', required: false, enum: ['pending', 'paid', 'cancelled', 'refunded'] },
      { key: 'limit', type: 'number', label: 'Quantidade', required: false },
    ],
    domainService: 'OrderService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 9 — Carteira ═══════════
  {
    id: 'wallet.balance',
    title: 'Saldo da carteira',
    description: 'Mostra o saldo disponível, pendente e total',
    category: 'QUERY',
    tier: 9,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getBalance',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'wallet.withdraw',
    title: 'Solicitar saque',
    description: 'Solicita saque do saldo disponível para conta bancária',
    category: 'MUTATION_SENSITIVE',
    tier: 9,
    requiresConfirmation: true,
    requiredPermissions: ['wallet:write'],
    inputSchema: [
      { key: 'amount', type: 'number', label: 'Valor (R$)', required: true, prompt: 'Qual valor do saque?' },
    ],
    domainService: 'WalletService.requestWithdrawal',
    emits: ['wallet.withdrawal_requested'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 10 — Relatórios ═══════════
  {
    id: 'reports.operations',
    title: 'Operações',
    description: 'Mostra relatório de operações: vendas, receita, ticket médio',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'period', type: 'select', label: 'Período', required: false, enum: ['today', 'week', 'month', 'year'] },
    ],
    domainService: 'ReportService.getOperations',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'reports.abandonments',
    title: 'Carrinhos abandonados',
    description: 'Mostra carrinhos abandonados no período',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'period', type: 'select', label: 'Período', required: false, enum: ['today', 'week', 'month', 'year'] },
    ],
    domainService: 'ReportService.getAbandonments',
    emits: [],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 11 — Configurações ═══════════
  {
    id: 'account.update_fiscal',
    title: 'Atualizar dados fiscais',
    description: 'Atualiza dados fiscais: CPF/CNPJ, razão social, endereço',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'personType', type: 'select', label: 'Tipo', required: true, enum: ['PF', 'PJ'] },
      { key: 'document', type: 'string', label: 'CPF/CNPJ', required: true },
      { key: 'businessName', type: 'string', label: 'Razão social', required: false },
      { key: 'zipCode', type: 'string', label: 'CEP', required: false },
    ],
    domainService: 'AccountService.updateFiscalData',
    emits: ['account.fiscal_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.update_bank',
    title: 'Atualizar dados bancários',
    description: 'Atualiza conta bancária para recebimento de saques',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'bankCode', type: 'string', label: 'Código do banco', required: true },
      { key: 'agency', type: 'string', label: 'Agência', required: true },
      { key: 'account', type: 'string', label: 'Conta', required: true },
    ],
    domainService: 'AccountService.updateBankAccount',
    emits: ['account.bank_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.set_pix_key',
    title: 'Cadastrar chave PIX',
    description: 'Cadastra ou altera a chave PIX',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'pixKey', type: 'string', label: 'Chave PIX', required: true },
      { key: 'pixKeyType', type: 'select', label: 'Tipo', required: true, enum: ['CPF', 'CNPJ', 'email', 'celular', 'aleatória'] },
    ],
    domainService: 'AccountService.setPixKey',
    emits: ['account.pix_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.upload_document',
    title: 'Enviar documento',
    description: 'Anexa um documento (PDF/imagem) enviado pelo chat aos documentos fiscais',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'documentType', type: 'select', label: 'Tipo', required: true, enum: ['identity', 'contract', 'cnpj_card'] },
    ],
    domainService: 'DocumentService.upload',
    emits: ['account.document_uploaded'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'ui.theme',
    title: 'Alternar tema',
    description: 'Alterna entre tema claro e escuro',
    category: 'CONFIGURATION',
    tier: 11,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'theme', type: 'select', label: 'Tema', required: true, enum: ['light', 'dark'] },
    ],
    domainService: 'ThemeService.set',
    emits: [],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 12 — Marketing ═══════════
  {
    id: 'whatsapp.send',
    title: 'Enviar WhatsApp',
    description: 'Envia mensagem de WhatsApp para um contato',
    category: 'COMMUNICATION',
    tier: 12,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [
      { key: 'phone', type: 'string', label: 'Telefone', required: true },
      { key: 'message', type: 'string', label: 'Mensagem', required: true },
    ],
    domainService: 'MessagingService.sendWhatsApp',
    emits: ['whatsapp.message_sent'],
    surface: ['dashboard-chat'],
  },
];
export const CAPABILITY_MAP = new Map<string, CapabilityDefinition>(
  CAPABILITY_DEFINITIONS.map((cap) => [cap.id, cap]),
);

/** Map capability ID -> tier grouping */
export const CAPABILITIES_BY_TIER: Record<number, CapabilityDefinition[]> =
  CAPABILITY_DEFINITIONS.reduce<Record<number, CapabilityDefinition[]>>((acc, cap) => {
    if (!acc[cap.tier]) acc[cap.tier] = [];
    acc[cap.tier].push(cap);
    return acc;
  }, {});