import type { CapabilityDefinition } from './capability-registry-v2.types';

export const OPERATIONS_CAPABILITY_DEFINITIONS: CapabilityDefinition[] = [
  // ═══════════ Tier 6 — URLs ═══════════
  {
    id: 'urls.add',
    title: 'Adicionar URL',
    description: 'Adiciona URL (página de venda, landing page) a um produto',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'url', type: 'string', label: 'URL', required: true },
      { key: 'description', type: 'string', label: 'Descrição', required: true },
    ],
    domainService: 'ProductUrlService.add',
    emits: ['product.url_added'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 7 — Afiliados ═══════════
  {
    id: 'affiliates.configure',
    title: 'Configurar afiliados',
    description: 'Ativa/desativa e configura o programa de afiliados do produto',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar programa?', required: true },
      { key: 'commissionPercent', type: 'number', label: 'Comissão (%)', required: false },
    ],
    domainService: 'AffiliateService.configure',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 8 — CRM ═══════════
  {
    id: 'crm.pipeline',
    title: 'Pipeline CRM',
    description: 'Mostra o pipeline CRM com estágios e leads',
    category: 'QUERY',
    tier: 8,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CrmService.getPipeline',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'sales.list',
    title: 'Listar vendas',
    description: 'Lista as vendas do workspace',
    category: 'QUERY',
    tier: 8,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'status',
        type: 'select',
        label: 'Status',
        required: false,
        enum: ['pending', 'paid', 'cancelled', 'refunded'],
      },
      { key: 'limit', type: 'number', label: 'Quantidade', required: false },
    ],
    domainService: 'OrderService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 9 — Carteira ═══════════
  {
    id: 'wallet.balance',
    title: 'Saldo da carteira',
    description: 'Mostra o saldo disponível, pendente e total',
    category: 'QUERY',
    tier: 9,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getBalance',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'wallet.withdraw',
    title: 'Solicitar saque',
    description: 'Solicita saque do saldo disponível para conta bancária',
    category: 'MUTATION_SENSITIVE',
    tier: 9,
    requiresConfirmation: true,
    requiredPermissions: ['wallet:write'],
    inputSchema: [
      {
        key: 'amount',
        type: 'number',
        label: 'Valor (R$)',
        required: true,
        prompt: 'Qual valor do saque?',
      },
    ],
    domainService: 'WalletService.requestWithdrawal',
    emits: ['wallet.withdrawal_requested'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 10 — Relatórios ═══════════
  {
    id: 'reports.operations',
    title: 'Operações',
    description: 'Mostra relatório de operações: vendas, receita, ticket médio',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'period',
        type: 'select',
        label: 'Período',
        required: false,
        enum: ['today', 'week', 'month', 'year'],
      },
    ],
    domainService: 'ReportService.getOperations',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'reports.abandonments',
    title: 'Carrinhos abandonados',
    description: 'Mostra carrinhos abandonados no período',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'period',
        type: 'select',
        label: 'Período',
        required: false,
        enum: ['today', 'week', 'month', 'year'],
      },
    ],
    domainService: 'ReportService.getAbandonments',
    emits: [],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 11 — Configurações ═══════════
  {
    id: 'account.update_fiscal',
    title: 'Atualizar dados fiscais',
    description: 'Atualiza dados fiscais: CPF/CNPJ, razão social, endereço',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'personType', type: 'select', label: 'Tipo', required: true, enum: ['PF', 'PJ'] },
      { key: 'document', type: 'string', label: 'CPF/CNPJ', required: true },
      { key: 'businessName', type: 'string', label: 'Razão social', required: false },
      { key: 'zipCode', type: 'string', label: 'CEP', required: false },
    ],
    domainService: 'AccountService.updateFiscalData',
    emits: ['account.fiscal_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.update_bank',
    title: 'Atualizar dados bancários',
    description: 'Atualiza conta bancária para recebimento de saques',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'bankCode', type: 'string', label: 'Código do banco', required: true },
      { key: 'agency', type: 'string', label: 'Agência', required: true },
      { key: 'account', type: 'string', label: 'Conta', required: true },
    ],
    domainService: 'AccountService.updateBankAccount',
    emits: ['account.bank_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.set_pix_key',
    title: 'Cadastrar chave PIX',
    description: 'Cadastra ou altera a chave PIX',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'pixKey', type: 'string', label: 'Chave PIX', required: true },
      {
        key: 'pixKeyType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['CPF', 'CNPJ', 'email', 'celular', 'aleatória'],
      },
    ],
    domainService: 'AccountService.setPixKey',
    emits: ['account.pix_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.upload_document',
    title: 'Enviar documento',
    description: 'Anexa um documento (PDF/imagem) enviado pelo chat aos documentos fiscais',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      {
        key: 'documentType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['identity', 'contract', 'cnpj_card'],
      },
    ],
    domainService: 'DocumentService.upload',
    emits: ['account.document_uploaded'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'ui.theme',
    title: 'Alternar tema',
    description: 'Alterna entre tema claro e escuro',
    category: 'CONFIGURATION',
    tier: 11,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'theme', type: 'select', label: 'Tema', required: true, enum: ['light', 'dark'] },
    ],
    domainService: 'ThemeService.set',
    emits: [],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 12 — Marketing ═══════════
  {
    id: 'whatsapp.send',
    title: 'Enviar WhatsApp',
    description: 'Envia mensagem de WhatsApp para um contato',
    category: 'COMMUNICATION',
    tier: 12,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [
      { key: 'phone', type: 'string', label: 'Telefone', required: true },
      { key: 'message', type: 'string', label: 'Mensagem', required: true },
    ],
    domainService: 'MessagingService.sendWhatsApp',
    emits: ['whatsapp.message_sent'],
    surface: ['dashboard-chat'],
  },
];
