import type { CapabilityDefinition } from './capability-registry-v2.types';

export const COMMERCE_CAPABILITY_DEFINITIONS: CapabilityDefinition[] = [
  // ═══════════ Tier 1 — Produtos: Criar ═══════════
  {
    id: 'products.create',
    title: 'Criar produto',
    description: 'Cria um novo produto no catálogo do workspace',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      {
        key: 'name',
        type: 'string',
        label: 'Nome',
        required: true,
        prompt: 'Qual o nome do produto?',
      },
      { key: 'description', type: 'string', label: 'Descrição', required: false },
      { key: 'category', type: 'string', label: 'Categoria', required: false },
      {
        key: 'format',
        type: 'select',
        label: 'Formato',
        required: false,
        enum: ['físico', 'digital', 'híbrido'],
      },
      {
        key: 'price',
        type: 'number',
        label: 'Preço (R$)',
        required: true,
        prompt: 'Qual o preço?',
      },
    ],
    domainService: 'ProductService.create',
    emits: ['product.created'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.upload_image',
    title: 'Upload imagem do produto',
    description: 'Anexa uma imagem enviada no chat ao produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'imageFile', type: 'file', label: 'Arquivo de imagem', required: true },
    ],
    domainService: 'MediaService.attach + ProductService.setImage',
    emits: ['product.image_updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.update',
    title: 'Editar produto',
    description: 'Edita dados gerais de um produto existente',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: false },
      { key: 'description', type: 'string', label: 'Descrição', required: false },
      { key: 'active', type: 'boolean', label: 'Disponível para venda', required: false },
      { key: 'salesPageUrl', type: 'string', label: 'URL da página de vendas', required: false },
    ],
    domainService: 'ProductService.update',
    emits: ['product.updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 2 — Planos ═══════════
  {
    id: 'plans.create',
    title: 'Criar plano',
    description: 'Cria um novo plano/variação para um produto',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'name',
        type: 'string',
        label: 'Nome do plano',
        required: true,
        prompt: 'Nome do plano? (ex: "1 Frasco")',
      },
      {
        key: 'price',
        type: 'number',
        label: 'Valor (R$)',
        required: true,
        prompt: 'Qual o valor?',
      },
      { key: 'maxInstallments', type: 'number', label: 'Parcelas máx.', required: false },
      { key: 'acceptPix', type: 'boolean', label: 'Aceitar PIX', required: false },
      { key: 'acceptCard', type: 'boolean', label: 'Aceitar cartão', required: false },
      { key: 'acceptBoleto', type: 'boolean', label: 'Aceitar boleto', required: false },
    ],
    domainService: 'PlanService.create',
    emits: ['plan.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.update',
    title: 'Editar plano',
    description: 'Edita um plano existente: valor, parcelas, disponibilidade',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'ID do plano', required: true },
      { key: 'price', type: 'number', label: 'Valor', required: false },
      { key: 'active', type: 'boolean', label: 'Disponível para venda', required: false },
    ],
    domainService: 'PlanService.update',
    emits: ['plan.updated'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 3 — Checkouts ═══════════
  {
    id: 'checkouts.create',
    title: 'Criar checkout',
    description: 'Cria checkout vinculado a planos de um produto com personalização',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'name',
        type: 'string',
        label: 'Nome do checkout',
        required: true,
        prompt: 'Nome do checkout?',
      },
      { key: 'acceptPix', type: 'boolean', label: 'Aceitar PIX', required: false },
      { key: 'acceptCard', type: 'boolean', label: 'Aceitar cartão', required: false },
      { key: 'acceptBoleto', type: 'boolean', label: 'Aceitar boleto', required: false },
      { key: 'buttonText', type: 'string', label: 'Texto do botão', required: false },
    ],
    domainService: 'CheckoutService.create',
    emits: ['checkout.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.update',
    title: 'Editar checkout',
    description: 'Edita checkout existente',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'buttonText', type: 'string', label: 'Texto do botão', required: false },
      { key: 'active', type: 'boolean', label: 'Ativo', required: false },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 4 — Cupons ═══════════
  {
    id: 'coupons.create',
    title: 'Criar cupom',
    description: 'Cria cupom de desconto para um produto',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'code', type: 'string', label: 'Código', required: true, prompt: 'Código do cupom?' },
      {
        key: 'discountType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['percentage', 'fixed'],
      },
      { key: 'discountValue', type: 'number', label: 'Valor', required: true },
      { key: 'usageLimit', type: 'number', label: 'Limite de usos', required: false },
    ],
    domainService: 'CouponService.create',
    emits: ['coupon.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'coupons.delete',
    title: 'Excluir cupom',
    description: 'Remove um cupom de desconto',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'couponId', type: 'string', label: 'ID do cupom', required: true }],
    domainService: 'CouponService.delete',
    emits: ['coupon.deleted'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 5 — Vendas reais (CRÍTICO) ═══════════
  {
    id: 'generate_pix',
    title: 'Gerar PIX',
    description: 'Cria venda real com PIX. Retorna copia-e-cola + QR Code.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true },
    ],
    domainService: 'CheckoutService.createOrder + PaymentService.generatePix',
    emits: ['sale.created', 'payment.pix_generated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'generate_boleto',
    title: 'Gerar boleto',
    description: 'Cria venda real com boleto bancário.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true },
    ],
    domainService: 'CheckoutService.createOrder + PaymentService.generateBoleto',
    emits: ['sale.created', 'payment.boleto_generated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_payment_link',
    title: 'Link de pagamento',
    description: 'Gera link de pagamento para um lead',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
    ],
    domainService: 'PaymentService.createPayment',
    emits: ['payment.link_created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'sales.create_pix',
    title: 'Gerar PIX',
    description: 'Cria venda real com PIX. Retorna copia-e-cola + QR Code.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      {
        key: 'productName',
        type: 'string',
        label: 'Produto',
        required: true,
        prompt: 'Qual produto?',
      },
      { key: 'amount', type: 'number', label: 'Valor (R$)', required: true, prompt: 'Valor?' },
      {
        key: 'customerName',
        type: 'string',
        label: 'Nome do comprador',
        required: true,
        prompt: 'Nome do comprador?',
      },
      { key: 'customerPhone', type: 'string', label: 'Telefone', required: true },
      { key: 'customerEmail', type: 'string', label: 'Email', required: false },
      { key: 'customerCpf', type: 'string', label: 'CPF', required: false },
    ],
    domainService: 'CheckoutService.createOrder + PaymentService.generatePix',
    emits: ['sale.created', 'payment.pix_generated'],
    evidenceUrlBuilder: '/vendas/${orderId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'sales.create_boleto',
    title: 'Gerar boleto',
    description: 'Cria venda real com boleto bancário. Retorna PDF + código.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productName', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true },
      { key: 'customerPhone', type: 'string', label: 'Telefone', required: true },
      { key: 'customerEmail', type: 'string', label: 'Email', required: true },
      { key: 'customerCpf', type: 'string', label: 'CPF', required: true },
    ],
    domainService: 'CheckoutService.createOrder + PaymentService.generateBoleto',
    emits: ['sale.created', 'payment.boleto_generated'],
    evidenceUrlBuilder: '/vendas/${orderId}',
    surface: ['dashboard-chat'],
  },
];
