import { type CapabilityDefinition } from './capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY — Single source of truth
 *
 * Every action the Kloel can perform is defined here.
 * This IS the registry. Adding a capability here = it is dispatchable.
 */
export const CAPABILITY_DEFINITIONS: CapabilityDefinition[] = [
  // ═══════════ Tier 0 — Auto-consciência ═══════════
  {
    id: 'self.capabilities',
    title: 'Listar capacidades',
    description: 'Mostra o que o Kloel sabe fazer no contexto atual',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CapabilityRegistry.filterFor',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp', 'flow'],
  },
  {
    id: 'self.health',
    title: 'Saúde do sistema',
    description: 'Status de serviços, filas, integrações, banco',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'HealthService.snapshot',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },
  {
    id: 'self.gaps',
    title: 'Listar lacunas',
    description: 'Mostra quais capacidades ainda não estão disponíveis ou estão quebradas',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CapabilityRegistry.listGaps',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },
  {
    id: 'self.audit_log',
    title: 'Log de ações',
    description: 'Mostra as últimas ações executadas pelo Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['audit:read'],
    inputSchema: [
      { key: 'limit', type: 'number', label: 'Quantidade', required: false, description: 'Número de ações para mostrar' },
    ],
    domainService: 'AuditService.recent',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_products',
    title: 'Listar produtos',
    description: 'Lista todos os produtos do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ProductService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'self.explain',
    title: 'Explicar capacidade',
    description: 'Detalha uma capacidade: o que faz, como usar, status',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'capabilityId', type: 'string', label: 'ID', required: true, prompt: 'Qual capacidade você quer saber mais?' },
    ],
    domainService: 'CapabilityRegistry.describe',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },

  {
    id: 'add_url',
    title: 'Adicionar URL',
    description: 'Adiciona URL ao produto',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'url', type: 'string', label: 'URL', required: true },
    ],
    domainService: 'ProductUrlService.add',
    emits: ['product.url_added'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_url',
    title: 'Editar URL',
    description: 'Edita URL de um produto',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'urlId', type: 'string', label: 'ID da URL', required: true },
    ],
    domainService: 'ProductUrlService.update',
    emits: ['product.url_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'delete_url',
    title: 'Remover URL',
    description: 'Remove URL de um produto',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'urlId', type: 'string', label: 'ID da URL', required: true },
    ],
    domainService: 'ProductUrlService.delete',
    emits: ['product.url_deleted'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_social_proof',
    title: 'Prova social',
    description: 'Configura prova social do checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_pixel',
    title: 'Configurar pixel',
    description: 'Configura pixels FB/Google do produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'pixelType', type: 'select', label: 'Tipo', required: true, enum: ['facebook', 'google'] },
      { key: 'pixelId', type: 'string', label: 'ID do pixel', required: true },
    ],
    domainService: 'PixelService.configure',
    emits: ['product.pixel_configured'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_checkouts',
    title: 'Listar checkouts',
    description: 'Lista checkouts do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CheckoutService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_agent_memory',
    title: 'Buscar na memória',
    description: 'Busca na memória do agente por conversas e decisões',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'query', type: 'string', label: 'Busca', required: true },
    ],
    domainService: 'MemoryService.search',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_agent_sessions',
    title: 'Buscar sessões',
    description: 'Busca sessões de conversa anteriores',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'query', type: 'string', label: 'Busca', required: true },
    ],
    domainService: 'SessionService.search',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'request_withdrawal',
    title: 'Solicitar saque',
    description: 'Solicita saque do saldo disponível',
    category: 'MUTATION_SENSITIVE',
    tier: 9,
    requiresConfirmation: true,
    requiredPermissions: ['wallet:write'],
    inputSchema: [
      { key: 'amount', type: 'number', label: 'Valor (R$)', required: true },
    ],
    domainService: 'WalletService.withdraw',
    emits: ['wallet.withdrawal_requested'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'request_anticipation',
    title: 'Solicitar antecipação',
    description: 'Solicita antecipação de recebíveis',
    category: 'MUTATION_SENSITIVE',
    tier: 9,
    requiresConfirmation: true,
    requiredPermissions: ['wallet:write'],
    inputSchema: [],
    domainService: 'WalletService.anticipate',
    emits: ['wallet.anticipation_requested'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_subscription',
    title: 'Gerenciar assinatura',
    description: 'Cancela ou pausa uma assinatura',
    category: 'MUTATION_SENSITIVE',
    tier: 8,
    requiresConfirmation: true,
    requiredPermissions: ['subscription:write'],
    inputSchema: [
      { key: 'subscriptionId', type: 'string', label: 'ID da assinatura', required: false },
    ],
    domainService: 'SubscriptionService.update',
    emits: ['subscription.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_broadcast',
    title: 'Criar campanha',
    description: 'Cria campanha de broadcast',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: true,
    requiredPermissions: ['campaign:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'message', type: 'string', label: 'Mensagem', required: true },
    ],
    domainService: 'CampaignService.createBroadcast',
    emits: ['campaign.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'toggle_autopilot',
    title: 'Ativar/desativar autopilot',
    description: 'Liga ou desliga o modo autopilot',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'AutopilotService.toggle',
    emits: ['autopilot.toggled'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'connect_channel',
    title: 'Conectar canal',
    description: 'Conecta canal de marketing (WhatsApp, Instagram, etc)',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'channel', type: 'select', label: 'Canal', required: true, enum: ['whatsapp', 'instagram', 'facebook', 'tiktok', 'email'] },
    ],
    domainService: 'ChannelService.connect',
    emits: ['channel.connected'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'connect_whatsapp',
    title: 'Conectar WhatsApp',
    description: 'Conecta o WhatsApp ao workspace',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [],
    domainService: 'WhatsAppService.connect',
    emits: ['whatsapp.connected'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_after_pay',
    title: 'Configurar After Pay',
    description: 'Configura pagamento posterior (boleto parcelado, faturado)',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_order_bump',
    title: 'Order bump',
    description: 'Configura order bump (upsell no checkout)',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'bumpProductId', type: 'string', label: 'Produto do bump', required: false },
    ],
    domainService: 'PlanService.configure',
    emits: ['plan.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_affiliate_config',
    title: 'Configuração de afiliados',
    description: 'Mostra configuração do programa de afiliados',
    category: 'QUERY',
    tier: 7,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AffiliateService.getConfig',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_affiliate_config',
    title: 'Atualizar afiliados',
    description: 'Atualiza configuração do programa de afiliados',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'commissionPercent', type: 'number', label: 'Comissão %', required: false },
    ],
    domainService: 'AffiliateService.configure',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'browse_marketplace',
    title: 'Explorar marketplace',
    description: 'Lista produtos públicos para afiliação',
    category: 'QUERY',
    tier: 8,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'MarketplaceService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_details',
    title: 'Detalhes do produto',
    description: 'Mostra detalhes completos de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
    ],
    domainService: 'ProductService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_refunds',
    title: 'Estornos',
    description: 'Lista estornos e reembolsos',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'RefundService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_nps',
    title: 'NPS',
    description: 'Mostra Net Promoter Score',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'NpsService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'upload_plan_image',
    title: 'Upload foto do plano',
    description: 'Faz upload da imagem de um plano',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'Plano', required: true },
    ],
    domainService: 'MediaService.attach + PlanService.setImage',
    emits: ['plan.image_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'upload_product_image',
    title: 'Upload foto do produto',
    description: 'Faz upload da imagem de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
    ],
    domainService: 'MediaService.attach + ProductService.setImage',
    emits: ['product.image_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_order',
    title: 'Criar pedido',
    description: 'Cria pedido/venda manual',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
    ],
    domainService: 'CheckoutService.createOrder',
    emits: ['sale.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_whatsapp_status',
    title: 'Status WhatsApp',
    description: 'Verifica status da conexão WhatsApp',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WhatsAppService.status',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_coupons',
    title: 'Listar cupons',
    description: 'Lista cupons de desconto',
    category: 'QUERY',
    tier: 4,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CouponService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_campaign',
    title: 'Criar campanha',
    description: 'Cria campanha de marketing',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: true,
    requiredPermissions: ['campaign:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
    ],
    domainService: 'CampaignService.create',
    emits: ['campaign.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_flow',
    title: 'Criar fluxo',
    description: 'Cria fluxo de automação',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['flow:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'trigger', type: 'string', label: 'Gatilho', required: true },
    ],
    domainService: 'FlowService.create',
    emits: ['flow.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_flows',
    title: 'Listar fluxos',
    description: 'Lista fluxos de automação',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'FlowService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'send_whatsapp_message',
    title: 'Enviar WhatsApp',
    description: 'Envia mensagem via WhatsApp',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [
      { key: 'phone', type: 'string', label: 'Telefone', required: true },
      { key: 'message', type: 'string', label: 'Mensagem', required: true },
    ],
    domainService: 'MessagingService.sendWhatsApp',
    emits: ['whatsapp.message_sent'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'send_channel_message',
    title: 'Enviar por canal',
    description: 'Envia mensagem por canal específico',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['channel:write'],
    inputSchema: [
      { key: 'channel', type: 'string', label: 'Canal', required: true },
      { key: 'message', type: 'string', label: 'Mensagem', required: true },
    ],
    domainService: 'ChannelService.send',
    emits: ['channel.message_sent'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_analytics',
    title: 'Analytics',
    description: 'Obtém métricas e analytics do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'metric', type: 'string', label: 'Métrica', required: false },
      { key: 'period', type: 'string', label: 'Período', required: false },
    ],
    domainService: 'AnalyticsService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_lead_details',
    title: 'Detalhes do lead',
    description: 'Mostra detalhes de um lead',
    category: 'QUERY',
    tier: 8,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'leadId', type: 'string', label: 'Lead', required: true },
    ],
    domainService: 'LeadService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_order_details',
    title: 'Detalhes do pedido',
    description: 'Mostra detalhes de um pedido',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'orderId', type: 'string', label: 'Pedido', required: true },
    ],
    domainService: 'OrderService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_ai_config',
    title: 'Configuração IA do produto',
    description: 'Mostra configuração de IA de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
    ],
    domainService: 'ProductAIConfigService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_billing_status',
    title: 'Status faturamento',
    description: 'Mostra status de faturamento e plano',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'BillingService.status',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'change_plan',
    title: 'Mudar plano',
    description: 'Altera o plano do workspace',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['billing:write'],
    inputSchema: [
      { key: 'plan', type: 'string', label: 'Novo plano', required: true },
    ],
    domainService: 'BillingService.changePlan',
    emits: ['billing.plan_changed'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'remember_user_info',
    title: 'Lembrar informação',
    description: 'Salva informação do usuário na memória',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'key', type: 'string', label: 'Chave', required: true },
      { key: 'value', type: 'string', label: 'Valor', required: true },
    ],
    domainService: 'MemoryService.set',
    emits: ['memory.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'transcribe_audio',
    title: 'Transcrever áudio',
    description: 'Transcreve áudio para texto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'audioUrl', type: 'string', label: 'URL do áudio', required: true },
    ],
    domainService: 'AudioService.transcribe',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'save_business_info',
    title: 'Salvar info do negócio',
    description: 'Salva informações do negócio',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'businessName', type: 'string', label: 'Nome', required: false },
    ],
    domainService: 'WorkspaceService.updateInfo',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'set_brand_voice',
    title: 'Definir voz da marca',
    description: 'Define tom de voz da marca',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'tone', type: 'string', label: 'Tom', required: true },
    ],
    domainService: 'BrandService.setVoice',
    emits: ['brand.voice_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_workspace_settings',
    title: 'Atualizar configurações',
    description: 'Atualiza configurações do workspace',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'businessName', type: 'string', label: 'Nome', required: false },
    ],
    domainService: 'WorkspaceService.updateSettings',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'read_source_file',
    title: 'Ler código fonte',
    description: 'Lê arquivo fonte do Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'path', type: 'string', label: 'Caminho', required: true },
    ],
    domainService: 'CodeAccessService.read',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'send_audio',
    title: 'Enviar áudio',
    description: 'Envia mensagem de áudio',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [
      { key: 'phone', type: 'string', label: 'Telefone', required: true },
    ],
    domainService: 'MessagingService.sendAudio',
    emits: ['whatsapp.audio_sent'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'send_document',
    title: 'Enviar documento',
    description: 'Envia documento via WhatsApp',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [
      { key: 'phone', type: 'string', label: 'Telefone', required: true },
    ],
    domainService: 'MessagingService.sendDocument',
    emits: ['whatsapp.document_sent'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'send_voice_note',
    title: 'Enviar nota de voz',
    description: 'Envia nota de voz via WhatsApp',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [
      { key: 'phone', type: 'string', label: 'Telefone', required: true },
    ],
    domainService: 'MessagingService.sendVoiceNote',
    emits: ['whatsapp.voice_sent'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'set_business_hours',
    title: 'Horário comercial',
    description: 'Define horário de funcionamento',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'start', type: 'string', label: 'Início', required: true },
      { key: 'end', type: 'string', label: 'Fim', required: true },
    ],
    domainService: 'WorkspaceService.setHours',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'set_sales_policy',
    title: 'Política de vendas',
    description: 'Define política de vendas do workspace',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'policy', type: 'string', label: 'Política', required: true },
    ],
    domainService: 'WorkspaceService.setPolicy',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_whatsapp_chats',
    title: 'Conversas WhatsApp',
    description: 'Lista conversas do WhatsApp',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [],
    domainService: 'WhatsAppService.listChats',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_whatsapp_contacts',
    title: 'Contatos WhatsApp',
    description: 'Lista contatos do WhatsApp',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [],
    domainService: 'WhatsAppService.listContacts',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_whatsapp_contact',
    title: 'Criar contato WhatsApp',
    description: 'Cria novo contato no WhatsApp',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [
      { key: 'phone', type: 'string', label: 'Telefone', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: true },
    ],
    domainService: 'WhatsAppService.createContact',
    emits: ['whatsapp.contact_created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_billing_info',
    title: 'Atualizar faturamento',
    description: 'Atualiza informações de cobrança/plano',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['billing:write'],
    inputSchema: [],
    domainService: 'BillingService.update',
    emits: ['billing.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_churn',
    title: 'Churn',
    description: 'Mostra taxa de cancelamento',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ChurnService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_social_channels',
    title: 'Canais sociais',
    description: 'Lista canais sociais conectados',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ChannelService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_product',
    title: 'Criar produto',
    description: 'Cria novo produto no catálogo',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'price', type: 'number', label: 'Preço (R$)', required: true },
    ],
    domainService: 'ProductService.create',
    emits: ['product.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'save_product',
    title: 'Salvar produto',
    description: 'Cria ou atualiza um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'price', type: 'number', label: 'Preço (R$)', required: true },
    ],
    domainService: 'ProductService.create',
    emits: ['product.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_plan',
    title: 'Criar plano',
    description: 'Cria novo plano para um produto',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'price', type: 'number', label: 'Preço', required: true },
    ],
    domainService: 'PlanService.create',
    emits: ['plan.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_checkout',
    title: 'Criar checkout',
    description: 'Cria novo checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: true },
    ],
    domainService: 'CheckoutService.create',
    emits: ['checkout.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_coupon',
    title: 'Criar cupom',
    description: 'Cria novo cupom de desconto',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'code', type: 'string', label: 'Código', required: true },
      { key: 'discountType', type: 'select', label: 'Tipo', required: true, enum: ['percentage', 'fixed'] },
      { key: 'discountValue', type: 'number', label: 'Valor', required: true },
    ],
    domainService: 'CouponService.create',
    emits: ['coupon.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_product',
    title: 'Atualizar produto',
    description: 'Atualiza dados de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: false },
    ],
    domainService: 'ProductService.update',
    emits: ['product.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_plan',
    title: 'Atualizar plano',
    description: 'Atualiza dados de um plano',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'Plano', required: true },
    ],
    domainService: 'PlanService.update',
    emits: ['plan.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_checkout',
    title: 'Atualizar checkout',
    description: 'Atualiza dados de um checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'Checkout', required: true },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_coupon',
    title: 'Atualizar cupom',
    description: 'Atualiza dados de um cupom',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'couponId', type: 'string', label: 'Cupom', required: true },
    ],
    domainService: 'CouponService.update',
    emits: ['coupon.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'delete_product',
    title: 'Excluir produto',
    description: 'Remove um produto permanentemente',
    category: 'MUTATION_SENSITIVE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
    ],
    domainService: 'ProductService.delete',
    emits: ['product.deleted'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'delete_plan',
    title: 'Excluir plano',
    description: 'Remove um plano permanentemente',
    category: 'MUTATION_SENSITIVE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'Plano', required: true },
    ],
    domainService: 'PlanService.delete',
    emits: ['plan.deleted'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'delete_checkout',
    title: 'Excluir checkout',
    description: 'Remove um checkout permanentemente',
    category: 'MUTATION_SENSITIVE',
    tier: 3,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'Checkout', required: true },
    ],
    domainService: 'CheckoutService.delete',
    emits: ['checkout.deleted'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'toggle_theme',
    title: 'Alternar tema',
    description: 'Alterna entre tema claro e escuro',
    category: 'CONFIGURATION',
    tier: 11,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'theme', type: 'select', label: 'Tema', required: true, enum: ['light', 'dark'] },
    ],
    domainService: 'ThemeService.set',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_web',
    title: 'Buscar na web',
    description: 'Busca informações na internet',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'query', type: 'string', label: 'Busca', required: true },
    ],
    domainService: 'SearchService.web',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_codebase',
    title: 'Buscar no código',
    description: 'Busca no código-fonte do Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'query', type: 'string', label: 'Busca', required: true },
    ],
    domainService: 'CodeAccessService.search',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_fiscal_data',
    title: 'Atualizar dados fiscais',
    description: 'Atualiza CPF/CNPJ e dados fiscais',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'personType', type: 'select', label: 'Tipo', required: true, enum: ['PF', 'PJ'] },
      { key: 'document', type: 'string', label: 'CPF/CNPJ', required: true },
    ],
    domainService: 'AccountService.updateFiscalData',
    emits: ['account.fiscal_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_affiliates',
    title: 'Listar afiliados',
    description: 'Lista afiliados do programa',
    category: 'QUERY',
    tier: 7,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AffiliateService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_ai_persona',
    title: 'Configurar persona IA',
    description: 'Configura a persona e tom de voz da IA',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'personality', type: 'select', label: 'Personalidade', required: false, enum: ['formal', 'informal', 'friendly', 'professional'] },
      { key: 'tone', type: 'string', label: 'Tom de voz', required: false },
    ],
    domainService: 'AIConfigService.update',
    emits: ['ai.persona_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_settings',
    title: 'Configurações',
    description: 'Mostra configurações do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WorkspaceService.getSettings',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_dashboard_summary',
    title: 'Resumo do dashboard',
    description: 'Mostra resumo do dashboard: vendas, leads, oportunidades',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'DashboardService.summary',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_orders',
    title: 'Listar vendas/pedidos',
    description: 'Lista vendas e pedidos do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'status', type: 'select', label: 'Status', required: false, enum: ['pending', 'paid', 'cancelled'] },
    ],
    domainService: 'OrderService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_sales_summary',
    title: 'Resumo de vendas',
    description: 'Mostra resumo de vendas: total, receita, ticket médio',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'SalesService.summary',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_leads',
    title: 'Listar leads',
    description: 'Lista leads do CRM com filtros',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CrmService.listLeads',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_wallet_balance',
    title: 'Saldo da carteira',
    description: 'Mostra saldo disponível, pendente e total',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getBalance',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_wallet_statement',
    title: 'Extrato da carteira',
    description: 'Mostra extrato de transações',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getStatement',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_abandonments',
    title: 'Carrinhos abandonados',
    description: 'Lista carrinhos abandonados recentes',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AbandonmentService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_plans',
    title: 'Planos do produto',
    description: 'Lista todos os planos de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
    ],
    domainService: 'PlanService.listForProduct',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_reviews',
    title: 'Avaliações',
    description: 'Lista avaliações de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
    ],
    domainService: 'ReviewService.listForProduct',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_urls',
    title: 'URLs do produto',
    description: 'Lista URLs cadastradas de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
    ],
    domainService: 'ProductUrlService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'delete_coupon',
    title: 'Excluir cupom',
    description: 'Remove um cupom permanentemente',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'couponId', type: 'string', label: 'ID do cupom', required: true },
    ],
    domainService: 'CouponService.delete',
    emits: ['coupon.deleted'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'validate_coupon',
    title: 'Validar cupom',
    description: 'Verifica se um cupom é válido para um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'code', type: 'string', label: 'Código', required: true },
      { key: 'productId', type: 'string', label: 'Produto', required: true },
    ],
    domainService: 'CouponService.validate',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'upload_document',
    title: 'Enviar documento',
    description: 'Anexa documento (PDF/imagem) aos documentos fiscais',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'documentType', type: 'select', label: 'Tipo', required: true, enum: ['identity', 'contract', 'cnpj_card'] },
    ],
    domainService: 'DocumentService.upload',
    emits: ['account.document_uploaded'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_subscriptions',
    title: 'Listar assinaturas',
    description: 'Lista assinaturas ativas do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'SubscriptionService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_shipping',
    title: 'Configurar frete',
    description: 'Configura frete e entrega de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'shippingType', type: 'select', label: 'Tipo', required: false, enum: ['free', 'fixed', 'variable'] },
    ],
    domainService: 'ShippingService.configure',
    emits: ['product.shipping_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_warranty',
    title: 'Configurar garantia',
    description: 'Define garantia em dias de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'warrantyDays', type: 'number', label: 'Dias de garantia', required: true },
    ],
    domainService: 'ProductService.update',
    emits: ['product.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_exit_intent',
    title: 'Popup de saída',
    description: 'Ativa/desativa popup de exit intent no checkout',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
  },
  // ═══════════ Tier 1 — Produtos: Criar ═══════════
  {
    id: 'products.create',
    title: 'Criar produto',
    description: 'Cria um novo produto no catálogo do workspace',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true, prompt: 'Qual o nome do produto?' },
      { key: 'description', type: 'string', label: 'Descrição', required: false },
      { key: 'category', type: 'string', label: 'Categoria', required: false },
      { key: 'format', type: 'select', label: 'Formato', required: false, enum: ['físico', 'digital', 'híbrido'] },
      { key: 'price', type: 'number', label: 'Preço (R$)', required: true, prompt: 'Qual o preço?' },
    ],
    domainService: 'ProductService.create',
    emits: ['product.created'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.upload_image',
    title: 'Upload imagem do produto',
    description: 'Anexa uma imagem enviada no chat ao produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'imageFile', type: 'file', label: 'Arquivo de imagem', required: true },
    ],
    domainService: 'MediaService.attach + ProductService.setImage',
    emits: ['product.image_updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.update',
    title: 'Editar produto',
    description: 'Edita dados gerais de um produto existente',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: false },
      { key: 'description', type: 'string', label: 'Descrição', required: false },
      { key: 'active', type: 'boolean', label: 'Disponível para venda', required: false },
      { key: 'salesPageUrl', type: 'string', label: 'URL da página de vendas', required: false },
    ],
    domainService: 'ProductService.update',
    emits: ['product.updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 2 — Planos ═══════════
  {
    id: 'plans.create',
    title: 'Criar plano',
    description: 'Cria um novo plano/variação para um produto',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome do plano', required: true, prompt: 'Nome do plano? (ex: "1 Frasco")' },
      { key: 'price', type: 'number', label: 'Valor (R$)', required: true, prompt: 'Qual o valor?' },
      { key: 'maxInstallments', type: 'number', label: 'Parcelas máx.', required: false },
      { key: 'acceptPix', type: 'boolean', label: 'Aceitar PIX', required: false },
      { key: 'acceptCard', type: 'boolean', label: 'Aceitar cartão', required: false },
      { key: 'acceptBoleto', type: 'boolean', label: 'Aceitar boleto', required: false },
    ],
    domainService: 'PlanService.create',
    emits: ['plan.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.update',
    title: 'Editar plano',
    description: 'Edita um plano existente: valor, parcelas, disponibilidade',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'ID do plano', required: true },
      { key: 'price', type: 'number', label: 'Valor', required: false },
      { key: 'active', type: 'boolean', label: 'Disponível para venda', required: false },
    ],
    domainService: 'PlanService.update',
    emits: ['plan.updated'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 3 — Checkouts ═══════════
  {
    id: 'checkouts.create',
    title: 'Criar checkout',
    description: 'Cria checkout vinculado a planos de um produto com personalização',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome do checkout', required: true, prompt: 'Nome do checkout?' },
      { key: 'acceptPix', type: 'boolean', label: 'Aceitar PIX', required: false },
      { key: 'acceptCard', type: 'boolean', label: 'Aceitar cartão', required: false },
      { key: 'acceptBoleto', type: 'boolean', label: 'Aceitar boleto', required: false },
      { key: 'buttonText', type: 'string', label: 'Texto do botão', required: false },
    ],
    domainService: 'CheckoutService.create',
    emits: ['checkout.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.update',
    title: 'Editar checkout',
    description: 'Edita checkout existente',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'buttonText', type: 'string', label: 'Texto do botão', required: false },
      { key: 'active', type: 'boolean', label: 'Ativo', required: false },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 4 — Cupons ═══════════
  {
    id: 'coupons.create',
    title: 'Criar cupom',
    description: 'Cria cupom de desconto para um produto',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'code', type: 'string', label: 'Código', required: true, prompt: 'Código do cupom?' },
      { key: 'discountType', type: 'select', label: 'Tipo', required: true, enum: ['percentage', 'fixed'] },
      { key: 'discountValue', type: 'number', label: 'Valor', required: true },
      { key: 'usageLimit', type: 'number', label: 'Limite de usos', required: false },
    ],
    domainService: 'CouponService.create',
    emits: ['coupon.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'coupons.delete',
    title: 'Excluir cupom',
    description: 'Remove um cupom de desconto',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'couponId', type: 'string', label: 'ID do cupom', required: true },
    ],
    domainService: 'CouponService.delete',
    emits: ['coupon.deleted'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 5 — Vendas reais (CRÍTICO) ═══════════
  {
    id: 'generate_pix',
    title: 'Gerar PIX',
    description: 'Cria venda real com PIX. Retorna copia-e-cola + QR Code.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true },
    ],
    domainService: 'CheckoutService.createOrder + PaymentService.generatePix',
    emits: ['sale.created', 'payment.pix_generated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'generate_boleto',
    title: 'Gerar boleto',
    description: 'Cria venda real com boleto bancário.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true },
    ],
    domainService: 'CheckoutService.createOrder + PaymentService.generateBoleto',
    emits: ['sale.created', 'payment.boleto_generated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_payment_link',
    title: 'Link de pagamento',
    description: 'Gera link de pagamento para um lead',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
    ],
    domainService: 'PaymentService.createPayment',
    emits: ['payment.link_created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'sales.create_pix',
    title: 'Gerar PIX',
    description: 'Cria venda real com PIX. Retorna copia-e-cola + QR Code.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productName', type: 'string', label: 'Produto', required: true, prompt: 'Qual produto?' },
      { key: 'amount', type: 'number', label: 'Valor (R$)', required: true, prompt: 'Valor?' },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true, prompt: 'Nome do comprador?' },
      { key: 'customerPhone', type: 'string', label: 'Telefone', required: true },
      { key: 'customerEmail', type: 'string', label: 'Email', required: false },
      { key: 'customerCpf', type: 'string', label: 'CPF', required: false },
    ],
    domainService: 'CheckoutService.createOrder + PaymentService.generatePix',
    emits: ['sale.created', 'payment.pix_generated'],
    evidenceUrlBuilder: '/vendas/${orderId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'sales.create_boleto',
    title: 'Gerar boleto',
    description: 'Cria venda real com boleto bancário. Retorna PDF + código.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productName', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true },
      { key: 'customerPhone', type: 'string', label: 'Telefone', required: true },
      { key: 'customerEmail', type: 'string', label: 'Email', required: true },
      { key: 'customerCpf', type: 'string', label: 'CPF', required: true },
    ],
    domainService: 'CheckoutService.createOrder + PaymentService.generateBoleto',
    emits: ['sale.created', 'payment.boleto_generated'],
    evidenceUrlBuilder: '/vendas/${orderId}',
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 6 — URLs ═══════════
  {
    id: 'urls.add',
    title: 'Adicionar URL',
    description: 'Adiciona URL (página de venda, landing page) a um produto',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'url', type: 'string', label: 'URL', required: true },
      { key: 'description', type: 'string', label: 'Descrição', required: true },
    ],
    domainService: 'ProductUrlService.add',
    emits: ['product.url_added'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 7 — Afiliados ═══════════
  {
    id: 'affiliates.configure',
    title: 'Configurar afiliados',
    description: 'Ativa/desativa e configura o programa de afiliados do produto',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar programa?', required: true },
      { key: 'commissionPercent', type: 'number', label: 'Comissão (%)', required: false },
    ],
    domainService: 'AffiliateService.configure',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 8 — CRM ═══════════
  {
    id: 'crm.pipeline',
    title: 'Pipeline CRM',
    description: 'Mostra o pipeline CRM com estágios e leads',
    category: 'QUERY',
    tier: 8,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CrmService.getPipeline',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'sales.list',
    title: 'Listar vendas',
    description: 'Lista as vendas do workspace',
    category: 'QUERY',
    tier: 8,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'status', type: 'select', label: 'Status', required: false, enum: ['pending', 'paid', 'cancelled', 'refunded'] },
      { key: 'limit', type: 'number', label: 'Quantidade', required: false },
    ],
    domainService: 'OrderService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 9 — Carteira ═══════════
  {
    id: 'wallet.balance',
    title: 'Saldo da carteira',
    description: 'Mostra o saldo disponível, pendente e total',
    category: 'QUERY',
    tier: 9,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getBalance',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'wallet.withdraw',
    title: 'Solicitar saque',
    description: 'Solicita saque do saldo disponível para conta bancária',
    category: 'MUTATION_SENSITIVE',
    tier: 9,
    requiresConfirmation: true,
    requiredPermissions: ['wallet:write'],
    inputSchema: [
      { key: 'amount', type: 'number', label: 'Valor (R$)', required: true, prompt: 'Qual valor do saque?' },
    ],
    domainService: 'WalletService.requestWithdrawal',
    emits: ['wallet.withdrawal_requested'],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 10 — Relatórios ═══════════
  {
    id: 'reports.operations',
    title: 'Operações',
    description: 'Mostra relatório de operações: vendas, receita, ticket médio',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'period', type: 'select', label: 'Período', required: false, enum: ['today', 'week', 'month', 'year'] },
    ],
    domainService: 'ReportService.getOperations',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'reports.abandonments',
    title: 'Carrinhos abandonados',
    description: 'Mostra carrinhos abandonados no período',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'period', type: 'select', label: 'Período', required: false, enum: ['today', 'week', 'month', 'year'] },
    ],
    domainService: 'ReportService.getAbandonments',
    emits: [],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 11 — Configurações ═══════════
  {
    id: 'account.update_fiscal',
    title: 'Atualizar dados fiscais',
    description: 'Atualiza dados fiscais: CPF/CNPJ, razão social, endereço',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'personType', type: 'select', label: 'Tipo', required: true, enum: ['PF', 'PJ'] },
      { key: 'document', type: 'string', label: 'CPF/CNPJ', required: true },
      { key: 'businessName', type: 'string', label: 'Razão social', required: false },
      { key: 'zipCode', type: 'string', label: 'CEP', required: false },
    ],
    domainService: 'AccountService.updateFiscalData',
    emits: ['account.fiscal_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.update_bank',
    title: 'Atualizar dados bancários',
    description: 'Atualiza conta bancária para recebimento de saques',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'bankCode', type: 'string', label: 'Código do banco', required: true },
      { key: 'agency', type: 'string', label: 'Agência', required: true },
      { key: 'account', type: 'string', label: 'Conta', required: true },
    ],
    domainService: 'AccountService.updateBankAccount',
    emits: ['account.bank_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.set_pix_key',
    title: 'Cadastrar chave PIX',
    description: 'Cadastra ou altera a chave PIX',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'pixKey', type: 'string', label: 'Chave PIX', required: true },
      { key: 'pixKeyType', type: 'select', label: 'Tipo', required: true, enum: ['CPF', 'CNPJ', 'email', 'celular', 'aleatória'] },
    ],
    domainService: 'AccountService.setPixKey',
    emits: ['account.pix_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.upload_document',
    title: 'Enviar documento',
    description: 'Anexa um documento (PDF/imagem) enviado pelo chat aos documentos fiscais',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'documentType', type: 'select', label: 'Tipo', required: true, enum: ['identity', 'contract', 'cnpj_card'] },
    ],
    domainService: 'DocumentService.upload',
    emits: ['account.document_uploaded'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'ui.theme',
    title: 'Alternar tema',
    description: 'Alterna entre tema claro e escuro',
    category: 'CONFIGURATION',
    tier: 11,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'theme', type: 'select', label: 'Tema', required: true, enum: ['light', 'dark'] },
    ],
    domainService: 'ThemeService.set',
    emits: [],
    surface: ['dashboard-chat'],
  },

  // ═══════════ Tier 12 — Marketing ═══════════
  {
    id: 'whatsapp.send',
    title: 'Enviar WhatsApp',
    description: 'Envia mensagem de WhatsApp para um contato',
    category: 'COMMUNICATION',
    tier: 12,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [
      { key: 'phone', type: 'string', label: 'Telefone', required: true },
      { key: 'message', type: 'string', label: 'Mensagem', required: true },
    ],
    domainService: 'MessagingService.sendWhatsApp',
    emits: ['whatsapp.message_sent'],
    surface: ['dashboard-chat'],
  },
];
export const CAPABILITY_MAP = new Map<string, CapabilityDefinition>(
  CAPABILITY_DEFINITIONS.map((cap) => [cap.id, cap]),
);

/** Map capability ID -> tier grouping */
export const CAPABILITIES_BY_TIER: Record<number, CapabilityDefinition[]> =
  CAPABILITY_DEFINITIONS.reduce<Record<number, CapabilityDefinition[]>>((acc, cap) => {
    if (!acc[cap.tier]) acc[cap.tier] = [];
    acc[cap.tier].push(cap);
    return acc;
  }, {});