#!/usr/bin/env node
// tools/auto-pr/batch-job.mjs — Wave 5: batched job emitter.
//
// Em vez de 1 PR por arquivo (`auto-pr` clássico), agrupa N arquivos da MESMA
// classe-de-mudança em UM único job → UM único PR. Mais realista para um
// workflow de produção.
//
// CLI:
//   node tools/auto-pr/batch-job.mjs cluster-annotate --type=nest-controller --limit=30
//   node tools/auto-pr/batch-job.mjs cluster-annotate --type=nest-provider --limit=50
//
// O job resultante vai para graphify-out/auto-pr-jobs/batch-<ts>.json e pode
// ser processado pelo runner ou loop-runner normalmente.

import { argv } from 'node:process';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');

const SUB = argv[2];
const args = argv.slice(3);
const flag = (k) => args.find((a) => a.startsWith(`--${k}=`))?.split('=').slice(1).join('=');

const subs = { 'cluster-annotate': clusterAnnotate };

const fn = subs[SUB];
if (!fn) {
  console.error('usage: batch-job.mjs <cluster-annotate> [opts]');
  process.exit(2);
}
await fn();

async function clusterAnnotate() {
  const type = flag('type') || 'nest-controller';
  const limit = Number(flag('limit') || 30);
  const skipAdmin = (flag('include-admin') || 'false') === 'false';

  const graph = JSON.parse(await readFile(join(ROOT, 'graphify-out/enriched-graph.json'), 'utf8'));
  const nodes = graph.nodes
    .filter((n) => n.type === type && n.file)
    .filter((n) => (skipAdmin ? !n.file.includes('/admin/') : true))
    .filter((n) => !n.file.includes('.spec.'));

  const files = [];
  let touched = 0;
  let skipped = 0;

  for (const node of nodes) {
    if (touched >= limit) break;
    const filePath = join(ROOT, node.file);
    let src;
    try {
      src = await readFile(filePath, 'utf8');
    } catch {
      skipped++;
      continue;
    }
    if (src.includes('@cluster')) {
      skipped++;
      continue;
    }
    const segs = node.file.split('/');
    const area = segs[2] || segs[1];
    const ws = segs[0] === 'backend' ? 'backend' : segs[0] === 'frontend' ? 'frontend' : segs[0] === 'worker' ? 'worker' : 'other';
    const cluster = `whatsapp_saas/${ws}/${area}`;
    const annotation = `/**\n * @cluster ${cluster}\n * L11 multi-agent TaskGraph annotation (batched by tools/auto-pr/batch-job.mjs).\n */\n`;
    const importEnd = src.search(/\n(?=(?:export|class|@|const|function|interface|type)\s)/);
    const updated = importEnd > 0 ? src.slice(0, importEnd + 1) + annotation + src.slice(importEnd + 1) : annotation + src;
    files.push({ path: node.file, content: updated });
    touched++;
  }

  const ts = Date.now();
  const branch = `chore/batch-cluster-tag-${type}-${ts}`;
  const job = {
    title: `chore(auto-batch): tag L11 clusters on ${files.length} ${type} files`,
    body: `Auto-generated by Wave 5 batch-job emitter.\n\nAdds \`/** @cluster <name> */\` JSDoc to ${files.length} ${type} files in a SINGLE PR (vs ${files.length} sequential PRs in Wave 3/4).\n\nDeterministic transform, comment-only, zero behavior impact. Per-file cluster IDs follow the convention \`whatsapp_saas/<workspace>/<area>\`.\n\nFiles:\n${files.map((f) => `- \`${f.path}\``).join('\n')}\n\n- Generator: \`tools/auto-pr/batch-job.mjs cluster-annotate --type=${type} --limit=${limit}\`\n- Runner: \`node tools/auto-pr/runner.mjs <this-job>\``,
    branch,
    base: 'origin/main',
    files,
    shell: [],
  };

  const outDir = join(ROOT, 'graphify-out', 'auto-pr-jobs');
  await mkdir(outDir, { recursive: true });
  const out = join(outDir, `batch-${ts}.json`);
  await writeFile(out, JSON.stringify(job, null, 2));

  console.log(`[batch-job] emitted ${out}`);
  console.log(`[batch-job] files=${files.length} skipped=${skipped} (type=${type} limit=${limit})`);
  console.log(`[batch-job] branch=${branch}`);
}
