#!/usr/bin/env node
// tools/auto-pr/codacy-drain.mjs — Wave 10: real-debt drainer.
//
// Strategy:
//   1) Run `eslint --rule '{"<rule>":"error"}' --fix-dry-run --format json`
//      across backend/frontend/worker for a small SAFE rule allow-list.
//   2) For each file that has a non-empty `output`, emit a batched job that
//      writes the fixed content. Multiple rules can be batched into one PR
//      per (workspace, rule) tuple.
//   3) Each job carries pre-commit shell validators: tsc --noEmit + the
//      target rule re-run to confirm zero residuals.
//
// CLI:
//   node tools/auto-pr/codacy-drain.mjs                # default safe rules
//   node tools/auto-pr/codacy-drain.mjs --rules=R1,R2  # explicit
//   node tools/auto-pr/codacy-drain.mjs --max-files=20 # cap per job
//   node tools/auto-pr/codacy-drain.mjs --dry-run      # report, no jobs
//
// Output: graphify-out/auto-pr-jobs/codacy-<rule>-<ws>-<ts>.json — consumed
// by tools/loop-runner/runner.mjs.

import { argv } from 'node:process';
import { spawn } from 'node:child_process';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const OUT_DIR = join(ROOT, 'graphify-out', 'auto-pr-jobs');

const DEFAULT_SAFE_RULES = [
  // ESLint's own — fully deterministic, autofixable, safe.
  'eol-last',
  'no-trailing-spaces',
  '@typescript-eslint/no-unnecessary-type-assertion',
  'prefer-const',
  'no-extra-semi',
];
const DRY = argv.includes('--dry-run');
const RULES_ARG = argv.find((a) => a.startsWith('--rules='))?.split('=')[1];
const RULES = RULES_ARG ? RULES_ARG.split(',') : DEFAULT_SAFE_RULES;
const MAX_FILES = Number(argv.find((a) => a.startsWith('--max-files='))?.split('=')[1] || 25);
const WORKSPACES = (argv.find((a) => a.startsWith('--ws='))?.split('=')[1] || 'backend,frontend,worker').split(',');

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  let totalJobs = 0;
  let totalFiles = 0;

  for (const ws of WORKSPACES) {
    const wsRoot = join(ROOT, ws);
    for (const rule of RULES) {
      console.log(`[codacy-drain] ${ws} :: ${rule}`);
      const fixes = await runEslintFixDryRun(wsRoot, rule);
      if (fixes.length === 0) {
        console.log(`  no fixes`);
        continue;
      }
      const slice = fixes.slice(0, MAX_FILES);
      console.log(`  ${fixes.length} files have fixes (using first ${slice.length})`);
      totalFiles += slice.length;

      if (DRY) continue;

      const ts = Date.now();
      const ruleSlug = rule.replace(/[^a-z0-9]+/gi, '-').toLowerCase();
      const branch = `auto/codacy-${ws}-${ruleSlug}-${ts}`;
      const job = {
        title: `chore(${ws}): autofix \`${rule}\` on ${slice.length} files`,
        body: `Auto-generated by Wave 10 codacy-drain pipeline.\n\nRule: \`${rule}\`\nWorkspace: \`${ws}\`\nFiles: ${slice.length} of ${fixes.length} matching\n\nESLint --fix-dry-run was run; each file's \`output\` is the post-fix content. Pre-commit validators: workspace tsc --noEmit + the same rule re-run to confirm zero residuals.\n\nFiles:\n${slice.map((f) => `- \`${f.path}\``).join('\n')}`,
        branch,
        base: 'origin/main',
        files: slice.map((f) => ({ path: f.path, content: f.output })),
        shell: [
          `cd ${ws} && npx tsc --noEmit -p tsconfig.json`,
          `cd ${ws} && npx eslint --rule '{"${rule}":"error"}' ${slice.map((f) => `'${relative(wsRoot, join(ROOT, f.path))}'`).join(' ')} --max-warnings=0`,
        ],
      };
      const out = join(OUT_DIR, `codacy-${ws}-${ruleSlug}-${ts}.json`);
      await writeFile(out, JSON.stringify(job, null, 2));
      console.log(`  emitted ${out}`);
      totalJobs++;
    }
  }
  console.log(`\n[codacy-drain] ${totalJobs} jobs, ${totalFiles} total files patched`);
}

async function runEslintFixDryRun(wsRoot, rule) {
  // eslint --no-eslintrc to avoid local config interference; --rule injects only the target.
  const out = await capture(
    ['npx', 'eslint', '.', '--no-eslintrc', '--rule', `{"${rule}":"error"}`, '--fix-dry-run', '--format', 'json'],
    { cwd: wsRoot, swallowExit: true },
  );
  let parsed;
  try {
    const i = out.indexOf('[');
    parsed = JSON.parse(out.slice(i));
  } catch {
    return [];
  }
  const fixes = [];
  for (const r of parsed) {
    if (!r.output || r.output === '') continue;
    const rel = relative(ROOT, r.filePath).split(sep).join('/');
    fixes.push({ path: rel, output: r.output });
  }
  return fixes;
}

function capture(args, { cwd, swallowExit = false } = {}) {
  return new Promise((resolve, reject) => {
    let out = '';
    const child = spawn(args[0], args.slice(1), { cwd, stdio: ['inherit', 'pipe', 'pipe'] });
    child.stdout?.on('data', (d) => (out += d.toString()));
    child.stderr?.on('data', () => {});
    child.on('exit', (code) => (code === 0 || swallowExit ? resolve(out) : reject(new Error(`${args.join(' ')} → ${code}`))));
    child.on('error', reject);
  });
}

await main();
