#!/usr/bin/env node
// tools/auto-pr/generate-jobs.mjs — Wave 3 #5 jobs-from-pattern generator.
//
// Recebe um pattern + transformação e emite N job.json prontos para auto-pr.mjs.
//
// CLI:
//   node tools/auto-pr/generate-jobs.mjs grep <pattern> --replace=<replacement> --files=<glob>
//   node tools/auto-pr/generate-jobs.mjs eslint --rule=<rule> --fix
//   node tools/auto-pr/generate-jobs.mjs graph-query <cluster-type> --action=<id>
//
// Outputs: jobs/<timestamp>-<index>.json (one per file/cluster).
//
// Idempotent — same pattern + state yields same job count.

import { argv, exit } from 'node:process';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join, basename, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { collect, readCapped, rel } from '../graphify-plus/lib/scan.mjs';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');

const SUB = argv[2];
const args = argv.slice(3);
const flag = (k) => args.find((a) => a.startsWith(`--${k}=`))?.split('=').slice(1).join('=');

const OUT_DIR = flag('out') || join(ROOT, 'graphify-out', 'auto-pr-jobs');

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const subs = { grep, eslint: eslintFix, 'graph-query': graphQuery };
  const fn = subs[SUB];
  if (!fn) {
    console.error(`usage: generate-jobs.mjs <grep|eslint|graph-query> ...`);
    console.error(`  grep <pattern> --replace=<R> --files=<extension-list>`);
    console.error(`  eslint --rule=<rule>`);
    console.error(`  graph-query <type> --action=<add-jsdoc|something>`);
    exit(2);
  }
  await fn();
}

/** grep <pat> --replace=<R> --files=ts,tsx — for each match emit a job. */
async function grep() {
  const pat = args[0];
  const replacement = flag('replace');
  const exts = (flag('files') || 'ts,tsx,mts,cts,js,mjs,cjs,jsx').split(',');
  const dirs = (flag('dirs') || 'backend/src,frontend/src,worker').split(',');
  if (!pat || replacement == null) {
    console.error('usage: generate-jobs.mjs grep <pat> --replace=<R> [--files=ts,tsx] [--dirs=...]');
    exit(2);
  }
  const re = new RegExp(pat, 'g');
  let count = 0;
  const ts = Date.now();

  for (const dir of dirs) {
    for await (const file of (await collect(join(ROOT, dir), (_p, n) => exts.some((e) => n.endsWith(`.${e}`))))) {
      const src = await readCapped(file);
      if (!src || !re.test(src)) continue;
      re.lastIndex = 0; // reset
      const updated = src.replace(re, replacement);
      if (updated === src) continue;

      const fileRel = rel(file, ROOT);
      const sluggedFile = fileRel.replace(/[^a-z0-9]+/gi, '-').toLowerCase().slice(0, 60);
      const branch = `auto/grep-${shorten(pat)}-${sluggedFile}-${ts}`;

      const job = {
        title: `chore(auto): grep replace ${pat} → ${replacement.slice(0, 30)} (${fileRel})`,
        body: `Auto-generated by tools/auto-pr/generate-jobs.mjs grep.\n\n• pattern: \`${pat}\`\n• replacement: \`${replacement}\`\n• file: \`${fileRel}\``,
        branch,
        base: 'origin/main',
        labels: ['auto-pr', 'auto-grep'],
        files: [{ path: fileRel, content: updated }],
        shell: shellForFile(fileRel),
      };
      const outFile = join(OUT_DIR, `${ts}-${count.toString().padStart(3, '0')}.json`);
      await writeFile(outFile, JSON.stringify(job, null, 2));
      console.log(`emitted ${outFile} — ${fileRel}`);
      count++;
    }
  }
  console.log(`done: ${count} jobs in ${OUT_DIR}`);
}

/** eslint --rule=foo — runs eslint --fix-dry-run for the rule, emits one job per file with fixes. */
async function eslintFix() {
  const rule = flag('rule');
  if (!rule) {
    console.error('usage: generate-jobs.mjs eslint --rule=<rule>');
    exit(2);
  }
  const ts = Date.now();
  // eslint --rule '{}' --fix-dry-run --format json
  const wss = ['backend', 'frontend', 'worker'];
  let count = 0;
  for (const ws of wss) {
    const out = await capture(['npx', 'eslint', '.', '--rule', `{"${rule}":"error"}`, '--no-eslintrc', '--fix-dry-run', '--format', 'json'], {
      cwd: join(ROOT, ws),
      swallowExit: true,
    });
    let parsed;
    try {
      parsed = JSON.parse(out.slice(out.indexOf('[')));
    } catch {
      continue;
    }
    for (const r of parsed) {
      if (!r.output || r.output === '') continue;
      const fileRel = relative(ROOT, r.filePath).split(sep).join('/');
      const branch = `auto/eslint-${rule.replace(/[^a-z0-9]/gi, '-')}-${count.toString().padStart(3, '0')}-${ts}`;
      const job = {
        title: `fix(auto): eslint --fix \`${rule}\` (${fileRel})`,
        body: `Auto-generated by generate-jobs.mjs eslint --rule=${rule}.`,
        branch,
        base: 'origin/main',
        labels: ['auto-pr', 'auto-eslint'],
        files: [{ path: fileRel, content: r.output }],
        shell: shellForFile(fileRel),
      };
      const outFile = join(OUT_DIR, `${ts}-${count.toString().padStart(3, '0')}.json`);
      await writeFile(outFile, JSON.stringify(job, null, 2));
      console.log(`emitted ${outFile} — ${fileRel}`);
      count++;
    }
  }
  console.log(`done: ${count} jobs`);
}

/** Emit jobs based on a graph-query result (e.g. all `nest-controller` nodes). */
async function graphQuery() {
  const type = args[0];
  const action = flag('action') || 'noop';
  if (!type) {
    console.error('usage: generate-jobs.mjs graph-query <node-type> --action=<id>');
    exit(2);
  }
  const graph = JSON.parse(await readFile(join(ROOT, 'graphify-out/enriched-graph.json'), 'utf8'));
  const matches = graph.nodes.filter((n) => n.type === type);
  console.log(`graph-query: ${matches.length} nodes of type ${type}`);

  const ts = Date.now();
  let count = 0;
  for (const node of matches) {
    if (!node.file) continue;
    const job = {
      title: `chore(auto-graph): ${action} on ${node.label || node.id}`,
      body: `Auto-generated from graph-query type=${type} action=${action}.`,
      branch: `auto/graph-${type}-${count}-${ts}`,
      base: 'origin/main',
      labels: ['auto-pr', 'auto-graph-query'],
      files: [], // intentionally empty — caller can post-process
      shell: [],
      meta: { node },
    };
    const outFile = join(OUT_DIR, `${ts}-${count.toString().padStart(3, '0')}.json`);
    await writeFile(outFile, JSON.stringify(job, null, 2));
    count++;
  }
  console.log(`emitted ${count} jobs`);
}

function shorten(s) {
  return createHash('sha1').update(s).digest('hex').slice(0, 8);
}

function shellForFile(file) {
  if (file.startsWith('backend/')) return ['cd backend && npx tsc --noEmit'];
  if (file.startsWith('frontend/')) return ['cd frontend && npx tsc --noEmit'];
  if (file.startsWith('worker/')) return ['cd worker && npx tsc --noEmit'];
  return [];
}

function capture(argv, { cwd, swallowExit = false } = {}) {
  return new Promise((resolve, reject) => {
    let out = '';
    const child = spawn(argv[0], argv.slice(1), { cwd, stdio: ['inherit', 'pipe', 'pipe'] });
    child.stdout?.on('data', (d) => (out += d.toString()));
    child.stderr?.on('data', () => {});
    child.on('exit', (code) => (code === 0 || swallowExit ? resolve(out) : reject(new Error(`${argv.join(' ')} → ${code}`))));
    child.on('error', reject);
  });
}

await main();
