#!/usr/bin/env node
// tools/auto-pr/hot-to-jobs.mjs — Wave 8: graph:hot → auto-pr bridge.
//
// Reads graph:hot ranking (composite priority: runtime errors, blast-radius,
// doc-staleness, untested) and emits job.json files for the top N hottest
// nodes. Each job adds a /** @hot-now */ JSDoc marker so subsequent diff
// queries can surface "things that were hot this week".
//
// Real signal → real job — not topology alone.
//
// CLI:
//   node tools/auto-pr/hot-to-jobs.mjs --top=10
//   node tools/auto-pr/hot-to-jobs.mjs --top=5 --batch  # one PR for all

import { argv } from 'node:process';
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const TOP = Number(argv.find((a) => a.startsWith('--top='))?.split('=')[1] || 10);
const BATCH = argv.includes('--batch');
const OUT_DIR = join(ROOT, 'graphify-out', 'auto-pr-jobs');

async function main() {
  // Get the hot ranking as JSON.
  const hotJson = await runCapture(['node', 'tools/graphify-plus/lib/hot.mjs', `--top=${TOP * 2}`, '--json']);
  const ranked = JSON.parse(hotJson);

  // Filter: only nodes with a `file` we can annotate.
  const targets = ranked.filter((r) => r.file && r.type !== 'runtime-overlay' && r.type !== 'runtime-queue-overlay').slice(0, TOP);
  if (targets.length === 0) {
    console.log('[hot-to-jobs] no file-bound targets in top — nothing to emit');
    return;
  }

  await mkdir(OUT_DIR, { recursive: true });
  const ts = Date.now();
  const annotated = [];

  for (const t of targets) {
    const filePath = join(ROOT, t.file);
    let src;
    try {
      src = await readFile(filePath, 'utf8');
    } catch {
      continue;
    }
    if (src.includes('@hot-now')) continue;

    const meta = JSON.stringify({ score: t.score, reasons: t.reasons.slice(0, 4) });
    const annotation = `/**\n * @hot-now ${new Date().toISOString().slice(0, 10)} ${meta}\n * Flagged by tools/graphify-plus/lib/hot.mjs — composite priority\n * (runtime errors + blast-radius + doc-staleness + untested signal).\n * Remove this tag once the underlying issue is addressed.\n */\n`;

    const importEnd = src.search(/\n(?=(?:export|class|@|const|function|interface|type)\s)/);
    const updated = importEnd > 0 ? src.slice(0, importEnd + 1) + annotation + src.slice(importEnd + 1) : annotation + src;
    annotated.push({ path: t.file, content: updated, target: t });
  }

  if (BATCH) {
    const branch = `chore/hot-flag-batch-${ts}`;
    const job = {
      title: `chore(auto-hot): tag ${annotated.length} highest-priority files via graph:hot ranker`,
      body: `Auto-generated by Wave 8 hot-to-jobs bridge.\n\nFlags the top-${annotated.length} hottest nodes (composite of runtime errors, blast-radius, doc staleness, untested signal) with \`@hot-now\` JSDoc so subsequent reviews can target them.\n\nTargets:\n${annotated.map((a) => `- \`${a.path}\` (score=${a.target.score}, reasons=${a.target.reasons.slice(0, 3).join(',')})`).join('\n')}\n\nGenerator: \`node tools/auto-pr/hot-to-jobs.mjs --top=${TOP} --batch\``,
      branch,
      base: 'origin/main',
      files: annotated.map((a) => ({ path: a.path, content: a.content })),
      shell: [],
    };
    const out = join(OUT_DIR, `hot-batch-${ts}.json`);
    await writeFile(out, JSON.stringify(job, null, 2));
    console.log(`[hot-to-jobs] emitted batch with ${annotated.length} files → ${out}`);
  } else {
    let count = 0;
    for (const a of annotated) {
      const slug = a.path.replace(/[^a-z0-9]+/gi, '-').toLowerCase().slice(0, 60);
      const branch = `auto/hot-${slug}-${ts}`;
      const job = {
        title: `chore(auto-hot): tag ${a.path.split('/').pop()} (score=${a.target.score})`,
        body: `Wave 8 hot-to-jobs.\n\n• File: \`${a.path}\`\n• Score: ${a.target.score}\n• Reasons: ${a.target.reasons.join(', ')}\n• Type: ${a.target.type}`,
        branch,
        base: 'origin/main',
        files: [{ path: a.path, content: a.content }],
        shell: [],
      };
      await writeFile(join(OUT_DIR, `${ts}-hot-${count.toString().padStart(2, '0')}.json`), JSON.stringify(job, null, 2));
      count++;
    }
    console.log(`[hot-to-jobs] emitted ${count} single-file jobs`);
  }
}

function runCapture(argvList) {
  return new Promise((resolve, reject) => {
    let out = '';
    const child = spawn(argvList[0], argvList.slice(1), { cwd: ROOT, stdio: ['inherit', 'pipe', 'pipe'] });
    child.stdout?.on('data', (d) => (out += d.toString()));
    child.on('exit', (code) => (code === 0 ? resolve(out) : reject(new Error(`${argvList.join(' ')} → ${code}`))));
    child.on('error', reject);
  });
}

await main();
