import { join } from 'node:path';
import { mkdirSync, writeFileSync } from 'node:fs';

export function writeOutputs({ OUT_DIR, domains, services, controllers, modules, processors, events, queues, routes, prismaUsage, symbols }) {
// ─────────── write outputs ───────────
mkdirSync(OUT_DIR, { recursive: true });

function writeMd(name, content) {
  writeFileSync(join(OUT_DIR, name), content);
  console.log(`  wrote docs/architecture/${name}`);
}

// 1) CANONICAL_DOMAINS.md
{
  const sorted = [...domains.entries()].sort((a, b) => b[1].files.size - a[1].files.size);
  const lines = [
    '# Kloel Canonical Domains',
    '',
    '> Generated by `tools/canonicalize/scan.mjs`. Static inventory of every domain (top-level module) in the codebase, with file count, service count, and event surface.',
    '',
    `Total domains: ${domains.size}. Total files scanned: ${tsFiles.length}.`,
    '',
    '| Domain | Files | Services | Controllers | Modules | Events |',
    '|---|---:|---:|---:|---:|---:|',
  ];
  for (const [domain, d] of sorted) {
    lines.push(`| \`${domain}\` | ${d.files.size} | ${d.services.length} | ${d.controllers.length} | ${d.modules.length} | ${d.events.size} |`);
  }
  writeMd('CANONICAL_DOMAINS.md', lines.join('\n') + '\n');
}

// 2) SERVICE_CATALOG.md
{
  const byDomain = new Map();
  for (const s of services) {
    const d = domainOf(s.file);
    if (!byDomain.has(d)) byDomain.set(d, []);
    byDomain.get(d).push(s);
  }
  const lines = [
    '# Kloel Service Catalog',
    '',
    '> Every `@Injectable()` class with its domain assignment. Generated by `tools/canonicalize/scan.mjs`.',
    '',
    `Total services: ${services.length}. Sorted by domain.`,
    '',
  ];
  for (const [domain, list] of [...byDomain.entries()].sort((a, b) => b[1].length - a[1].length)) {
    lines.push(`## ${domain} (${list.length})`);
    lines.push('');
    for (const s of list.sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`- \`${s.name}\` — \`${s.file}\``);
    }
    lines.push('');
  }
  writeMd('SERVICE_CATALOG.md', lines.join('\n'));
}

// 3) CAPABILITY_MAP.md
{
  const lines = [
    '# Kloel Capability Map',
    '',
    '> Functional capabilities detected via canonical name patterns. Generated by `tools/canonicalize/scan.mjs`.',
    '',
    'Each capability lists every implementation found across the codebase. A capability with **>1 implementation** is a candidate for canonicalization (pick one canonical name, deprecate the rest).',
    '',
  ];
  for (const [cap, impls] of capabilityMap) {
    const marker = impls.length > 1 ? ' ⚠️ duplicated' : impls.length === 1 ? '' : ' ⚪ not implemented';
    lines.push(`## CAPABILITY: \`${cap}\` (${impls.length} implementations${marker})`);
    lines.push('');
    if (impls.length === 0) {
      lines.push('No implementation detected. May not be a feature of this codebase.');
      lines.push('');
      continue;
    }
    for (const impl of impls) {
      lines.push(`- \`${impl.name}\` (${impl.kind}) — \`${impl.file}:${impl.line}\``);
    }
    lines.push('');
  }
  writeMd('CAPABILITY_MAP.md', lines.join('\n'));
}

// 4) EVENT_TAXONOMY.md
{
  const lines = [
    '# Kloel Event Taxonomy',
    '',
    '> All `.emit(...)` and `.on(...)` strings detected statically. Generated by `tools/canonicalize/scan.mjs`.',
    '',
    `Total unique events: ${events.size}. Events with naming variants (same canonical form, different cases/separators): ${eventDuplicates.length}.`,
    '',
    '## Variants flagged for canonicalization',
    '',
  ];
  if (eventDuplicates.length === 0) {
    lines.push('None detected. ✅');
  } else {
    for (const [canonical, variants] of eventDuplicates.sort((a, b) => b[1].size - a[1].size)) {
      lines.push(`### \`${canonical}\``);
      lines.push('');
      for (const v of [...variants].sort()) {
        const refs = events.get(v) ?? [];
        lines.push(`- \`${v}\` (${refs.length} refs)`);
        for (const r of refs.slice(0, 5)) {
          lines.push(`  - ${r.kind} in \`${r.file}\``);
        }
      }
      lines.push('');
    }
  }
  lines.push('');
  lines.push('## All events (alphabetical)');
  lines.push('');
  for (const [name, refs] of [...events.entries()].sort()) {
    const emits = refs.filter((r) => r.kind === 'emit').length;
    const listens = refs.filter((r) => r.kind === 'listen').length;
    lines.push(`- \`${name}\` — ${emits} emit / ${listens} listen`);
  }
  writeMd('EVENT_TAXONOMY.md', lines.join('\n'));
}

// 5) DUPLICATION_REGISTER.md
{
  const lines = [
    '# Kloel Duplication Register',
    '',
    '> Symbols (classes, interfaces, types, functions) exported from multiple files. Generated by `tools/canonicalize/scan.mjs`.',
    '',
    `Total cross-file duplicates: ${exactDuplicates.length}. Sorted by severity (most-duplicated first).`,
    '',
    '## Top 100 duplicated exports',
    '',
    '| Exported name | # files | Files |',
    '|---|---:|---|',
  ];
  for (const d of exactDuplicates.slice(0, 100)) {
    const sample = d.files.slice(0, 3).map((f) => `\`${f}\``).join('<br>');
    const extra = d.files.length > 3 ? `<br>… +${d.files.length - 3} more` : '';
    lines.push(`| \`${d.name}\` | ${d.files.length} | ${sample}${extra} |`);
  }
  writeMd('DUPLICATION_REGISTER.md', lines.join('\n') + '\n');
}

// 6) CANONICAL_VOCABULARY.md (starter — depends on Daniel's choices)
{
  const lines = [
    '# Kloel Canonical Vocabulary',
    '',
    '> Starter dictionary. Each row maps a canonical name to forbidden/deprecated aliases. Extend as canonicalization decisions are made.',
    '',
    '| Canonical | Aliases to migrate | Notes |',
    '|---|---|---|',
    '| `ChannelSession` | `whatsappSession`, `waSession`, `connection`, `instance`, `botSession` | Authoritative session entity across all messaging channels |',
    '| `Contact` | `Lead`, `Client`, `Customer`, `Prospect`, `User` (in messaging context) | General entity; `Lead`/`Customer` allowed only as funnel-stage labels |',
    '| `MessageDispatchService` | `WahaService.sendMessage`, `WhatsappApiService.sendText`, `MessageWorker.process` (in send role) | Single send pipeline; channel-specific adapters live below it |',
    '| `Webhook` | `Hook`, `Callback`, `Notification`, `IncomingEvent` | External provider → internal event boundary |',
    '| `Workspace` | `Tenant`, `Org`, `Account` (in scope context) | The multi-tenant unit |',
    '',
    '## How to add an entry',
    '',
    '1. Find duplication: see `DUPLICATION_REGISTER.md` or `CAPABILITY_MAP.md`',
    '2. Pick the canonical name (preferred: domain-clear, no abbreviation)',
    '3. List all aliases',
    '4. Add row above',
    '5. Migration codemod can read this table to perform safe renames via `mcp__atomic-edit__atomic_rename_symbol_cross_file`',
  ];
  writeMd('CANONICAL_VOCABULARY.md', lines.join('\n') + '\n');
}

// 7) DEPRECATION_MAP.md (template)
{
  const lines = [
    '# Kloel Deprecation Map',
    '',
    '> Tracks each symbol marked as deprecated, with its replacement and migration deadline.',
    '',
    '| Deprecated symbol | Replacement | Deadline | Status |',
    '|---|---|---|---|',
    '| _(none yet — populate as canonicalization migrations land)_ | | | |',
  ];
  writeMd('DEPRECATION_MAP.md', lines.join('\n') + '\n');
}

// 8) ROUTES_CATALOG.md
{
  const byVerb = new Map();
  for (const r of routes) {
    if (!byVerb.has(r.verb)) byVerb.set(r.verb, []);
    byVerb.get(r.verb).push(r);
  }
  const lines = [
    '# Kloel Routes Catalog',
    '',
    '> Every `@Get/@Post/@Put/@Delete/@Patch` route in the backend. Generated by `tools/canonicalize/scan.mjs`.',
    '',
    `Total routes: ${routes.length}.`,
    '',
  ];
  for (const [verb, list] of [...byVerb.entries()].sort()) {
    lines.push(`## ${verb} (${list.length})`);
    lines.push('');
    for (const r of list.sort((a, b) => (a.path || '').localeCompare(b.path || ''))) {
      lines.push(`- \`${r.path || '(root)'}\` — \`${r.file}\``);
    }
    lines.push('');
  }
  writeMd('ROUTES_CATALOG.md', lines.join('\n'));
}

// 9) QUEUES_CATALOG.md
{
  const lines = [
    '# Kloel Queues Catalog',
    '',
    '> Every BullMQ Queue() and @Processor() detected. Generated by `tools/canonicalize/scan.mjs`.',
    '',
    `Total unique queues: ${queues.size}. Total processors: ${processors.length}.`,
    '',
    '## Queues',
    '',
  ];
  for (const [q, files] of [...queues.entries()].sort()) {
    lines.push(`### \`${q}\``);
    for (const f of [...new Set(files)]) lines.push(`- \`${f}\``);
    lines.push('');
  }
  lines.push('## Processors');
  lines.push('');
  for (const p of processors.sort((a, b) => (a.queue || '').localeCompare(b.queue || ''))) {
    lines.push(`- \`${p.name}\` → queue \`${p.queue}\` (\`${p.file}\`)`);
  }
  writeMd('QUEUES_CATALOG.md', lines.join('\n') + '\n');
}

// 10) PRISMA_USAGE.md
{
  const lines = [
    '# Kloel Prisma Model Usage',
    '',
    '> Each Prisma model with the files that read/write it. Generated by `tools/canonicalize/scan.mjs`.',
    '',
    `Total models referenced: ${prismaUsage.size}.`,
    '',
    '| Model | # files | Files (top 3) |',
    '|---|---:|---|',
  ];
  for (const [model, fileSet] of [...prismaUsage.entries()].sort((a, b) => b[1].size - a[1].size)) {
    const top = [...fileSet].slice(0, 3).map((f) => `\`${f}\``).join('<br>');
    const extra = fileSet.size > 3 ? `<br>… +${fileSet.size - 3}` : '';
    lines.push(`| \`${model}\` | ${fileSet.size} | ${top}${extra} |`);
  }
  writeMd('PRISMA_USAGE.md', lines.join('\n') + '\n');
}

// 11) ARCHITECTURE_INDEX.md (entry point)
{
  const lines = [
    '# Kloel Architecture',
    '',
    '> Generated canonical inventory of the Kloel codebase. **Read order:**',
    '',
    '1. **[CANONICAL_DOMAINS.md](./CANONICAL_DOMAINS.md)** — top-level domains and their size',
    '2. **[SERVICE_CATALOG.md](./SERVICE_CATALOG.md)** — every `@Injectable()` service per domain',
    '3. **[CAPABILITY_MAP.md](./CAPABILITY_MAP.md)** — what the system can do, grouped by capability',
    '4. **[EVENT_TAXONOMY.md](./EVENT_TAXONOMY.md)** — every event emitted/listened, with naming variants flagged',
    '5. **[DUPLICATION_REGISTER.md](./DUPLICATION_REGISTER.md)** — same-name exports across multiple files',
    '6. **[CANONICAL_VOCABULARY.md](./CANONICAL_VOCABULARY.md)** — official names vs aliases (starter)',
    '7. **[DEPRECATION_MAP.md](./DEPRECATION_MAP.md)** — symbols marked for removal with deadlines',
    '8. **[ROUTES_CATALOG.md](./ROUTES_CATALOG.md)** — HTTP routes',
    '9. **[QUEUES_CATALOG.md](./QUEUES_CATALOG.md)** — BullMQ queues + processors',
    '10. **[PRISMA_USAGE.md](./PRISMA_USAGE.md)** — Prisma model → files that touch it',
    '',
    '## Regenerate',
    '',
    '```sh',
    'node tools/canonicalize/scan.mjs',
    '```',
    '',
    '## Operating principle',
    '',
    'These files are an **inventory**, not a target. They tell you what the codebase IS today — the canonicalization mission moves it toward what it SHOULD be:',
    '',
    '- **One canonical name** per concept (see `CANONICAL_VOCABULARY.md`)',
    '- **One canonical implementation** per capability (see `CAPABILITY_MAP.md` — pick one of each duplicated row)',
    '- **One canonical event** per occurrence (see `EVENT_TAXONOMY.md` variants section)',
    '- **One canonical service** per responsibility (see `SERVICE_CATALOG.md`)',
    '',
    'Migrations use `mcp__atomic-edit__atomic_rename_symbol_cross_file` for safe renames; deprecated aliases get tracked in `DEPRECATION_MAP.md`.',
    '',
    '## Anti-regression',
    '',
    'See `scripts/ops/check-canonical-*.mjs` (added by Phase J) for gates that:',
    '- Forbid new events without an entry in `EVENT_TAXONOMY.md`',
    '- Forbid new services duplicating a canonical capability',
    '- Forbid new entries to `CANONICAL_VOCABULARY.md` aliases column without a deprecation plan',
  ];
  writeMd('ARCHITECTURE_INDEX.md', lines.join('\n') + '\n');
}

console.log('\nDone. Output in docs/architecture/');

}
