import * as path from 'path';

const SCANNABLE_EXTENSIONS = new Set([
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
  '.css',
  '.scss',
  '.less',
  '.json',
  '.yml',
  '.yaml',
  '.md',
  '.mdx',
  '.html',
  '.svg',
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.ico',
  '.webp',
  '.sql',
  '.prisma',
  '.graphql',
  '.gql',
  '.env',
  '.env.example',
]);

const IMPORT_REGEX =
  /(?:(?:import\s+(?:[\s\S]*?)\s+from\s+)|(?:import\s+))['"]([^'"]+)['"]|require\(['"]([^'"]+)['"]\)|(?:export\s+(?:[\s\S]*?)\s+from\s+)['"]([^'"]+)['"]/g;

const EXPORT_REGEX =
  /\bexport\s+(?:default\s+|const\s+|function\s+|class\s+|let\s+|var\s+|async\s+function\s+|type\s+|interface\s+|enum\s+|abstract\s+class\s+|\*)/g;

const RESOLVE_EXTENSIONS = [
  '.ts',
  '.tsx',
  '.js',
  '.jsx',
  '.mjs',
  '.cjs',
  '/index.ts',
  '/index.tsx',
  '/index.js',
];

function classifyFileExtension(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase();
  return ext || '<none>';
}

function hasTestPathSignal(filePath: string): boolean {
  const basename = path.basename(filePath).toLowerCase();
  if (basename.includes('.spec.') || basename.includes('.test.')) return true;
  const pathSegments = filePath.split(path.sep);
  return pathSegments.some((segment) => segment === '__tests__' || segment === 'tests');
}

function extractImports(filePath: string, content: string): string[] {
  const imports: string[] = [];
  let match: RegExpExecArray | null;
  const regex = new RegExp(IMPORT_REGEX.source, 'g');

  while ((match = regex.exec(content)) !== null) {
    const importPath = match[1] || match[2] || match[3];
    if (!importPath || importPath.startsWith('@types/')) continue;
    imports.push(importPath);
  }

  return imports;
}

function hasTestRuntimeEvidence(content: string): boolean {
  const imports = extractImports('', content);
  if (imports.some((importPath) => importPath.includes('test'))) return true;
  return (
    content.includes('describe(') ||
    content.includes('it(') ||
    content.includes('test(') ||
    content.includes('expect(')
  );
}

function hasGeneratedPathSignal(filePath: string): boolean {
  const basename = path.basename(filePath).toLowerCase();
  if (basename.includes('.generated.')) return true;
  return filePath.split(path.sep).some((segment) => segment.toLowerCase() === 'generated');
}

function hasGeneratedContentEvidence(content: string): boolean {
  const lowered = content.slice(0, 2_000).toLowerCase();
  return (
    lowered.includes('@generated') ||
    lowered.includes('generated by') ||
    lowered.includes('do not edit')
  );
}

export {
  SCANNABLE_EXTENSIONS,
  IMPORT_REGEX,
  EXPORT_REGEX,
  RESOLVE_EXTENSIONS,
  classifyFileExtension,
  hasTestPathSignal,
  hasTestRuntimeEvidence,
  hasGeneratedPathSignal,
  hasGeneratedContentEvidence,
  extractImports,
};
