import type { FrontendCapability } from './types';

export const FALE_CAPABILITIES: FrontendCapability[] = [
  {
    icon: '\u{1F4F2}',
    title: 'WhatsApp Marketing',
    desc: 'Envie campanhas em massa pelo WhatsApp com mensagens personalizadas.',
    badge: 'WhatsApp',
    category: 'fale',
    roles: ['produtor', 'afiliado'],
    status: 'active',
    route: '/marketing/whatsapp',
  },
  {
    icon: '\u{1F916}',
    title: 'Kloel IA',
    desc: 'Assistente de IA que atende seus leads 24/7 com inteligencia conversacional.',
    badge: 'IA',
    category: 'fale',
    roles: ['produtor'],
    status: 'active',
    route: '/',
  },
  {
    icon: '\u{1F4E8}',
    title: 'Email Marketing',
    desc: 'Crie e envie campanhas de email com templates profissionais.',
    category: 'fale',
    roles: ['produtor'],
    status: 'active',
    route: '/marketing/email',
  },
  {
    icon: '\u{1F4DE}',
    title: 'Central de Suporte',
    desc: 'Sistema de tickets e atendimento ao cliente integrado.',
    category: 'fale',
    roles: ['produtor'],
    status: 'active',
    route: '/inbox',
  },
  {
    icon: '\u{1F4E2}',
    title: 'Broadcast',
    desc: 'Envie mensagens em massa para listas segmentadas de contatos.',
    category: 'fale',
    roles: ['produtor'],
    status: 'active',
    route: '/marketing/whatsapp?mode=broadcast',
  },
  {
    icon: '\u{1F4DD}',
    title: 'Templates de Mensagem',
    desc: 'Biblioteca de templates aprovados para WhatsApp e email.',
    category: 'fale',
    roles: ['produtor', 'afiliado'],
    status: 'active',
    route: '/marketing/email?mode=templates',
  },
  {
    icon: '\u{1F4CB}',
    title: 'Pesquisa de Satisfacao',
    desc: 'Colete feedback automatico apos cada interacao ou compra.',
    category: 'fale',
    roles: ['produtor'],
    status: 'active',
    route: '/analytics?tab=satisfacao',
  },
  {
    icon: '\u{1F5D3}\u{FE0F}',
    title: 'Agendamento de Envio',
    desc: 'Programe mensagens e campanhas para envio futuro automatico.',
    category: 'fale',
    roles: ['produtor'],
    status: 'active',
    route: '/campaigns',
  },
  {
    icon: '\u{1F310}',
    title: 'Multicanal',
    desc: 'Gerencie conversas de WhatsApp, email e Instagram em um so lugar.',
    badge: 'Omnichannel',
    category: 'fale',
    roles: ['produtor'],
    status: 'active',
    route: '/inbox',
  },
  {
    icon: '\u{1F4EC}',
    title: 'Inbox',
    desc: 'Central unica para atendimento, conversas, backlog e tomada de acao.',
    category: 'fale',
    roles: ['produtor'],
    status: 'active',
    route: '/inbox',
  },
  {
    icon: '\u{1F50A}',
    title: 'CIA',
    desc: 'Superficie de inteligencia operacional e assistencia de execucao.',
    category: 'fale',
    roles: ['produtor'],
    status: 'active',
    route: '/cia',
  },
];
