import type { FrontendCapability } from './types';

export const GERENCIE_CAPABILITIES: FrontendCapability[] = [
  {
    icon: '\u{25B6}\u{FE0F}',
    title: 'Kloel Player',
    desc: 'Player de video seguro com protecao contra download e pirataria.',
    badge: 'Seguro',
    category: 'gerencie',
    roles: ['produtor'],
    status: 'active',
    route: '/produtos/area-membros',
  },
  {
    icon: '\u{1F465}',
    title: 'Central de Colaboradores',
    desc: 'Gerencie permissoes, funcoes e acessos da equipe.',
    category: 'gerencie',
    roles: ['produtor'],
    status: 'active',
    route: '/parcerias/colaboradores',
  },
  {
    icon: '\u{1F4D6}',
    title: 'Protecao de Ebooks',
    desc: 'Entrega protegida para ebooks e materiais digitais com area de membros, player e camada de protecao do site.',
    category: 'gerencie',
    roles: ['produtor'],
    status: 'active',
    badge: 'Seguro',
    route: '/sites/protecao',
  },
  {
    icon: '\u{1F4B3}',
    title: 'Cobrancas Kloel',
    desc: 'Gerencie cobrancas, checkout e operacao financeira diretamente pelo Kloel.',
    category: 'gerencie',
    roles: ['produtor'],
    status: 'active',
    route: '/settings?section=billing',
  },
  {
    icon: '\u{1F517}',
    title: 'Widget de Pagamento',
    desc: 'Incorpore o checkout do Kloel em sites externos com embed pronto para copiar.',
    category: 'gerencie',
    roles: ['produtor', 'afiliado'],
    status: 'active',
    route: '/products?feature=payment-widget',
  },
  {
    icon: '\u{1F4E7}',
    title: 'Envio de Relatorios',
    desc: 'Envio automatico de relatorios por email para sua equipe.',
    category: 'gerencie',
    roles: ['produtor'],
    status: 'active',
    route: '/analytics?tab=envio',
  },
  {
    icon: '\u{1F50D}',
    title: 'Pixel de Rastreamento',
    desc: 'Pixels do Facebook, Google e TikTok para rastrear conversoes.',
    badge: 'Ads',
    category: 'gerencie',
    roles: ['produtor', 'afiliado'],
    status: 'active',
    route: '/anuncios/rastreamento',
  },
  {
    icon: '\u{1F4CA}',
    title: 'Relatorios Exportados',
    desc: 'Exporte relatorios em CSV e PDF para analise externa.',
    category: 'gerencie',
    roles: ['produtor'],
    status: 'active',
    route: '/analytics?tab=exportacoes',
  },
  {
    icon: '\u{1F91D}',
    title: 'Coproducoes',
    desc: 'Parcerias de coproducao com divisao automatica de receita.',
    category: 'gerencie',
    roles: ['produtor'],
    status: 'active',
    route: '/products?feature=coproduction',
  },
  {
    icon: '\u{1F4C8}',
    title: 'Estrategias de Vendas',
    desc: 'Templates de estrategias comprovadas para maximizar vendas.',
    badge: 'Novo',
    category: 'gerencie',
    roles: ['produtor', 'afiliado'],
    status: 'active',
    route: '/vendas?tab=estrategias',
  },
  {
    icon: '\u{1F680}',
    title: 'Launchpad',
    desc: 'Gerencie lancamentos com grupos de WhatsApp automatizados.',
    badge: 'Launch',
    category: 'gerencie',
    roles: ['produtor'],
    status: 'active',
    route: '/ferramentas/launchpad',
  },
  {
    icon: '\u{1F4B8}',
    title: 'Cobrancas Avulsas',
    desc: 'Crie cobrancas diretas no fluxo interno do Kloel quando precisar vender fora do produto.',
    category: 'gerencie',
    roles: ['produtor'],
    status: 'active',
    route: '/payments',
  },
  {
    icon: '\u{1F3A5}',
    title: 'Video',
    desc: 'Geracao, perfis de voz e superfícies de video orientadas por IA.',
    category: 'gerencie',
    roles: ['produtor'],
    status: 'active',
    route: '/video',
  },
  {
    icon: '\u{1F578}\u{FE0F}',
    title: 'Scrapers',
    desc: 'Ferramentas de captura e enriquecimento para operacoes comerciais.',
    category: 'gerencie',
    roles: ['produtor'],
    status: 'active',
    route: '/scrapers',
  },
];
