import type { FrontendCapability } from './types';

export const IMPULSIONE_CAPABILITIES: FrontendCapability[] = [
  {
    icon: '\u{1F91D}',
    title: 'Programa de Afiliados',
    desc: 'Crie seu programa de afiliados e tenha parceiros vendendo seus produtos com comissoes automaticas.',
    badge: 'Popular',
    category: 'impulsione',
    roles: ['produtor'],
    status: 'active',
    route: '/parcerias/afiliados',
  },
  {
    icon: '\u{1F4C4}',
    title: 'Paginas Dinamicas',
    desc: 'Paginas de vendas personalizadas que se adaptam ao perfil do visitante.',
    category: 'impulsione',
    roles: ['produtor'],
    status: 'active',
    route: '/sites/criar?mode=dynamic',
  },
  {
    icon: '\u{1F503}',
    title: 'Paginas Alternativas',
    desc: 'Teste diferentes versoes da sua pagina de vendas com testes A/B.',
    badge: 'A/B Test',
    category: 'impulsione',
    roles: ['produtor'],
    status: 'active',
    route: '/sites/editar?mode=ab',
  },
  {
    icon: '\u{2B50}',
    title: 'Recomenda',
    desc: 'Sistema de recomendacao inteligente que sugere produtos complementares.',
    category: 'impulsione',
    roles: ['produtor'],
    status: 'active',
    route: '/products?feature=recommendation',
  },
  {
    icon: '\u{1F4E6}',
    title: 'Order Bump',
    desc: 'Ofertas complementares no checkout para aumentar o ticket medio.',
    badge: 'Receita +',
    category: 'impulsione',
    roles: ['produtor'],
    status: 'active',
    route: '/products?feature=order-bump',
  },
  {
    icon: '\u{1F4E3}',
    title: 'Material de Divulgacao',
    desc: 'Banners, criativos e materiais prontos para afiliados divulgarem.',
    category: 'impulsione',
    roles: ['produtor', 'afiliado'],
    status: 'active',
    route: '/parcerias/afiliados',
  },
  {
    icon: '\u{1F3A8}',
    title: 'Criador de Paginas',
    desc: 'Editor visual para landing pages, paginas de captura e paginas de vendas.',
    category: 'impulsione',
    roles: ['produtor'],
    status: 'active',
    route: '/sites/criar',
  },
  {
    icon: '\u{1F6D2}',
    title: 'Aparencia do Pagamento',
    desc: 'Personalize a aparencia do checkout com sua marca e cores.',
    category: 'impulsione',
    roles: ['produtor'],
    status: 'active',
    route: '/products?feature=checkout-appearance',
  },
  {
    icon: '\u{1F3AF}',
    title: 'Funil de Vendas',
    desc: 'Monte funis completos com upsell, downsell e cross-sell.',
    badge: 'Estrategia',
    category: 'impulsione',
    roles: ['produtor'],
    status: 'active',
    route: '/funnels',
  },
  {
    icon: '\u{1F3A5}',
    title: 'Webinario',
    desc: 'Webinarios ao vivo ou automaticos para vender seus produtos.',
    category: 'impulsione',
    roles: ['produtor'],
    status: 'active',
    route: '/webinarios',
  },
  {
    icon: '\u{1F451}',
    title: 'Kloel Club',
    desc: 'Area de membros exclusiva para conteudo premium.',
    badge: 'Premium',
    category: 'impulsione',
    roles: ['produtor'],
    status: 'active',
    route: '/produtos/area-membros',
  },
  {
    icon: '\u{1F6E1}\u{FE0F}',
    title: 'Estrategia de Retencao',
    desc: 'Ferramentas para reduzir cancelamentos e manter clientes.',
    category: 'impulsione',
    roles: ['produtor'],
    status: 'active',
    route: '/followups?source=marketing',
  },
];
