import type { FrontendCapability } from './types';

export const RECUPERE_CAPABILITIES: FrontendCapability[] = [
  {
    icon: '\u{1F4E9}',
    title: 'Recuperacao de Carrinho',
    desc: 'Recupere vendas perdidas com mensagens automaticas para quem abandonou o checkout.',
    badge: 'Recupere',
    category: 'recupere',
    roles: ['produtor'],
    status: 'active',
    route: '/followups?source=marketing',
  },
  {
    icon: '\u{1F4AC}',
    title: 'Chatbot de Vendas',
    desc: 'Bot de conversacao para qualificar leads e recuperar vendas via chat.',
    badge: 'IA',
    category: 'recupere',
    roles: ['produtor'],
    status: 'active',
    route: '/inbox',
  },
  {
    icon: '\u{1F4E7}',
    title: 'Email de Recuperacao',
    desc: 'Sequencia automatica de emails para leads que nao compraram.',
    category: 'recupere',
    roles: ['produtor'],
    status: 'active',
    route: '/campaigns',
  },
  {
    icon: '\u{1F504}',
    title: 'Retargeting Inteligente',
    desc: 'Crie audiencias de retargeting automaticas para suas campanhas de ads.',
    category: 'recupere',
    roles: ['produtor', 'afiliado'],
    status: 'active',
    route: '/anuncios/rastreamento?focus=retargeting',
  },
  {
    icon: '\u{23F0}',
    title: 'Urgencia e Escassez',
    desc: 'Adicione contadores regressivos e alertas de estoque limitado.',
    category: 'recupere',
    roles: ['produtor'],
    status: 'active',
    route: '/products?feature=urgency',
  },
  {
    icon: '\u{1F3AB}',
    title: 'Cupom de Recuperacao',
    desc: 'Gere cupons automaticos para incentivo de compra apos abandono.',
    category: 'recupere',
    roles: ['produtor'],
    status: 'active',
    route: '/products?feature=coupon',
  },
  {
    icon: '\u{1F4CA}',
    title: 'Analytics de Abandono',
    desc: 'Analise detalhada de onde e por que seus leads desistem da compra.',
    category: 'recupere',
    roles: ['produtor'],
    status: 'active',
    route: '/analytics?tab=abandonos',
  },
  {
    icon: '\u{1F300}',
    title: 'Automacao de Retorno',
    desc: 'Fluxos automaticos para trazer de volta leads inativos.',
    category: 'recupere',
    roles: ['produtor'],
    status: 'active',
    route: '/flow',
  },
  {
    icon: '\u{1F465}',
    title: 'Leads',
    desc: 'Gestao dedicada dos contatos e segmentos comerciais.',
    category: 'recupere',
    roles: ['produtor'],
    status: 'active',
    route: '/leads',
  },
  {
    icon: '\u{1F501}',
    title: 'Follow-ups',
    desc: 'Cadencias e retomadas manuais para nao perder leads mornos.',
    category: 'recupere',
    roles: ['produtor'],
    status: 'active',
    route: '/followups',
  },
];
