import { resolve, join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = resolve(join(__dirname, '..', '..', '..'));

export const VAULT_ROOT = resolve(
  process.env.KLOEL_VAULT_ROOT || '/Users/danielpenin/Documents/Obsidian Vault',
);
export const MIRROR_ROOT = resolve(
  process.env.KLOEL_MIRROR_ROOT || join(VAULT_ROOT, 'Kloel', '99 - Espelho do Codigo'),
);
export const SOURCE_MIRROR_DIR = join(MIRROR_ROOT, '_source');

export const PHASE_TAG_PREFIX = 'kloel/phase-';

export const MODULE_PHASE_MAP = {
  Auth: 0,
  Workspaces: 0,
  Settings: 0,
  KYC: 0,
  Products: 1,
  Checkout: 1,
  Wallet: 1,
  Billing: 1,
  WhatsApp: 2,
  Inbox: 2,
  Autopilot: 2,
  Flows: 2,
  CIA: 3,
  CRM: 3,
  Dashboard: 3,
  Analytics: 3,
  Reports: 3,
  Vendas: 4,
  Affiliate: 4,
  'Member Area': 4,
  Campaigns: 4,
  FollowUps: 4,
  Marketing: 5,
  Anúncios: 5,
  Sites: 5,
  Canvas: 5,
  Funnels: 5,
  Webinários: 5,
  Leads: 5,
  Team: 6,
  'API Keys': 6,
  Webhooks: 6,
  'Audit Log': 6,
  Notifications: 6,
  Marketplace: 6,
  Video: 6,
  Voice: 6,
};

export const BACKEND_DIR_MAP = {
  auth: 'Auth',
  workspaces: 'Workspaces',
  kyc: 'KYC',
  checkout: 'Checkout',
  wallet: 'Wallet',
  billing: 'Billing',
  whatsapp: 'WhatsApp',
  inbox: 'Inbox',
  autopilot: 'Autopilot',
  flows: 'Flows',
  cia: 'CIA',
  'ai-brain': 'CIA',
  crm: 'CRM',
  dashboard: 'Dashboard',
  analytics: 'Analytics',
  reports: 'Reports',
  pipeline: 'Vendas',
  affiliate: 'Affiliate',
  partnerships: 'Affiliate',
  'member-area': 'Member Area',
  campaigns: 'Campaigns',
  followup: 'FollowUps',
  marketing: 'Marketing',
  scrapers: 'Leads',
  team: 'Team',
  'api-keys': 'API Keys',
  webhooks: 'Webhooks',
  audit: 'Audit Log',
  notifications: 'Notifications',
  marketplace: 'Marketplace',
  video: 'Video',
  voice: 'Voice',
};

export const FRONTEND_PATH_SEGMENTS = {
  auth: 'Auth',
  workspace: 'Workspaces',
  settings: 'Settings',
  kyc: 'KYC',
  products: 'Products',
  checkout: 'Checkout',
  wallet: 'Wallet',
  billing: 'Billing',
  whatsapp: 'WhatsApp',
  inbox: 'Inbox',
  autopilot: 'Autopilot',
  flows: 'Flows',
  cia: 'CIA',
  crm: 'CRM',
  dashboard: 'Dashboard',
  analytics: 'Analytics',
  reports: 'Reports',
  vendas: 'Vendas',
  pipeline: 'Vendas',
  affiliate: 'Affiliate',
  partnerships: 'Affiliate',
  'member-area': 'Member Area',
  campaigns: 'Campaigns',
  followup: 'FollowUps',
  marketing: 'Marketing',
  'member-area': 'Member Area',
  members: 'Member Area',
  sites: 'Sites',
  canvas: 'Canvas',
  funnels: 'Funnels',
  webinários: 'Webinários',
  leads: 'Leads',
  scrapers: 'Leads',
  team: 'Team',
  'api-keys': 'API Keys',
  webhooks: 'Webhooks',
  audit: 'Audit Log',
  notifications: 'Notifications',
  marketplace: 'Marketplace',
  video: 'Video',
  voice: 'Voice',
};

export const SKIP_PREFIXES = [
  'scripts/',
  'ops/',
  'docs/',
  '.github/',
  '.husky/',
  'prisma/',
  'nginx/',
  'e2e/',
  '.claude/',
  '.agents/',
  '.pulse/',
  '.omx/',
  '.gitnexus/',
  '.kilo/',
  '.beads/',
  '.serena/',
  '.turbo/',
  'node_modules/',
  'dist/',
  'build/',
  'coverage/',
  '.next/',
  'artifacts/',
  'tmp/',
];

export const SKIP_ROOT_FILES = new Set([
  'package.json',
  'pnpm-lock.yaml',
  'pnpm-workspace.yaml',
  'turbo.json',
  '.editorconfig',
  '.prettierrc.json',
  '.gitignore',
  '.nvmrc',
  '.node-version',
  '.npmrc',
  '.codacy.yml',
  'CLAUDE.md',
  'AGENTS.md',
  'CODEX.md',
  '.sentryclirc',
]);

export const SKIP_EXTS = new Set([
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.svg',
  '.webp',
  '.ico',
  '.woff',
  '.woff2',
  '.ttf',
  '.eot',
  '.pdf',
  '.zip',
  '.tar',
  '.gz',
  '.mp3',
  '.mp4',
  '.webm',
  '.mov',
  '.sqlite',
  '.sqlite3',
  '.db',
  '.wasm',
  '.bin',
  '.lock',
  '.log',
  '.map',
  '.tsbuildinfo',
]);
