import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY sub-partition — Tier 0B (query / comms).
 *
 * Read-only queries scoped to the communications surface: WhatsApp status,
 * chats and contacts, social channels, web search, audio transcription, and
 * agent memory / sessions. Extracted from `./tier-0b-query` (Gate-fix2-D,
 * 2026-05-28).
 */
export const TIER_0B_QUERY_COMMS_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'search_agent_memory',
    title: 'Buscar na memória',
    description: 'Busca na memória do agente por conversas e decisões',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'MemoryService.search',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_agent_sessions',
    title: 'Buscar sessões',
    description: 'Busca sessões de conversa anteriores',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'SessionService.search',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_whatsapp_status',
    title: 'Status WhatsApp',
    description: 'Verifica status da conexão WhatsApp',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WhatsAppService.status',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'transcribe_audio',
    title: 'Transcrever áudio',
    description: 'Transcreve áudio para texto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'audioUrl', type: 'string', label: 'URL do áudio', required: true }],
    domainService: 'AudioService.transcribe',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_whatsapp_chats',
    title: 'Conversas WhatsApp',
    description: 'Lista conversas do WhatsApp',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [],
    domainService: 'WhatsAppService.listChats',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_whatsapp_contacts',
    title: 'Contatos WhatsApp',
    description: 'Lista contatos do WhatsApp',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [],
    domainService: 'WhatsAppService.listContacts',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_social_channels',
    title: 'Canais sociais',
    description: 'Lista canais sociais conectados',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ChannelService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_web',
    title: 'Buscar na web',
    description: 'Busca informações na internet',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'SearchService.web',
    emits: [],
    surface: ['dashboard-chat'],
  },
];
