import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 7 (affiliates).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_7_AFFILIATES_CAPABILITIES: CapabilityDefinition[] = [
  // ── Canonical (dotted) IDs first, legacy (deprecated) at end ──
  {
    id: 'affiliates.configure',
    title: 'Configurar afiliados',
    description: 'Ativa/desativa e configura o programa de afiliados do produto',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar programa?', required: true },
      { key: 'commissionPercent', type: 'number', label: 'Comissão (%)', required: false },
    ],
    domainService: 'AffiliateService.configure',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },

  // ── Wave7 L4 — fine-grained affiliate program controls ──
  {
    id: 'affiliates.toggle_program',
    title: 'Ativar/desativar programa de afiliados',
    description: 'Liga ou desliga o programa de afiliados de um produto',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'AffiliateService.toggleProgram',
    emits: ['affiliate.program_updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'affiliates.set_visibility',
    title: 'Visibilidade na vitrine de afiliados',
    description: 'Define se o produto aparece na vitrine pública de afiliados',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: false,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'visible', type: 'boolean', label: 'Visível?', required: true },
    ],
    domainService: 'AffiliateService.setVisibility',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affiliates.set_auto_approval',
    title: 'Aprovação automática de afiliados',
    description: 'Liga ou desliga a aprovação automática de novos afiliados',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: false,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'autoApprove', type: 'boolean', label: 'Aprovar automaticamente?', required: true },
    ],
    domainService: 'AffiliateService.setAutoApproval',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affiliates.set_data_access',
    title: 'Acesso do afiliado aos dados do comprador',
    description: 'Define se o afiliado pode acessar os dados dos compradores',
    category: 'MUTATION_SENSITIVE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'accessData', type: 'boolean', label: 'Permitir acesso aos dados?', required: true },
    ],
    domainService: 'AffiliateService.setDataAccess',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affiliates.set_abandonment_access',
    title: 'Acesso do afiliado a carrinhos abandonados',
    description: 'Define se o afiliado pode acessar carrinhos abandonados',
    category: 'MUTATION_SENSITIVE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'accessAbandoned',
        type: 'boolean',
        label: 'Permitir acesso a abandonos?',
        required: true,
      },
    ],
    domainService: 'AffiliateService.setAbandonmentAccess',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affiliates.set_first_installment_commission',
    title: 'Comissão sobre a primeira parcela',
    description: 'Define se a comissão do afiliado incide sobre a primeira parcela',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'firstInstallment',
        type: 'boolean',
        label: 'Comissão na 1ª parcela?',
        required: true,
      },
    ],
    domainService: 'AffiliateService.setFirstInstallmentCommission',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affiliates.set_attribution_model',
    title: 'Modelo de atribuição de comissão',
    description: 'Define o modelo de atribuição: primeiro clique, último clique ou proporcional',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'model',
        type: 'select',
        label: 'Modelo de atribuição',
        required: true,
        enum: ['primeiro clique', 'último clique', 'proporcional'],
      },
    ],
    domainService: 'AffiliateService.setAttributionModel',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affiliates.set_cookie_days',
    title: 'Janela de cookie de atribuição',
    description: 'Define por quantos dias o cookie de atribuição do afiliado vale',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: false,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'cookieDays', type: 'number', label: 'Dias de cookie', required: true },
    ],
    domainService: 'AffiliateService.setCookieDays',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affiliates.set_commission_pct',
    title: 'Percentual de comissão dos afiliados',
    description: 'Define o percentual de comissão pago aos afiliados',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'commissionPercent', type: 'number', label: 'Comissão (%)', required: true },
    ],
    domainService: 'AffiliateService.setCommissionPct',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affiliates.list',
    title: 'Listar afiliados',
    description: 'Lista os afiliados do workspace, opcionalmente filtrados por produto',
    category: 'QUERY',
    tier: 7,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: false }],
    domainService: 'AffiliateService.listForChat',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affiliates.list_merchants',
    title: 'Listar produtores que promovo',
    description: 'Lista os produtores cujos produtos este workspace promove como afiliado',
    category: 'QUERY',
    tier: 7,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AffiliateService.listMerchants',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affiliates.update_terms',
    title: 'Atualizar regulamento de afiliados',
    description: 'Atualiza os termos/regulamento do programa de afiliados do produto',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'terms', type: 'string', label: 'Regulamento', required: true },
    ],
    domainService: 'AffiliateService.updateTerms',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affiliates.manage_coproduction',
    title: 'Gerenciar coprodução',
    description: 'Adiciona ou remove um coprodutor (divisão de comissão) do produto',
    category: 'MUTATION_SENSITIVE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'action',
        type: 'select',
        label: 'Ação',
        required: false,
        enum: ['add', 'remove'],
      },
      { key: 'agentEmail', type: 'string', label: 'Email do coprodutor', required: true },
      { key: 'agentName', type: 'string', label: 'Nome do coprodutor', required: false },
      { key: 'percentage', type: 'number', label: 'Percentual (%)', required: false },
    ],
    domainService: 'AffiliateService.manageCoproduction',
    emits: ['affiliate.coproduction_updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },

  // ── Wave7 L4 — affiliate marketplace (consumer side) ──
  {
    id: 'marketplace.list_public_products',
    title: 'Produtos públicos do marketplace',
    description: 'Lista produtos disponíveis no marketplace de afiliados',
    category: 'QUERY',
    tier: 7,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'category', type: 'string', label: 'Categoria', required: false },
      { key: 'search', type: 'string', label: 'Busca', required: false },
      { key: 'limit', type: 'number', label: 'Limite', required: false },
    ],
    domainService: 'MarketplaceService.listPublicProducts',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'marketplace.apply_as_affiliate',
    title: 'Candidatar-se como afiliado',
    description: 'Solicita afiliação a um produto do marketplace de afiliados',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'affiliateName', type: 'string', label: 'Nome', required: false },
      { key: 'affiliateEmail', type: 'string', label: 'Email', required: false },
    ],
    domainService: 'MarketplaceService.applyAsAffiliate',
    emits: ['affiliate.request_created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'marketplace.get_affiliate_link',
    title: 'Obter link de afiliado',
    description: 'Retorna o link de afiliado deste workspace para um produto do marketplace',
    category: 'QUERY',
    tier: 7,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'MarketplaceService.getAffiliateLink',
    emits: [],
    surface: ['dashboard-chat'],
  },
  // ── Legacy IDs (deprecated) — superseded by canonical dotted equivalents ──
  {
    id: 'get_affiliate_config',
    title: 'Configuração de afiliados (legado)',
    description: 'DEPRECATED — use affiliates.configure',
    category: 'QUERY',
    tier: 7,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AffiliateService.getConfig',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['affiliates.configure'],
  },
  {
    id: 'update_affiliate_config',
    title: 'Atualizar afiliados (legado)',
    description: 'DEPRECATED — use affiliates.configure',
    category: 'MUTATION_SAFE',
    tier: 7,
    requiresConfirmation: true,
    requiredPermissions: ['affiliate:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'commissionPercent', type: 'number', label: 'Comissão %', required: false },
    ],
    domainService: 'AffiliateService.configure',
    emits: ['affiliate.program_updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['affiliates.configure'],
  },
  {
    id: 'list_affiliates',
    title: 'Listar afiliados (legado)',
    description: 'DEPRECATED — use affiliates.list',
    category: 'QUERY',
    tier: 7,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AffiliateService.list',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['affiliates.list'],
  },
];
