import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 4 (coupons).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_4_COUPONS_CAPABILITIES: CapabilityDefinition[] = [
  // ── Canonical (dotted) IDs ──
  {
    id: 'coupons.list',
    title: 'Listar cupons',
    description: 'Lista cupons de desconto de um produto',
    category: 'QUERY',
    tier: 4,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: false }],
    domainService: 'CouponService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'coupons.update',
    title: 'Atualizar cupom',
    description: 'Atualiza dados de um cupom existente (código, tipo, valor, limite de usos)',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'couponId', type: 'string', label: 'ID do cupom', required: true },
      { key: 'code', type: 'string', label: 'Código', required: false },
      {
        key: 'discountType',
        type: 'select',
        label: 'Tipo de desconto',
        required: false,
        enum: ['percentage', 'fixed'],
      },
      { key: 'discountValue', type: 'number', label: 'Valor do desconto', required: false },
      { key: 'usageLimit', type: 'number', label: 'Limite de usos', required: false },
      { key: 'active', type: 'boolean', label: 'Ativo', required: false },
    ],
    domainService: 'CouponService.update',
    emits: ['coupon.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/cupons/${couponId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'coupons.create',
    title: 'Criar cupom',
    description: 'Cria cupom de desconto para um produto',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'code', type: 'string', label: 'Código', required: true, prompt: 'Código do cupom?' },
      {
        key: 'discountType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['percentage', 'fixed'],
      },
      { key: 'discountValue', type: 'number', label: 'Valor', required: true },
      { key: 'usageLimit', type: 'number', label: 'Limite de usos', required: false },
    ],
    domainService: 'CouponService.create',
    emits: ['coupon.created'],
    evidenceUrlBuilder: '/produtos/${productId}/cupons/${couponId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'coupons.delete',
    title: 'Excluir cupom',
    description: 'Remove um cupom de desconto',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'couponId', type: 'string', label: 'ID do cupom', required: true }],
    domainService: 'CouponService.delete',
    emits: ['coupon.deleted'],
    surface: ['dashboard-chat'],
  },
  // ── Legacy IDs (deprecated) — superseded by canonical dotted equivalents ──
  {
    id: 'list_coupons',
    title: 'Listar cupons (legado)',
    description: 'DEPRECATED — use coupons.list',
    category: 'QUERY',
    tier: 4,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CouponService.list',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['coupons.list'],
  },
  {
    id: 'create_coupon',
    title: 'Criar cupom (legado)',
    description: 'DEPRECATED — use coupons.create',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'code', type: 'string', label: 'Código', required: true },
      {
        key: 'discountType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['percentage', 'fixed'],
      },
      { key: 'discountValue', type: 'number', label: 'Valor', required: true },
    ],
    domainService: 'CouponService.create',
    emits: ['coupon.created'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['coupons.create'],
  },
  {
    id: 'update_coupon',
    title: 'Atualizar cupom (legado)',
    description: 'DEPRECATED — use coupons.update',
    category: 'MUTATION_SAFE',
    tier: 4,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'couponId', type: 'string', label: 'Cupom', required: true }],
    domainService: 'CouponService.update',
    emits: ['coupon.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['coupons.update'],
  },
];
