import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 10 (reports).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_10_REPORTS_CAPABILITIES: CapabilityDefinition[] = [
  // ── Canonical (dotted) IDs first, legacy (deprecated) at end ──
  {
    id: 'reports.operations',
    title: 'Operações',
    description: 'Mostra relatório de operações: vendas, receita, ticket médio',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'period',
        type: 'select',
        label: 'Período',
        required: false,
        enum: ['today', 'week', 'month', 'year'],
      },
    ],
    domainService: 'ReportService.getOperations',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'reports.abandonments',
    title: 'Carrinhos abandonados',
    description: 'Mostra carrinhos abandonados no período',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'period',
        type: 'select',
        label: 'Período',
        required: false,
        enum: ['today', 'week', 'month', 'year'],
      },
    ],
    domainService: 'ReportService.getAbandonments',
    emits: [],
    surface: ['dashboard-chat'],
  },
  // ── Legacy IDs (deprecated) — superseded by canonical dotted equivalents or no direct replacement ──
  {
    id: 'create_broadcast',
    title: 'Criar campanha (legado)',
    description: 'DEPRECATED — use campaigns.create_broadcast',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: true,
    requiredPermissions: ['campaign:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'message', type: 'string', label: 'Mensagem', required: true },
    ],
    domainService: 'CampaignService.createBroadcast',
    emits: ['campaign.created'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['campaigns.create_broadcast'],
  },
  {
    id: 'connect_channel',
    title: 'Conectar canal (legado)',
    description: 'DEPRECATED — use channels.connect',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      {
        key: 'channel',
        type: 'select',
        label: 'Canal',
        required: true,
        enum: ['whatsapp', 'instagram', 'facebook', 'tiktok', 'email'],
      },
    ],
    domainService: 'ChannelService.connect',
    emits: ['channel.connected'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['channels.connect'],
  },
  {
    id: 'connect_whatsapp',
    title: 'Conectar WhatsApp (legado)',
    description: 'DEPRECATED — use whatsapp.connect',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [],
    domainService: 'WhatsAppService.connect',
    emits: ['whatsapp.connected'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['whatsapp.connect'],
  },
  {
    id: 'create_campaign',
    title: 'Criar campanha (legado)',
    description: 'DEPRECATED — use campaigns.create',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: true,
    requiredPermissions: ['campaign:write'],
    inputSchema: [{ key: 'name', type: 'string', label: 'Nome', required: true }],
    domainService: 'CampaignService.create',
    emits: ['campaign.created'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['campaigns.create'],
  },
  {
    id: 'create_flow',
    title: 'Criar fluxo (legado)',
    description: 'DEPRECATED — use flows.create',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['flow:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'trigger', type: 'string', label: 'Gatilho', required: true },
    ],
    domainService: 'FlowService.create',
    emits: ['flow.created'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['flows.create'],
  },
  {
    id: 'list_flows',
    title: 'Listar fluxos (legado)',
    description: 'DEPRECATED — use flows.list',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'FlowService.list',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['flows.list'],
  },
  {
    id: 'send_whatsapp_message',
    title: 'Enviar WhatsApp (legado)',
    description: 'DEPRECATED — use whatsapp.send_message',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [
      { key: 'phone', type: 'string', label: 'Telefone', required: true },
      { key: 'message', type: 'string', label: 'Mensagem', required: true },
    ],
    domainService: 'MessagingService.sendWhatsApp',
    emits: ['whatsapp.message_sent'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['whatsapp.send_message'],
  },
  {
    id: 'send_channel_message',
    title: 'Enviar por canal (legado)',
    description: 'DEPRECATED — use channels.send_message',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['channel:write'],
    inputSchema: [
      { key: 'channel', type: 'string', label: 'Canal', required: true },
      { key: 'message', type: 'string', label: 'Mensagem', required: true },
    ],
    domainService: 'ChannelService.send',
    emits: ['channel.message_sent'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['channels.send_message'],
  },
  {
    id: 'send_audio',
    title: 'Enviar áudio (legado)',
    description: 'DEPRECATED — use whatsapp.send_audio',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [{ key: 'phone', type: 'string', label: 'Telefone', required: true }],
    domainService: 'MessagingService.sendAudio',
    emits: ['whatsapp.audio_sent'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['whatsapp.send_audio'],
  },
  {
    id: 'send_document',
    title: 'Enviar documento (legado)',
    description: 'DEPRECATED — use whatsapp.send_document',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [{ key: 'phone', type: 'string', label: 'Telefone', required: true }],
    domainService: 'MessagingService.sendDocument',
    emits: ['whatsapp.document_sent'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['whatsapp.send_document'],
  },
  {
    id: 'send_voice_note',
    title: 'Enviar nota de voz (legado)',
    description: 'DEPRECATED — use whatsapp.send_voice_note',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [{ key: 'phone', type: 'string', label: 'Telefone', required: true }],
    domainService: 'MessagingService.sendVoiceNote',
    emits: ['whatsapp.voice_sent'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['whatsapp.send_voice_note'],
  },
  {
    id: 'get_whatsapp_messages',
    title: 'Mensagens WhatsApp (legado)',
    description: 'DEPRECATED — use whatsapp.get_messages',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [{ key: 'chatId', type: 'string', label: 'Conversa', required: true }],
    domainService: 'WhatsAppService.getMessages',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['whatsapp.get_messages'],
  },
  {
    id: 'get_whatsapp_backlog',
    title: 'Backlog WhatsApp (legado)',
    description: 'DEPRECATED — use whatsapp.get_backlog',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [],
    domainService: 'WhatsAppService.getBacklog',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['whatsapp.get_backlog'],
  },
  {
    id: 'set_whatsapp_presence',
    title: 'Presença WhatsApp (legado)',
    description: 'DEPRECATED — use whatsapp.set_presence',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [
      {
        key: 'presence',
        type: 'select',
        label: 'Status',
        required: true,
        enum: ['available', 'unavailable'],
      },
    ],
    domainService: 'WhatsAppService.setPresence',
    emits: ['whatsapp.presence_updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['whatsapp.set_presence'],
  },
  {
    id: 'sync_whatsapp_history',
    title: 'Sincronizar WhatsApp (legado)',
    description: 'DEPRECATED — use whatsapp.sync_history',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [],
    domainService: 'WhatsAppService.syncHistory',
    emits: ['whatsapp.history_synced'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['whatsapp.sync_history'],
  },
  {
    id: 'create_agent_job',
    title: 'Criar job agente (legado)',
    description: 'DEPRECATED — use agent.create_job',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: true,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'schedule', type: 'string', label: 'Agendamento', required: false },
      { key: 'action', type: 'string', label: 'Ação', required: true },
    ],
    domainService: 'AgentJobService.create',
    emits: ['agent.job_created'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['agent.create_job'],
  },
  {
    id: 'list_agent_jobs',
    title: 'Listar jobs agente (legado)',
    description: 'DEPRECATED — use agent.list_jobs',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AgentJobService.list',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['agent.list_jobs'],
  },
  {
    id: 'set_agent_job_enabled',
    title: 'Ativar/desativar job (legado)',
    description: 'DEPRECATED — use agent.toggle_job',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'jobId', type: 'string', label: 'Job', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'AgentJobService.setEnabled',
    emits: ['agent.job_updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['agent.toggle_job'],
  },
  {
    id: 'money_machine',
    title: 'Máquina de Dinheiro (legado)',
    description: 'DEPRECATED — use autopilot.money_machine',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: true,
    requiredPermissions: ['campaign:write'],
    inputSchema: [
      { key: 'topN', type: 'number', label: 'Tamanho do lote', required: false },
      { key: 'autoSend', type: 'boolean', label: 'Enviar automaticamente?', required: false },
      { key: 'smartTime', type: 'boolean', label: 'Usar smart time?', required: false },
    ],
    domainService: 'AutopilotService.runMoneyMachine',
    emits: ['autopilot.money_machine_run'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['autopilot.money_machine'],
  },
];
