import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY sub-partition — Tier 0 (read-only queries).
 *
 * QUERY capabilities: read-only data fetches that don't mutate workspace state.
 *
 * Aggregated by '../partitions/tier-0-self-awareness' alongside tier-0a/0c
 * before being re-exported through '../capability-registry-v2.const'.
 */
export const TIER_0B_QUERY_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'list_products',
    title: 'Listar produtos',
    description: 'Lista todos os produtos do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ProductService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_checkouts',
    title: 'Listar checkouts',
    description: 'Lista checkouts do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CheckoutService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_agent_memory',
    title: 'Buscar na memória',
    description: 'Busca na memória do agente por conversas e decisões',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'MemoryService.search',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_agent_sessions',
    title: 'Buscar sessões',
    description: 'Busca sessões de conversa anteriores',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'SessionService.search',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_details',
    title: 'Detalhes do produto',
    description: 'Mostra detalhes completos de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'ProductService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_refunds',
    title: 'Estornos',
    description: 'Lista estornos e reembolsos',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'RefundService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_nps',
    title: 'NPS',
    description: 'Mostra Net Promoter Score',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'NpsService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_whatsapp_status',
    title: 'Status WhatsApp',
    description: 'Verifica status da conexão WhatsApp',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WhatsAppService.status',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_analytics',
    title: 'Analytics',
    description: 'Obtém métricas e analytics do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'metric', type: 'string', label: 'Métrica', required: false },
      { key: 'period', type: 'string', label: 'Período', required: false },
    ],
    domainService: 'AnalyticsService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_order_details',
    title: 'Detalhes do pedido',
    description: 'Mostra detalhes de um pedido',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'orderId', type: 'string', label: 'Pedido', required: true }],
    domainService: 'OrderService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_ai_config',
    title: 'Configuração IA do produto',
    description: 'Mostra configuração de IA de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'ProductAIConfigService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_billing_status',
    title: 'Status faturamento',
    description: 'Mostra status de faturamento e plano',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'BillingService.status',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'transcribe_audio',
    title: 'Transcrever áudio',
    description: 'Transcreve áudio para texto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'audioUrl', type: 'string', label: 'URL do áudio', required: true }],
    domainService: 'AudioService.transcribe',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_whatsapp_chats',
    title: 'Conversas WhatsApp',
    description: 'Lista conversas do WhatsApp',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [],
    domainService: 'WhatsAppService.listChats',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_whatsapp_contacts',
    title: 'Contatos WhatsApp',
    description: 'Lista contatos do WhatsApp',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [],
    domainService: 'WhatsAppService.listContacts',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_churn',
    title: 'Churn',
    description: 'Mostra taxa de cancelamento',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ChurnService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_social_channels',
    title: 'Canais sociais',
    description: 'Lista canais sociais conectados',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ChannelService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_web',
    title: 'Buscar na web',
    description: 'Busca informações na internet',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'SearchService.web',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_settings',
    title: 'Configurações',
    description: 'Mostra configurações do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WorkspaceService.getSettings',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_dashboard_summary',
    title: 'Resumo do dashboard',
    description: 'Mostra resumo do dashboard: vendas, leads, oportunidades',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'DashboardService.summary',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_orders',
    title: 'Listar vendas/pedidos',
    description: 'Lista vendas e pedidos do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'status',
        type: 'select',
        label: 'Status',
        required: false,
        enum: ['pending', 'paid', 'cancelled'],
      },
    ],
    domainService: 'OrderService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_sales_summary',
    title: 'Resumo de vendas',
    description: 'Mostra resumo de vendas: total, receita, ticket médio',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'SalesService.summary',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_leads',
    title: 'Listar leads',
    description: 'Lista leads do CRM com filtros',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CrmService.listLeads',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_wallet_balance',
    title: 'Saldo da carteira',
    description: 'Mostra saldo disponível, pendente e total',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getBalance',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_wallet_statement',
    title: 'Extrato da carteira',
    description: 'Mostra extrato de transações',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getStatement',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_abandonments',
    title: 'Carrinhos abandonados',
    description: 'Lista carrinhos abandonados recentes',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AbandonmentService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_plans',
    title: 'Planos do produto',
    description: 'Lista todos os planos de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'PlanService.listForProduct',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_reviews',
    title: 'Avaliações',
    description: 'Lista avaliações de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'ReviewService.listForProduct',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_urls',
    title: 'URLs do produto',
    description: 'Lista URLs cadastradas de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'ProductUrlService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'validate_coupon',
    title: 'Validar cupom',
    description: 'Verifica se um cupom é válido para um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'code', type: 'string', label: 'Código', required: true },
      { key: 'productId', type: 'string', label: 'Produto', required: true },
    ],
    domainService: 'CouponService.validate',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_subscriptions',
    title: 'Listar assinaturas',
    description: 'Lista assinaturas ativas do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'SubscriptionService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
];
