import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 1 (products).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_1_PRODUCTS_CAPABILITIES: CapabilityDefinition[] = [
  // ── Canonical (dotted) IDs — legacy (deprecated) at end ──
  {
    id: 'products.create',
    title: 'Criar produto',
    description: 'Cria um novo produto no catálogo do workspace',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      {
        key: 'name',
        type: 'string',
        label: 'Nome',
        required: true,
        prompt: 'Qual o nome do produto?',
      },
      { key: 'description', type: 'string', label: 'Descrição', required: false },
      { key: 'category', type: 'string', label: 'Categoria', required: false },
      {
        key: 'format',
        type: 'select',
        label: 'Formato',
        required: false,
        enum: ['físico', 'digital', 'híbrido'],
      },
      {
        key: 'price',
        type: 'number',
        label: 'Preço (R$)',
        required: true,
        prompt: 'Qual o preço?',
      },
    ],
    domainService: 'ProductService.create',
    emits: ['product.created'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.upload_image',
    title: 'Upload imagem do produto',
    description: 'Anexa uma imagem enviada no chat ao produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'imageFile', type: 'file', label: 'Arquivo de imagem', required: true },
    ],
    domainService: 'MediaService.attach + ProductService.setImage',
    emits: ['product.updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.update',
    title: 'Editar produto',
    description: 'Edita dados gerais de um produto existente',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: false },
      { key: 'description', type: 'string', label: 'Descrição', required: false },
      { key: 'active', type: 'boolean', label: 'Disponível para venda', required: false },
      { key: 'salesPageUrl', type: 'string', label: 'URL da página de vendas', required: false },
    ],
    domainService: 'ProductService.update',
    emits: ['product.updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  // ── Wave7 L1 — fine-grained product capabilities (Y-1/Y-2) ──
  // Each routes to a real ProductService method (resolver path: (ws, args)),
  // never Prisma-direct, reusing existing update/toggleAvailability/publish.
  {
    id: 'products.set_pixels',
    title: 'Configurar pixels do produto',
    description: 'Define os pixels de rastreamento (FB/Google/TikTok) de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      {
        key: 'pixels',
        type: 'string',
        label: 'Pixels (lista de configs)',
        required: true,
        description: 'Array de pixels { type, pixelId, accessToken? }',
      },
    ],
    domainService: 'ProductService.setPixels',
    emits: ['product.updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.set_shipping',
    title: 'Configurar frete do produto',
    description: 'Define tipo, valor e origem de frete e garantia de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      {
        key: 'shippingType',
        type: 'select',
        label: 'Tipo de frete',
        required: false,
        enum: ['FREE', 'FIXED', 'VARIABLE', 'NONE'],
      },
      { key: 'shippingValue', type: 'number', label: 'Valor do frete (R$)', required: false },
      { key: 'originCep', type: 'string', label: 'CEP de origem', required: false },
      { key: 'warrantyDays', type: 'number', label: 'Dias de garantia', required: false },
    ],
    domainService: 'ProductService.setShipping',
    emits: ['product.updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.set_fulfillment',
    title: 'Configurar logística do produto',
    description: 'Define o provedor de logística/entrega (fulfillment) de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'provider', type: 'string', label: 'Provedor de logística', required: false },
    ],
    domainService: 'ProductService.setFulfillment',
    emits: ['product.updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.set_sales_page',
    title: 'Definir página de vendas',
    description: 'Define a URL da página de vendas de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'salesPageUrl', type: 'string', label: 'URL da página de vendas', required: true },
    ],
    domainService: 'ProductService.setSalesPage',
    emits: ['product.updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.update_urls',
    title: 'Atualizar URLs do produto',
    description: 'Atualiza URLs de obrigado, boleto, pix, Reclame Aqui e e-mail de suporte',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'thankyouUrl', type: 'string', label: 'URL de obrigado', required: false },
      { key: 'thankyouBoletoUrl', type: 'string', label: 'URL obrigado (boleto)', required: false },
      { key: 'thankyouPixUrl', type: 'string', label: 'URL obrigado (pix)', required: false },
      { key: 'reclameAquiUrl', type: 'string', label: 'URL Reclame Aqui', required: false },
      { key: 'supportEmail', type: 'string', label: 'E-mail de suporte', required: false },
    ],
    domainService: 'ProductService.updateUrls',
    emits: ['product.updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.toggle_availability',
    title: 'Ativar/desativar produto',
    description: 'Liga ou desliga a disponibilidade de venda de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'available', type: 'boolean', label: 'Disponível para venda', required: true },
    ],
    domainService: 'ProductService.toggleAvailabilityFor',
    emits: ['product.activated', 'product.deactivated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.review_and_publish',
    title: 'Revisar e publicar produto',
    description: 'Aprova e publica um produto, tornando-o ativo para venda',
    category: 'MUTATION_SENSITIVE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'ProductService.reviewAndPublish',
    emits: ['product.published'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  // ── Wave8 — new canonical capabilities: reviews, AI config, campaign linking ──
  {
    id: 'products.review_create',
    title: 'Criar avaliação do produto',
    description: 'Registra uma avaliação de comprador para o produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'rating', type: 'number', label: 'Nota (1-5)', required: true },
      { key: 'comment', type: 'string', label: 'Comentário', required: false },
      { key: 'reviewerName', type: 'string', label: 'Nome do avaliador', required: false },
    ],
    domainService: 'ReviewService.create',
    emits: ['product.review_created'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.review_list',
    title: 'Listar avaliações do produto',
    description: 'Lista avaliações de um produto com estatísticas de notas',
    category: 'QUERY',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'limit', type: 'number', label: 'Limite', required: false },
    ],
    domainService: 'ReviewService.listForProduct',
    emits: [],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.set_ai_config',
    title: 'Configurar IA do produto',
    description:
      'Define a configuração de IA para o produto: persona, instruções, conhecimento base',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'persona', type: 'string', label: 'Persona da IA', required: false },
      { key: 'instructions', type: 'string', label: 'Instruções base', required: false },
      { key: 'knowledgeBase', type: 'string', label: 'Base de conhecimento', required: false },
      { key: 'enabled', type: 'boolean', label: 'Ativar IA no produto', required: false },
    ],
    domainService: 'ProductAIConfigService.update',
    emits: ['product.ai_config_updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.link_campaign',
    title: 'Vincular campanha ao produto',
    description: 'Vincula uma campanha de marketing a um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'campaignId', type: 'string', label: 'ID da campanha', required: true },
    ],
    domainService: 'CampaignsService.linkToProduct',
    emits: ['campaign.product_linked'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  // ── Legacy IDs (deprecated) — superseded by canonical dotted equivalents ──
  {
    id: 'configure_pixel',
    title: 'Configurar pixel (legado)',
    description: 'DEPRECATED — use products.set_pixels',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'pixelType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['facebook', 'google'],
      },
      { key: 'pixelId', type: 'string', label: 'ID do pixel', required: true },
    ],
    domainService: 'PixelService.configure',
    emits: ['product.pixel_configured'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['products.set_pixels'],
  },
  {
    id: 'upload_product_image',
    title: 'Upload foto do produto (legado)',
    description: 'DEPRECATED — use products.upload_image',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'MediaService.attach + ProductService.setImage',
    emits: ['product.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['products.upload_image'],
  },
  {
    id: 'create_product',
    title: 'Criar produto (legado)',
    description: 'DEPRECATED — use products.create',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'price', type: 'number', label: 'Preço (R$)', required: true },
    ],
    domainService: 'ProductService.create',
    emits: ['product.created'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['products.create'],
  },
  {
    id: 'save_product',
    title: 'Salvar produto (legado)',
    description: 'DEPRECATED — use products.create',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'price', type: 'number', label: 'Preço (R$)', required: true },
    ],
    domainService: 'ProductService.create',
    emits: ['product.created'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['products.create'],
  },
  {
    id: 'update_product',
    title: 'Atualizar produto (legado)',
    description: 'DEPRECATED — use products.update',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: false },
    ],
    domainService: 'ProductService.update',
    emits: ['product.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['products.update'],
  },
  {
    id: 'delete_product',
    title: 'Excluir produto (legado)',
    description: 'DEPRECATED — no canonical dotted equivalent yet; kept for backward compat',
    category: 'MUTATION_SENSITIVE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'ProductService.delete',
    emits: ['product.deleted'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
  },
  {
    id: 'configure_shipping',
    title: 'Configurar frete (legado)',
    description: 'DEPRECATED — use products.set_shipping',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'shippingType',
        type: 'select',
        label: 'Tipo',
        required: false,
        enum: ['free', 'fixed', 'variable'],
      },
    ],
    domainService: 'ShippingService.configure',
    emits: ['product.shipping_updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['products.set_shipping'],
  },
  {
    id: 'configure_warranty',
    title: 'Configurar garantia (legado)',
    description: 'DEPRECATED — use products.set_shipping (warrantyDays field)',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'warrantyDays', type: 'number', label: 'Dias de garantia', required: true },
    ],
    domainService: 'ProductService.update',
    emits: ['product.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['products.set_shipping'],
  },
  {
    id: 'configure_exit_intent',
    title: 'Popup de saída (legado)',
    description: 'DEPRECATED — use checkouts.set_exit_intent',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['checkouts.set_exit_intent'],
  },
];
