import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 5 (sales).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_5_SALES_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'create_order',
    title: 'Criar pedido',
    description: 'Cria pedido/venda manual',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
    ],
    domainService: 'CheckoutService.createOrder',
    emits: ['sale.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'generate_pix',
    title: 'Gerar PIX (alias legado)',
    description: 'Alias legado. Encaminha para sales.create_pix; não executa serviço próprio.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true },
    ],
    domainService: 'Alias for sales.create_pix',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['sales.create_pix'],
  },
  {
    id: 'generate_boleto',
    title: 'Gerar boleto (alias legado)',
    description: 'Alias legado. Encaminha para sales.create_boleto; não executa serviço próprio.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true },
    ],
    domainService: 'Alias for sales.create_boleto',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['sales.create_boleto'],
  },
  {
    id: 'create_payment_link',
    title: 'Link de pagamento',
    description: 'Gera link de pagamento para um lead',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'amount', type: 'number', label: 'Valor', required: true },
    ],
    domainService: 'PaymentService.createPayment',
    emits: ['payment.link_created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'sales.create_pix',
    title: 'Gerar PIX',
    description: 'Cria venda real com PIX. Retorna copia-e-cola + QR Code.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'planId', type: 'string', label: 'Plano', required: true },
      {
        key: 'customerName',
        type: 'string',
        label: 'Nome do comprador',
        required: true,
        prompt: 'Nome do comprador?',
      },
      { key: 'customerEmail', type: 'string', label: 'Email', required: true },
      { key: 'customerCpf', type: 'string', label: 'CPF', required: true },
      { key: 'customerPhone', type: 'string', label: 'Telefone', required: false },
    ],
    domainService: 'SalesService.createPixOrder',
    emits: ['sale.created', 'payment.pending'],
    evidenceUrlBuilder: '/vendas/${orderId}',
    executionRail: {
      provider: 'mercadopago',
      paymentMethod: 'PIX',
      providerMethod: 'pix',
      providerService: 'MercadoPagoPixChargeService.create',
      webhookPath: '/webhooks/mercadopago',
      proofFields: ['saleId', 'externalPaymentId', 'pixCopiaECola', 'pixQrCode'],
    },
    surface: ['dashboard-chat'],
  },
  {
    id: 'sales.create_boleto',
    title: 'Gerar boleto',
    description: 'Cria venda real com boleto Mercado Pago e retorna URL/codigo de pagamento.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'planId', type: 'string', label: 'Plano', required: true },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true },
      { key: 'customerPhone', type: 'string', label: 'Telefone', required: true },
      { key: 'customerEmail', type: 'string', label: 'Email', required: true },
      { key: 'customerCpf', type: 'string', label: 'CPF', required: true },
      { key: 'customerZipCode', type: 'string', label: 'CEP', required: true },
      { key: 'customerStreet', type: 'string', label: 'Rua', required: true },
      { key: 'customerNumber', type: 'string', label: 'Numero', required: true },
      { key: 'customerNeighborhood', type: 'string', label: 'Bairro', required: false },
      { key: 'customerCity', type: 'string', label: 'Cidade', required: true },
      { key: 'customerState', type: 'string', label: 'UF', required: true },
    ],
    domainService: 'SalesService.createBoletoOrder',
    emits: ['sale.created', 'payment.pending'],
    evidenceUrlBuilder: '/vendas/${orderId}',
    executionRail: {
      provider: 'mercadopago',
      paymentMethod: 'BOLETO',
      providerMethod: 'boleto',
      providerService: 'MercadoPagoBoletoChargeService.create',
      webhookPath: '/webhooks/mercadopago',
      proofFields: ['saleId', 'externalPaymentId', 'boletoBarcode', 'boletoUrl'],
    },
    surface: ['dashboard-chat'],
  },
  {
    id: 'sales.create_card_link',
    title: 'Gerar link de cartão',
    description: 'Cria venda real com link seguro de cartão via Stripe. Não usa PIX ou boleto.',
    category: 'MUTATION_SENSITIVE',
    tier: 5,
    requiresConfirmation: true,
    requiredPermissions: ['sale:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'planId', type: 'string', label: 'Plano', required: true },
      { key: 'customerName', type: 'string', label: 'Nome do comprador', required: true },
      { key: 'customerEmail', type: 'string', label: 'Email', required: true },
      { key: 'customerCpf', type: 'string', label: 'CPF', required: false },
      { key: 'customerPhone', type: 'string', label: 'Telefone', required: false },
    ],
    domainService: 'SalesService.createStripeCardLink',
    emits: ['sale.created', 'payment.pending'],
    evidenceUrlBuilder: '/vendas/${orderId}',
    executionRail: {
      provider: 'stripe',
      paymentMethod: 'CREDIT_CARD',
      providerMethod: 'card',
      providerService: 'StripeCheckout.sessions.create',
      webhookPath: '/webhook/payment/stripe',
      proofFields: ['saleId', 'externalPaymentId', 'checkoutSessionId', 'checkoutUrl'],
    },
    surface: ['dashboard-chat'],
  },
];
