import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY sub-partition — Tier 0 (mutations & configuration).
 *
 * Groups MUTATION_SAFE, MUTATION_SENSITIVE, and CONFIGURATION capabilities that
 * touch workspace state (autopilot, billing, brand voice, business hours,
 * documents, coupons, memory writes, etc.).
 *
 * Aggregated by '../partitions/tier-0-self-awareness' alongside tier-0a/0b
 * before being re-exported through '../capability-registry-v2.const'.
 */
export const TIER_0C_MUTATIONS_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'artifacts.create_renderable',
    title: 'Criar Markdown PDF HTML SVG Mermaid DOCX PPTX XLSX artifact renderizavel',
    description:
      'Cria e renderiza entregaveis reais no chat: Markdown, HTML, SVG, Mermaid, PDF, DOCX, PPTX, XLSX, dados e codigo com card de download e painel editavel quando houver conteudo textual.',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'kind',
        type: 'select',
        label: 'Formato markdown pdf html svg mermaid docx pptx xlsx react dashboard',
        required: false,
        enum: [
          'markdown',
          'html',
          'svg',
          'mermaid',
          'react',
          'pdf',
          'docx',
          'pptx',
          'xlsx',
          'data',
          'code',
        ],
      },
      {
        key: 'title',
        type: 'string',
        label: 'Titulo do artifact arquivo documento',
        required: false,
      },
      {
        key: 'content',
        type: 'string',
        label: 'Conteudo artifact arquivo documento dashboard codigo',
        required: false,
      },
    ],
    domainService: 'Alias for Kloel stream artifact pipeline',
    emits: ['artifact.created'],
    surface: ['dashboard-chat'],
    maturity: 'testable',
  },
  {
    id: 'toggle_autopilot',
    title: 'Ativar/desativar autopilot (legado)',
    description: 'DEPRECATED — use workspace.toggle_autopilot',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'enabled', type: 'boolean', label: 'Ativar?', required: true }],
    domainService: 'AutopilotService.toggle',
    emits: ['autopilot.toggled'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['workspace.toggle_autopilot'],
  },
  {
    id: 'change_plan',
    title: 'Mudar plano (legado)',
    description: 'DEPRECATED — use billing.change_plan',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['billing:write'],
    inputSchema: [{ key: 'plan', type: 'string', label: 'Novo plano', required: true }],
    domainService: 'BillingService.changePlan',
    emits: ['billing.plan_changed'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['billing.change_plan'],
  },
  {
    id: 'remember_user_info',
    title: 'Lembrar informação (legado)',
    description: 'DEPRECATED — use memory.set',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'key', type: 'string', label: 'Chave', required: true },
      { key: 'value', type: 'string', label: 'Valor', required: true },
    ],
    domainService: 'MemoryService.set',
    emits: ['memory.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['memory.set'],
  },
  {
    id: 'save_business_info',
    title: 'Salvar info do negócio (legado)',
    description: 'DEPRECATED — use workspace.update_info',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'businessName', type: 'string', label: 'Nome', required: false }],
    domainService: 'WorkspaceService.updateInfo',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['workspace.update_info'],
  },
  {
    id: 'set_brand_voice',
    title: 'Definir voz da marca (legado)',
    description: 'DEPRECATED — use workspace.set_brand_voice',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'tone', type: 'string', label: 'Tom', required: true }],
    domainService: 'BrandService.setVoice',
    emits: ['brand.voice_updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['workspace.set_brand_voice'],
  },
  {
    id: 'update_workspace_settings',
    title: 'Atualizar configurações (legado)',
    description: 'DEPRECATED — use workspace.update_settings',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'businessName', type: 'string', label: 'Nome', required: false }],
    domainService: 'WorkspaceService.updateSettings',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['workspace.update_settings'],
  },
  {
    id: 'set_business_hours',
    title: 'Horário comercial (legado)',
    description: 'DEPRECATED — use workspace.set_business_hours',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'start', type: 'string', label: 'Início', required: true },
      { key: 'end', type: 'string', label: 'Fim', required: true },
    ],
    domainService: 'WorkspaceService.setHours',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['workspace.set_business_hours'],
  },
  {
    id: 'set_sales_policy',
    title: 'Política de vendas (legado)',
    description: 'DEPRECATED — use workspace.set_sales_policy',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'policy', type: 'string', label: 'Política', required: true }],
    domainService: 'WorkspaceService.setPolicy',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['workspace.set_sales_policy'],
  },
  {
    id: 'update_billing_info',
    title: 'Atualizar faturamento (legado)',
    description: 'DEPRECATED — use billing.update',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['billing:write'],
    inputSchema: [],
    domainService: 'BillingService.update',
    emits: ['billing.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['billing.update'],
  },
  {
    id: 'configure_ai_persona',
    title: 'Configurar persona IA (legado)',
    description: 'DEPRECATED — use workspace.configure_ai_persona',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      {
        key: 'personality',
        type: 'select',
        label: 'Personalidade',
        required: false,
        enum: ['formal', 'informal', 'friendly', 'professional'],
      },
      { key: 'tone', type: 'string', label: 'Tom de voz', required: false },
    ],
    domainService: 'AIConfigService.update',
    emits: ['ai.persona_updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['workspace.configure_ai_persona'],
  },
  {
    id: 'delete_coupon',
    title: 'Excluir cupom (legado)',
    description: 'DEPRECATED — use coupons.delete',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'couponId', type: 'string', label: 'ID do cupom', required: true }],
    domainService: 'CouponService.delete',
    emits: ['coupon.deleted'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['coupons.delete'],
  },
  {
    id: 'upload_document',
    title: 'Enviar documento (legado)',
    description: 'DEPRECATED — use account.upload_document',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      {
        key: 'documentType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['identity', 'contract', 'cnpj_card'],
      },
    ],
    domainService: 'DocumentService.upload',
    emits: ['account.document_uploaded'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['account.upload_document'],
  },
];
