import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY sub-partition — Tier 0B (query / sales-ops).
 *
 * Read-only queries scoped to the sales-operations surface: orders, sales
 * summaries, leads, abandonments, dashboard, NPS, churn, subscriptions.
 * Extracted from `./tier-0b-query` (Gate-fix2-D, 2026-05-28).
 */
export const TIER_0B_QUERY_SALES_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'get_nps',
    title: 'NPS',
    description: 'Mostra Net Promoter Score',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'NpsService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_order_details',
    title: 'Detalhes do pedido',
    description: 'Mostra detalhes de um pedido',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'orderId', type: 'string', label: 'Pedido', required: true }],
    domainService: 'OrderService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_churn',
    title: 'Churn',
    description: 'Mostra taxa de cancelamento',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ChurnService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_dashboard_summary',
    title: 'Resumo do dashboard',
    description: 'Mostra resumo do dashboard: vendas, leads, oportunidades',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'DashboardService.summary',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_orders',
    title: 'Listar vendas/pedidos',
    description: 'Lista vendas e pedidos do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'status',
        type: 'select',
        label: 'Status',
        required: false,
        enum: ['pending', 'paid', 'cancelled'],
      },
    ],
    domainService: 'OrderService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_sales_summary',
    title: 'Resumo de vendas',
    description: 'Mostra resumo de vendas: total, receita, ticket médio',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'SalesService.summary',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_leads',
    title: 'Listar leads',
    description: 'Lista leads do CRM com filtros',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CrmService.listLeads',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_abandonments',
    title: 'Carrinhos abandonados',
    description: 'Lista carrinhos abandonados recentes',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AbandonmentService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_subscriptions',
    title: 'Listar assinaturas',
    description: 'Lista assinaturas ativas do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'SubscriptionService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
];
