import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY sub-partition — Tier 0B (query / comms).
 *
 * Read-only queries scoped to the communications surface: WhatsApp status,
 * chats and contacts, social channels, web search, audio transcription, and
 * agent memory / sessions. Extracted from `./tier-0b-query` (Gate-fix2-D,
 * 2026-05-28).
 */
export const TIER_0B_QUERY_COMMS_CAPABILITIES: CapabilityDefinition[] = [
  // ── Legacy IDs (deprecated) — superseded by canonical dotted equivalents ──
  {
    id: 'search_agent_memory',
    title: 'Buscar na memória (legado)',
    description: 'DEPRECATED — use memory.search',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'MemoryService.search',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['memory.search'],
  },
  {
    id: 'search_agent_sessions',
    title: 'Buscar sessões (legado)',
    description: 'DEPRECATED — use sessions.search',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'SessionService.search',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['sessions.search'],
  },
  {
    id: 'get_whatsapp_status',
    title: 'Status WhatsApp (legado)',
    description: 'DEPRECATED — use whatsapp.status',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WhatsAppService.status',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['whatsapp.status'],
  },
  {
    id: 'transcribe_audio',
    title: 'Transcrever áudio (legado)',
    description: 'DEPRECATED — use audio.transcribe',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'audioUrl', type: 'string', label: 'URL do áudio', required: true }],
    domainService: 'AudioService.transcribe',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['audio.transcribe'],
  },
  {
    id: 'list_whatsapp_chats',
    title: 'Conversas WhatsApp (legado)',
    description: 'DEPRECATED — use whatsapp.list_chats',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [],
    domainService: 'WhatsAppService.listChats',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['whatsapp.list_chats'],
  },
  {
    id: 'list_whatsapp_contacts',
    title: 'Contatos WhatsApp (legado)',
    description: 'DEPRECATED — use whatsapp.list_contacts',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [],
    domainService: 'WhatsAppService.listContacts',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['whatsapp.list_contacts'],
  },
  {
    id: 'get_social_channels',
    title: 'Canais sociais (legado)',
    description: 'DEPRECATED — use channels.list',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ChannelService.list',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['channels.list'],
  },
  {
    id: 'search_web',
    title: 'Buscar na web (legado)',
    description: 'DEPRECATED — use search.web',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'SearchService.web',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['search.web'],
  },
];
