import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY sub-partition — Tier 0B (query / commerce).
 *
 * Read-only queries scoped to the commerce surface: products, plans, URLs,
 * reviews, coupons, checkouts, refunds. Extracted from `./tier-0b-query`
 * (Gate-fix2-D, 2026-05-28) so each domain's capability list stays reviewable
 * in isolation.
 */
export const TIER_0B_QUERY_COMMERCE_CAPABILITIES: CapabilityDefinition[] = [
  // ── Legacy IDs (deprecated) — superseded by canonical dotted equivalents ──
  {
    id: 'list_products',
    title: 'Listar produtos (legado)',
    description: 'DEPRECATED — use products.list (or ProductService.list directly)',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ProductService.list',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['products.list'],
  },
  {
    id: 'list_checkouts',
    title: 'Listar checkouts (legado)',
    description: 'DEPRECATED — use checkouts.list',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CheckoutService.list',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['checkouts.list'],
  },
  {
    id: 'get_product_details',
    title: 'Detalhes do produto (legado)',
    description: 'DEPRECATED — use products.get',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'ProductService.get',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['products.get'],
  },
  {
    id: 'list_refunds',
    title: 'Estornos (legado)',
    description: 'DEPRECATED — use sales.list_refunds',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'RefundService.list',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['sales.list_refunds'],
  },
  {
    id: 'get_product_ai_config',
    title: 'Configuração IA do produto (legado)',
    description: 'DEPRECATED — use products.set_ai_config (or read from ProductAIConfigService.get)',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'ProductAIConfigService.get',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['products.set_ai_config'],
  },
  {
    id: 'get_product_plans',
    title: 'Planos do produto (legado)',
    description: 'DEPRECATED — use plans.list',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'PlanService.listForProduct',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['plans.list'],
  },
  {
    id: 'get_product_reviews',
    title: 'Avaliações (legado)',
    description: 'DEPRECATED — use products.review_list',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'ReviewService.listForProduct',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['products.review_list'],
  },
  {
    id: 'get_product_urls',
    title: 'URLs do produto (legado)',
    description: 'DEPRECATED — use products.update_urls',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'ProductUrlService.list',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['products.update_urls'],
  },
  {
    id: 'validate_coupon',
    title: 'Validar cupom (legado)',
    description: 'DEPRECATED — use coupons.validate',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'code', type: 'string', label: 'Código', required: true },
      { key: 'productId', type: 'string', label: 'Produto', required: true },
    ],
    domainService: 'CouponService.validate',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['coupons.validate'],
  },
];
