import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 3 (checkouts).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_3_CHECKOUTS_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'configure_social_proof',
    title: 'Prova social',
    description: 'Configura prova social do checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_after_pay',
    title: 'Configurar After Pay',
    description: 'Configura pagamento posterior (boleto parcelado, faturado)',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_checkout',
    title: 'Criar checkout',
    description: 'Cria novo checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: true },
    ],
    domainService: 'CheckoutService.create',
    emits: ['checkout.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_checkout',
    title: 'Atualizar checkout',
    description: 'Atualiza dados de um checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'checkoutId', type: 'string', label: 'Checkout', required: true }],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'delete_checkout',
    title: 'Excluir checkout',
    description: 'Remove um checkout permanentemente',
    category: 'MUTATION_SENSITIVE',
    tier: 3,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'checkoutId', type: 'string', label: 'Checkout', required: true }],
    domainService: 'CheckoutService.delete',
    emits: ['checkout.deleted'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.create',
    title: 'Criar checkout',
    description: 'Cria checkout vinculado a planos de um produto com personalização',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'name',
        type: 'string',
        label: 'Nome do checkout',
        required: true,
        prompt: 'Nome do checkout?',
      },
      { key: 'acceptPix', type: 'boolean', label: 'Aceitar PIX', required: false },
      { key: 'acceptCard', type: 'boolean', label: 'Aceitar cartão', required: false },
      { key: 'acceptBoleto', type: 'boolean', label: 'Aceitar boleto', required: false },
      { key: 'buttonText', type: 'string', label: 'Texto do botão', required: false },
    ],
    domainService: 'CheckoutService.create',
    emits: ['checkout.created'],
    evidenceUrlBuilder: '/produtos/${productId}/checkouts/${checkoutId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.update',
    title: 'Editar checkout',
    description: 'Edita checkout existente',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'buttonText', type: 'string', label: 'Texto do botão', required: false },
      { key: 'active', type: 'boolean', label: 'Ativo', required: false },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/checkouts/${checkoutId}',
    surface: ['dashboard-chat'],
  },
];
