import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 6 (urls).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_6_URLS_CAPABILITIES: CapabilityDefinition[] = [
  // ── Canonical (dotted) IDs first, legacy (deprecated) at end ──
  {
    id: 'urls.add',
    title: 'Adicionar URL',
    description: 'Adiciona URL (página de venda, landing page) a um produto',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'url', type: 'string', label: 'URL', required: true },
      { key: 'description', type: 'string', label: 'Descrição', required: true },
    ],
    domainService: 'ProductUrlService.add',
    emits: ['product.url_added'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'urls.update',
    title: 'Editar URL',
    description: 'Edita uma URL existente de um produto',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'urlId', type: 'string', label: 'ID da URL', required: true },
      { key: 'url', type: 'string', label: 'URL', required: false },
      { key: 'description', type: 'string', label: 'Descrição', required: false },
      { key: 'active', type: 'boolean', label: 'Ativa', required: false },
    ],
    domainService: 'ProductUrlService.update',
    emits: ['product.url_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'urls.delete',
    title: 'Remover URL',
    description: 'Remove uma URL de um produto',
    category: 'MUTATION_SENSITIVE',
    tier: 6,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'urlId', type: 'string', label: 'ID da URL', required: true }],
    domainService: 'ProductUrlService.delete',
    emits: ['product.url_deleted'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'urls.toggle_private',
    title: 'Alternar URL privada',
    description: 'Ativa ou desativa o modo privado de uma URL de produto',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'urlId', type: 'string', label: 'ID da URL', required: true },
      { key: 'enabled', type: 'boolean', label: 'Privada?', required: true },
    ],
    domainService: 'ProductUrlService.togglePrivate',
    emits: ['product.url_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'urls.toggle_kloel_learning',
    title: 'Alternar aprendizado do Kloel',
    description: 'Ativa ou desativa o aprendizado do Kloel a partir de uma URL de produto',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'urlId', type: 'string', label: 'ID da URL', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar aprendizado?', required: true },
    ],
    domainService: 'ProductUrlService.toggleKloelLearning',
    emits: ['product.url_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'urls.toggle_kloel_chat_embed',
    title: 'Alternar widget de chat do Kloel',
    description: 'Ativa ou desativa o widget de chat do Kloel embutido em uma URL de produto',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'urlId', type: 'string', label: 'ID da URL', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar chat?', required: true },
    ],
    domainService: 'ProductUrlService.toggleKloelChatEmbed',
    emits: ['product.url_updated'],
    surface: ['dashboard-chat'],
  },
  // ── Legacy IDs (deprecated) — superseded by canonical dotted equivalents ──
  {
    id: 'add_url',
    title: 'Adicionar URL (legado)',
    description: 'DEPRECATED — use urls.add',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'url', type: 'string', label: 'URL', required: true },
    ],
    domainService: 'ProductUrlService.add',
    emits: ['product.url_added'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['urls.add'],
  },
  {
    id: 'update_url',
    title: 'Editar URL (legado)',
    description: 'DEPRECATED — use urls.update',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'urlId', type: 'string', label: 'ID da URL', required: true }],
    domainService: 'ProductUrlService.update',
    emits: ['product.url_updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['urls.update'],
  },
  {
    id: 'delete_url',
    title: 'Remover URL (legado)',
    description: 'DEPRECATED — use urls.delete',
    category: 'MUTATION_SAFE',
    tier: 6,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'urlId', type: 'string', label: 'ID da URL', required: true }],
    domainService: 'ProductUrlService.delete',
    emits: ['product.url_deleted'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['urls.delete'],
  },
];
