import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 0 (self-awareness).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_0_SELF_AWARENESS_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'self.capabilities',
    title: 'Listar capacidades',
    description: 'Mostra o que o Kloel sabe fazer no contexto atual',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CapabilityRegistry.filterFor',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp', 'flow'],
  },
  {
    id: 'self.health',
    title: 'Saúde do sistema',
    description: 'Status de serviços, filas, integrações, banco',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'HealthService.snapshot',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },
  {
    id: 'self.gaps',
    title: 'Listar lacunas',
    description: 'Mostra quais capacidades ainda não estão disponíveis ou estão quebradas',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CapabilityRegistry.listGaps',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },
  {
    id: 'dependencies',
    title: 'Listar dependências',
    description: 'Lista dependências (SBOM) de um workspace com versões',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'workspace',
        type: 'string',
        label: 'Workspace',
        required: true,
        description: 'root|backend|frontend|frontend-admin|worker|e2e',
      },
      {
        key: 'pattern',
        type: 'string',
        label: 'Filtro',
        required: false,
        description: 'Nome do pacote (parcial)',
      },
    ],
    domainService: 'DepsCoverageService.dependencies',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'code_coverage',
    title: 'Cobertura de código',
    description:
      'Retorna cobertura de testes (lines/branches/functions/statements) com linhas não cobertas',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'filePath',
        type: 'string',
        label: 'Arquivo',
        required: false,
        description: 'Caminho do arquivo para cobertura específica',
      },
      {
        key: 'workspace',
        type: 'string',
        label: 'Workspace',
        required: false,
        description: 'root|backend|frontend|frontend-admin|worker|e2e',
      },
    ],
    domainService: 'DepsCoverageService.codeCoverage',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affected_tests',
    title: 'Testes afetados',
    description: 'Dados arquivos fonte, retorna spec/test files que os exercitam',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'files',
        type: 'string',
        label: 'Arquivos',
        required: true,
        description: 'Lista de paths separados por vírgula',
      },
    ],
    domainService: 'DepsCoverageService.affectedTests',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'self.audit_log',
    title: 'Log de ações',
    description: 'Mostra as últimas ações executadas pelo Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['audit:read'],
    inputSchema: [
      {
        key: 'limit',
        type: 'number',
        label: 'Quantidade',
        required: false,
        description: 'Número de ações para mostrar',
      },
    ],
    domainService: 'AuditService.recent',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_products',
    title: 'Listar produtos',
    description: 'Lista todos os produtos do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ProductService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'self.explain',
    title: 'Explicar capacidade',
    description: 'Detalha uma capacidade: o que faz, como usar, status',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'capabilityId',
        type: 'string',
        label: 'ID',
        required: true,
        prompt: 'Qual capacidade você quer saber mais?',
      },
    ],
    domainService: 'CapabilityRegistry.describe',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },
  {
    id: 'list_checkouts',
    title: 'Listar checkouts',
    description: 'Lista checkouts do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CheckoutService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_agent_memory',
    title: 'Buscar na memória',
    description: 'Busca na memória do agente por conversas e decisões',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'MemoryService.search',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_agent_sessions',
    title: 'Buscar sessões',
    description: 'Busca sessões de conversa anteriores',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'SessionService.search',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'toggle_autopilot',
    title: 'Ativar/desativar autopilot',
    description: 'Liga ou desliga o modo autopilot',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'enabled', type: 'boolean', label: 'Ativar?', required: true }],
    domainService: 'AutopilotService.toggle',
    emits: ['autopilot.toggled'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_details',
    title: 'Detalhes do produto',
    description: 'Mostra detalhes completos de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'ProductService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_refunds',
    title: 'Estornos',
    description: 'Lista estornos e reembolsos',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'RefundService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_nps',
    title: 'NPS',
    description: 'Mostra Net Promoter Score',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'NpsService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_whatsapp_status',
    title: 'Status WhatsApp',
    description: 'Verifica status da conexão WhatsApp',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WhatsAppService.status',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_analytics',
    title: 'Analytics',
    description: 'Obtém métricas e analytics do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'metric', type: 'string', label: 'Métrica', required: false },
      { key: 'period', type: 'string', label: 'Período', required: false },
    ],
    domainService: 'AnalyticsService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_order_details',
    title: 'Detalhes do pedido',
    description: 'Mostra detalhes de um pedido',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'orderId', type: 'string', label: 'Pedido', required: true }],
    domainService: 'OrderService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_ai_config',
    title: 'Configuração IA do produto',
    description: 'Mostra configuração de IA de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'ProductAIConfigService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_billing_status',
    title: 'Status faturamento',
    description: 'Mostra status de faturamento e plano',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'BillingService.status',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'change_plan',
    title: 'Mudar plano',
    description: 'Altera o plano do workspace',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['billing:write'],
    inputSchema: [{ key: 'plan', type: 'string', label: 'Novo plano', required: true }],
    domainService: 'BillingService.changePlan',
    emits: ['billing.plan_changed'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'remember_user_info',
    title: 'Lembrar informação',
    description: 'Salva informação do usuário na memória',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'key', type: 'string', label: 'Chave', required: true },
      { key: 'value', type: 'string', label: 'Valor', required: true },
    ],
    domainService: 'MemoryService.set',
    emits: ['memory.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'transcribe_audio',
    title: 'Transcrever áudio',
    description: 'Transcreve áudio para texto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'audioUrl', type: 'string', label: 'URL do áudio', required: true }],
    domainService: 'AudioService.transcribe',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'save_business_info',
    title: 'Salvar info do negócio',
    description: 'Salva informações do negócio',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'businessName', type: 'string', label: 'Nome', required: false }],
    domainService: 'WorkspaceService.updateInfo',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'set_brand_voice',
    title: 'Definir voz da marca',
    description: 'Define tom de voz da marca',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'tone', type: 'string', label: 'Tom', required: true }],
    domainService: 'BrandService.setVoice',
    emits: ['brand.voice_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_workspace_settings',
    title: 'Atualizar configurações',
    description: 'Atualiza configurações do workspace',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'businessName', type: 'string', label: 'Nome', required: false }],
    domainService: 'WorkspaceService.updateSettings',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'read_source_file',
    title: 'Ler código fonte',
    description: 'Lê arquivo fonte do Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'path', type: 'string', label: 'Caminho', required: true }],
    domainService: 'CodeAccessService.read',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'set_business_hours',
    title: 'Horário comercial',
    description: 'Define horário de funcionamento',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'start', type: 'string', label: 'Início', required: true },
      { key: 'end', type: 'string', label: 'Fim', required: true },
    ],
    domainService: 'WorkspaceService.setHours',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'set_sales_policy',
    title: 'Política de vendas',
    description: 'Define política de vendas do workspace',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'policy', type: 'string', label: 'Política', required: true }],
    domainService: 'WorkspaceService.setPolicy',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_whatsapp_chats',
    title: 'Conversas WhatsApp',
    description: 'Lista conversas do WhatsApp',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [],
    domainService: 'WhatsAppService.listChats',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_whatsapp_contacts',
    title: 'Contatos WhatsApp',
    description: 'Lista contatos do WhatsApp',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [],
    domainService: 'WhatsAppService.listContacts',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_billing_info',
    title: 'Atualizar faturamento',
    description: 'Atualiza informações de cobrança/plano',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['billing:write'],
    inputSchema: [],
    domainService: 'BillingService.update',
    emits: ['billing.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_churn',
    title: 'Churn',
    description: 'Mostra taxa de cancelamento',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ChurnService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_social_channels',
    title: 'Canais sociais',
    description: 'Lista canais sociais conectados',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ChannelService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_web',
    title: 'Buscar na web',
    description: 'Busca informações na internet',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'SearchService.web',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_codebase',
    title: 'Buscar no código',
    description: 'Busca no código-fonte do Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'CodeAccessService.search',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_ai_persona',
    title: 'Configurar persona IA',
    description: 'Configura a persona e tom de voz da IA',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      {
        key: 'personality',
        type: 'select',
        label: 'Personalidade',
        required: false,
        enum: ['formal', 'informal', 'friendly', 'professional'],
      },
      { key: 'tone', type: 'string', label: 'Tom de voz', required: false },
    ],
    domainService: 'AIConfigService.update',
    emits: ['ai.persona_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_settings',
    title: 'Configurações',
    description: 'Mostra configurações do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WorkspaceService.getSettings',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_dashboard_summary',
    title: 'Resumo do dashboard',
    description: 'Mostra resumo do dashboard: vendas, leads, oportunidades',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'DashboardService.summary',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_orders',
    title: 'Listar vendas/pedidos',
    description: 'Lista vendas e pedidos do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'status',
        type: 'select',
        label: 'Status',
        required: false,
        enum: ['pending', 'paid', 'cancelled'],
      },
    ],
    domainService: 'OrderService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_sales_summary',
    title: 'Resumo de vendas',
    description: 'Mostra resumo de vendas: total, receita, ticket médio',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'SalesService.summary',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_leads',
    title: 'Listar leads',
    description: 'Lista leads do CRM com filtros',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CrmService.listLeads',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_wallet_balance',
    title: 'Saldo da carteira',
    description: 'Mostra saldo disponível, pendente e total',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getBalance',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_wallet_statement',
    title: 'Extrato da carteira',
    description: 'Mostra extrato de transações',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getStatement',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_abandonments',
    title: 'Carrinhos abandonados',
    description: 'Lista carrinhos abandonados recentes',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AbandonmentService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_plans',
    title: 'Planos do produto',
    description: 'Lista todos os planos de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'PlanService.listForProduct',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_reviews',
    title: 'Avaliações',
    description: 'Lista avaliações de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'ReviewService.listForProduct',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_urls',
    title: 'URLs do produto',
    description: 'Lista URLs cadastradas de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'ProductUrlService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'delete_coupon',
    title: 'Excluir cupom',
    description: 'Remove um cupom permanentemente',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'couponId', type: 'string', label: 'ID do cupom', required: true }],
    domainService: 'CouponService.delete',
    emits: ['coupon.deleted'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'validate_coupon',
    title: 'Validar cupom',
    description: 'Verifica se um cupom é válido para um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'code', type: 'string', label: 'Código', required: true },
      { key: 'productId', type: 'string', label: 'Produto', required: true },
    ],
    domainService: 'CouponService.validate',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'upload_document',
    title: 'Enviar documento',
    description: 'Anexa documento (PDF/imagem) aos documentos fiscais',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      {
        key: 'documentType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['identity', 'contract', 'cnpj_card'],
      },
    ],
    domainService: 'DocumentService.upload',
    emits: ['account.document_uploaded'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_subscriptions',
    title: 'Listar assinaturas',
    description: 'Lista assinaturas ativas do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'SubscriptionService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_source_dir',
    title: 'Listar diretório fonte',
    description: 'Lista arquivos e diretórios do código fonte do Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'path', type: 'string', label: 'Caminho', required: false }],
    domainService: 'CodeAccessService.listDir',
    emits: [],
    surface: ['dashboard-chat'],
  },
];
