import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY sub-partition — Tier 0 (mutations & configuration).
 *
 * Groups MUTATION_SAFE, MUTATION_SENSITIVE, and CONFIGURATION capabilities that
 * touch workspace state (autopilot, billing, brand voice, business hours,
 * documents, coupons, memory writes, etc.).
 *
 * Aggregated by '../partitions/tier-0-self-awareness' alongside tier-0a/0b
 * before being re-exported through '../capability-registry-v2.const'.
 */
export const TIER_0C_MUTATIONS_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'toggle_autopilot',
    title: 'Ativar/desativar autopilot',
    description: 'Liga ou desliga o modo autopilot',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'enabled', type: 'boolean', label: 'Ativar?', required: true }],
    domainService: 'AutopilotService.toggle',
    emits: ['autopilot.toggled'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'change_plan',
    title: 'Mudar plano',
    description: 'Altera o plano do workspace',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['billing:write'],
    inputSchema: [{ key: 'plan', type: 'string', label: 'Novo plano', required: true }],
    domainService: 'BillingService.changePlan',
    emits: ['billing.plan_changed'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'remember_user_info',
    title: 'Lembrar informação',
    description: 'Salva informação do usuário na memória',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'key', type: 'string', label: 'Chave', required: true },
      { key: 'value', type: 'string', label: 'Valor', required: true },
    ],
    domainService: 'MemoryService.set',
    emits: ['memory.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'save_business_info',
    title: 'Salvar info do negócio',
    description: 'Salva informações do negócio',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'businessName', type: 'string', label: 'Nome', required: false }],
    domainService: 'WorkspaceService.updateInfo',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'set_brand_voice',
    title: 'Definir voz da marca',
    description: 'Define tom de voz da marca',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'tone', type: 'string', label: 'Tom', required: true }],
    domainService: 'BrandService.setVoice',
    emits: ['brand.voice_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_workspace_settings',
    title: 'Atualizar configurações',
    description: 'Atualiza configurações do workspace',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'businessName', type: 'string', label: 'Nome', required: false }],
    domainService: 'WorkspaceService.updateSettings',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'set_business_hours',
    title: 'Horário comercial',
    description: 'Define horário de funcionamento',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'start', type: 'string', label: 'Início', required: true },
      { key: 'end', type: 'string', label: 'Fim', required: true },
    ],
    domainService: 'WorkspaceService.setHours',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'set_sales_policy',
    title: 'Política de vendas',
    description: 'Define política de vendas do workspace',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [{ key: 'policy', type: 'string', label: 'Política', required: true }],
    domainService: 'WorkspaceService.setPolicy',
    emits: ['workspace.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_billing_info',
    title: 'Atualizar faturamento',
    description: 'Atualiza informações de cobrança/plano',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['billing:write'],
    inputSchema: [],
    domainService: 'BillingService.update',
    emits: ['billing.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_ai_persona',
    title: 'Configurar persona IA',
    description: 'Configura a persona e tom de voz da IA',
    category: 'CONFIGURATION',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      {
        key: 'personality',
        type: 'select',
        label: 'Personalidade',
        required: false,
        enum: ['formal', 'informal', 'friendly', 'professional'],
      },
      { key: 'tone', type: 'string', label: 'Tom de voz', required: false },
    ],
    domainService: 'AIConfigService.update',
    emits: ['ai.persona_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'delete_coupon',
    title: 'Excluir cupom',
    description: 'Remove um cupom permanentemente',
    category: 'MUTATION_SAFE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'couponId', type: 'string', label: 'ID do cupom', required: true }],
    domainService: 'CouponService.delete',
    emits: ['coupon.deleted'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'upload_document',
    title: 'Enviar documento',
    description: 'Anexa documento (PDF/imagem) aos documentos fiscais',
    category: 'MUTATION_SENSITIVE',
    tier: 0,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      {
        key: 'documentType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['identity', 'contract', 'cnpj_card'],
      },
    ],
    domainService: 'DocumentService.upload',
    emits: ['account.document_uploaded'],
    surface: ['dashboard-chat'],
  },
];
