import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 2 (plans).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_2_PLANS_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'configure_order_bump',
    title: 'Order bump',
    description: 'Configura order bump (upsell no checkout)',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'bumpProductId', type: 'string', label: 'Produto do bump', required: false },
    ],
    domainService: 'PlanService.configure',
    emits: ['plan.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'upload_plan_image',
    title: 'Upload foto do plano',
    description: 'Faz upload da imagem de um plano',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'planId', type: 'string', label: 'Plano', required: true }],
    domainService: 'MediaService.attach + PlanService.setImage',
    emits: ['plan.image_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_plan',
    title: 'Criar plano',
    description: 'Cria novo plano para um produto',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'price', type: 'number', label: 'Preço', required: true },
    ],
    domainService: 'PlanService.create',
    emits: ['plan.created'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_plan',
    title: 'Atualizar plano',
    description: 'Atualiza dados de um plano',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'planId', type: 'string', label: 'Plano', required: true }],
    domainService: 'PlanService.update',
    emits: ['plan.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'delete_plan',
    title: 'Excluir plano',
    description: 'Remove um plano permanentemente',
    category: 'MUTATION_SENSITIVE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'planId', type: 'string', label: 'Plano', required: true }],
    domainService: 'PlanService.delete',
    emits: ['plan.deleted'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.create',
    title: 'Criar plano',
    description: 'Cria um novo plano/variação para um produto',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'name',
        type: 'string',
        label: 'Nome do plano',
        required: true,
        prompt: 'Nome do plano? (ex: "1 Frasco")',
      },
      {
        key: 'price',
        type: 'number',
        label: 'Valor (R$)',
        required: true,
        prompt: 'Qual o valor?',
      },
      { key: 'maxInstallments', type: 'number', label: 'Parcelas máx.', required: false },
      { key: 'acceptPix', type: 'boolean', label: 'Aceitar PIX', required: false },
      { key: 'acceptCard', type: 'boolean', label: 'Aceitar cartão', required: false },
      { key: 'acceptBoleto', type: 'boolean', label: 'Aceitar boleto', required: false },
    ],
    domainService: 'PlanService.create',
    emits: ['plan.created'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.update',
    title: 'Editar plano',
    description: 'Edita um plano existente: valor, parcelas, disponibilidade',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'ID do plano', required: true },
      { key: 'price', type: 'number', label: 'Valor', required: false },
      { key: 'active', type: 'boolean', label: 'Disponível para venda', required: false },
    ],
    domainService: 'PlanService.update',
    emits: ['plan.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
];
