import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 2 (plans).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_2_PLANS_CAPABILITIES: CapabilityDefinition[] = [
  // ── Canonical (dotted) IDs first, then legacy (deprecated) below ──
  {
    id: 'plans.create',
    title: 'Criar plano',
    description: 'Cria um novo plano/variação para um produto',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'name',
        type: 'string',
        label: 'Nome do plano',
        required: true,
        prompt: 'Nome do plano? (ex: "1 Frasco")',
      },
      {
        key: 'price',
        type: 'number',
        label: 'Valor (R$)',
        required: true,
        prompt: 'Qual o valor?',
      },
      { key: 'maxInstallments', type: 'number', label: 'Parcelas máx.', required: false },
      { key: 'acceptPix', type: 'boolean', label: 'Aceitar PIX', required: false },
      { key: 'acceptCard', type: 'boolean', label: 'Aceitar cartão', required: false },
      { key: 'acceptBoleto', type: 'boolean', label: 'Aceitar boleto', required: false },
    ],
    domainService: 'PlanService.create',
    emits: ['plan.created'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.update',
    title: 'Editar plano',
    description: 'Edita um plano existente: valor, parcelas, disponibilidade',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'ID do plano', required: true },
      { key: 'price', type: 'number', label: 'Valor', required: false },
      { key: 'active', type: 'boolean', label: 'Disponível para venda', required: false },
    ],
    domainService: 'PlanService.update',
    emits: ['plan.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
  // ── Wave7 L2: fine-grained plan capabilities (Y-1/Y-2) ──
  {
    id: 'plans.set_payment_methods',
    title: 'Métodos de pagamento do plano',
    description: 'Define quais métodos de pagamento o plano aceita (cartão, PIX, boleto)',
    category: 'MUTATION_SENSITIVE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'Plano', required: true },
      { key: 'card', type: 'boolean', label: 'Aceitar cartão', required: false },
      { key: 'pix', type: 'boolean', label: 'Aceitar PIX', required: false },
      { key: 'boleto', type: 'boolean', label: 'Aceitar boleto', required: false },
    ],
    domainService: 'PlanService.setPaymentMethodsFromArgs',
    emits: ['plan.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.set_installments',
    title: 'Parcelamento do plano',
    description: 'Define o número máximo de parcelas do plano',
    category: 'MUTATION_SENSITIVE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'Plano', required: true },
      { key: 'maxInstallments', type: 'number', label: 'Parcelas máx.', required: true },
    ],
    domainService: 'PlanService.setInstallmentsFromArgs',
    emits: ['plan.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.set_coupons',
    title: 'Cupons no plano',
    description: 'Habilita ou desabilita o uso de cupons de desconto no plano',
    category: 'MUTATION_SENSITIVE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'Plano', required: true },
      { key: 'acceptCoupons', type: 'boolean', label: 'Aceitar cupons', required: true },
    ],
    domainService: 'PlanService.setCouponsFromArgs',
    emits: ['plan.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.set_shipping_mode',
    title: 'Modo de frete do plano',
    description: 'Define o frete do plano: fixo, variável ou grátis (com CEP de origem / faixa)',
    category: 'MUTATION_SENSITIVE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'Plano', required: true },
      {
        key: 'type',
        type: 'select',
        label: 'Tipo de frete',
        required: true,
        enum: ['FIXED', 'VARIABLE', 'FREE', 'NONE'],
      },
      { key: 'fixedValue', type: 'number', label: 'Valor fixo (R$)', required: false },
      { key: 'originCep', type: 'string', label: 'CEP de origem', required: false },
    ],
    domainService: 'PlanService.setShippingFromArgs',
    emits: ['plan.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.set_visibility_for_affiliates',
    title: 'Visibilidade para afiliados',
    description: 'Define se o plano aparece para afiliados promoverem',
    category: 'MUTATION_SENSITIVE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'Plano', required: true },
      {
        key: 'visibleToAffiliates',
        type: 'boolean',
        label: 'Visível para afiliados',
        required: true,
      },
    ],
    domainService: 'PlanService.setVisibilityForAffiliatesFromArgs',
    emits: ['plan.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.set_custom_commission',
    title: 'Comissão personalizada do plano',
    description: 'Define a comissão personalizada de afiliados para o plano (em %)',
    category: 'MUTATION_SENSITIVE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'Plano', required: true },
      { key: 'customCommission', type: 'number', label: 'Comissão (%)', required: true },
    ],
    domainService: 'PlanService.setCustomCommissionFromArgs',
    emits: ['plan.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.set_order_bump',
    title: 'Order bump do plano',
    description: 'Configura o order bump (oferta adicional no checkout) do plano',
    category: 'MUTATION_SENSITIVE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'Plano', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar order bump', required: false },
      { key: 'bumpProductId', type: 'string', label: 'Produto do bump', required: false },
      { key: 'bumpPlanId', type: 'string', label: 'Plano do bump', required: false },
      { key: 'title', type: 'string', label: 'Título da oferta', required: false },
      { key: 'discountPercent', type: 'number', label: 'Desconto (%)', required: false },
    ],
    domainService: 'PlanService.setOrderBumpFromArgs',
    emits: ['plan.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'plans.upload_image',
    title: 'Imagem do plano',
    description: 'Define a imagem (URL) exibida para o plano no checkout',
    category: 'MUTATION_SENSITIVE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'planId', type: 'string', label: 'Plano', required: true },
      { key: 'imageUrl', type: 'string', label: 'URL da imagem', required: true },
    ],
    domainService: 'PlanService.setImageFromArgs',
    emits: ['plan.image_updated'],
    evidenceUrlBuilder: '/produtos/${productId}/planos/${planId}',
    surface: ['dashboard-chat'],
  },
  // ── Legacy IDs (deprecated) — superseded by canonical dotted equivalents ──
  {
    id: 'configure_order_bump',
    title: 'Order bump (legado)',
    description: 'DEPRECATED — use plans.set_order_bump',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'bumpProductId', type: 'string', label: 'Produto do bump', required: false },
    ],
    domainService: 'PlanService.configure',
    emits: ['plan.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['plans.set_order_bump'],
  },
  {
    id: 'upload_plan_image',
    title: 'Upload foto do plano (legado)',
    description: 'DEPRECATED — use plans.upload_image',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'planId', type: 'string', label: 'Plano', required: true }],
    domainService: 'MediaService.attach + PlanService.setImage',
    emits: ['plan.image_updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['plans.upload_image'],
  },
  {
    id: 'create_plan',
    title: 'Criar plano (legado)',
    description: 'DEPRECATED — use plans.create',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'price', type: 'number', label: 'Preço', required: true },
    ],
    domainService: 'PlanService.create',
    emits: ['plan.created'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['plans.create'],
  },
  {
    id: 'update_plan',
    title: 'Atualizar plano (legado)',
    description: 'DEPRECATED — use plans.update',
    category: 'MUTATION_SAFE',
    tier: 2,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'planId', type: 'string', label: 'Plano', required: true }],
    domainService: 'PlanService.update',
    emits: ['plan.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['plans.update'],
  },
  {
    id: 'delete_plan',
    title: 'Excluir plano (legado)',
    description: 'DEPRECATED — no canonical dotted equivalent yet; kept for backward compat',
    category: 'MUTATION_SENSITIVE',
    tier: 2,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'planId', type: 'string', label: 'Plano', required: true }],
    domainService: 'PlanService.delete',
    // Runtime truth: PlanService.delete records no spine event; the bus-only
    // 'plan.deleted' emit died in 6e8ce118.
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
  },
];
