import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 3 (checkouts).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_3_CHECKOUTS_CAPABILITIES: CapabilityDefinition[] = [
  // ── Canonical (dotted) IDs first, legacy (deprecated) at end ──
  {
    id: 'checkouts.create',
    title: 'Criar checkout',
    description: 'Cria checkout vinculado a planos de um produto com personalização',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'name',
        type: 'string',
        label: 'Nome do checkout',
        required: true,
        prompt: 'Nome do checkout?',
      },
      { key: 'acceptPix', type: 'boolean', label: 'Aceitar PIX', required: false },
      { key: 'acceptCard', type: 'boolean', label: 'Aceitar cartão', required: false },
      { key: 'acceptBoleto', type: 'boolean', label: 'Aceitar boleto', required: false },
      { key: 'buttonText', type: 'string', label: 'Texto do botão', required: false },
    ],
    domainService: 'CheckoutService.create',
    emits: ['commerce.checkout.created'],
    evidenceUrlBuilder: '/produtos/${productId}/checkouts/${checkoutId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.update',
    title: 'Editar checkout',
    description: 'Edita checkout existente',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'buttonText', type: 'string', label: 'Texto do botão', required: false },
      { key: 'active', type: 'boolean', label: 'Ativo', required: false },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/checkouts/${checkoutId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.customize_theme',
    title: 'Personalizar tema do checkout',
    description:
      'Personaliza cor principal, cor de fundo, cor do texto, texto do botão e layout do checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'accentColor', type: 'string', label: 'Cor principal', required: false },
      { key: 'backgroundColor', type: 'string', label: 'Cor de fundo', required: false },
      { key: 'textColor', type: 'string', label: 'Cor do texto', required: false },
      { key: 'btnFinalizeText', type: 'string', label: 'Texto do botão', required: false },
      {
        key: 'theme',
        type: 'select',
        label: 'Layout',
        required: false,
        enum: ['NOIR', 'BLANC'],
      },
    ],
    domainService: 'CheckoutService.customizeTheme',
    emits: ['checkout.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/checkouts/${checkoutId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.set_timer',
    title: 'Configurar cronômetro do checkout',
    description: 'Configura o cronômetro de escassez (contagem regressiva/expiração) do checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'enableTimer', type: 'boolean', label: 'Ativar cronômetro', required: false },
      {
        key: 'timerType',
        type: 'select',
        label: 'Tipo',
        required: false,
        enum: ['COUNTDOWN', 'EXPIRATION', 'STOCK'],
      },
      { key: 'timerMinutes', type: 'number', label: 'Minutos', required: false },
      { key: 'timerMessage', type: 'string', label: 'Mensagem', required: false },
    ],
    domainService: 'CheckoutService.configureTimer',
    emits: ['checkout.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/checkouts/${checkoutId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.set_social_proof',
    title: 'Configurar prova social do checkout',
    description: 'Configura a prova social (alertas de compra recente) do checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'socialProofEnabled', type: 'boolean', label: 'Ativar', required: false },
      { key: 'socialProofAlerts', type: 'string', label: 'Alertas (JSON)', required: false },
    ],
    domainService: 'CheckoutService.configureSocialProof',
    emits: ['checkout.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/checkouts/${checkoutId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.set_testimonials',
    title: 'Configurar depoimentos do checkout',
    description: 'Configura os depoimentos exibidos no checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'enableTestimonials', type: 'boolean', label: 'Exibir', required: false },
      { key: 'testimonials', type: 'string', label: 'Depoimentos (JSON)', required: false },
    ],
    domainService: 'CheckoutService.configureTestimonials',
    emits: ['checkout.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/checkouts/${checkoutId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.set_warranty',
    title: 'Configurar garantia do checkout',
    description: 'Configura a garantia (devolução do dinheiro) exibida no checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'enableGuarantee', type: 'boolean', label: 'Exibir garantia', required: false },
      { key: 'guaranteeTitle', type: 'string', label: 'Título', required: false },
      { key: 'guaranteeText', type: 'string', label: 'Texto', required: false },
      { key: 'guaranteeDays', type: 'number', label: 'Dias', required: false },
    ],
    domainService: 'CheckoutService.configureWarranty',
    emits: ['checkout.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/checkouts/${checkoutId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.set_exit_intent',
    title: 'Configurar exit intent do checkout',
    description: 'Configura o popup de intenção de saída (exit intent) do checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'enableExitIntent', type: 'boolean', label: 'Ativar', required: false },
      { key: 'exitIntentTitle', type: 'string', label: 'Título', required: false },
      { key: 'exitIntentDescription', type: 'string', label: 'Descrição', required: false },
      { key: 'exitIntentCouponCode', type: 'string', label: 'Cupom', required: false },
    ],
    domainService: 'CheckoutService.configureExitIntent',
    emits: ['checkout.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/checkouts/${checkoutId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.link_plans',
    title: 'Vincular planos ao checkout',
    description: 'Vincula planos a um checkout',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'planIds', type: 'string', label: 'IDs dos planos', required: true },
    ],
    domainService: 'CheckoutService.linkPlansToCheckout',
    emits: ['checkout.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/checkouts/${checkoutId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'checkouts.set_coupon',
    title: 'Configurar cupons do checkout',
    description: 'Configura o uso de cupons no checkout (popup, cupom automático)',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'checkoutId', type: 'string', label: 'ID do checkout', required: true },
      { key: 'enableCoupon', type: 'boolean', label: 'Permitir cupons', required: false },
      { key: 'showCouponPopup', type: 'boolean', label: 'Mostrar popup', required: false },
      { key: 'autoCouponCode', type: 'string', label: 'Cupom automático', required: false },
    ],
    domainService: 'CheckoutService.configureCoupon',
    emits: ['checkout.updated'],
    evidenceUrlBuilder: '/produtos/${productId}/checkouts/${checkoutId}',
    surface: ['dashboard-chat'],
  },
  // ── Legacy IDs (deprecated) — superseded by canonical dotted equivalents ──
  {
    id: 'configure_social_proof',
    title: 'Prova social (legado)',
    description: 'DEPRECATED — use checkouts.set_social_proof',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['checkouts.set_social_proof'],
  },
  {
    id: 'configure_after_pay',
    title: 'Configurar After Pay (legado)',
    description: 'DEPRECATED — use checkouts.update',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['checkouts.update'],
  },
  {
    id: 'create_checkout',
    title: 'Criar checkout (legado)',
    description: 'DEPRECATED — use checkouts.create',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: true },
    ],
    domainService: 'CheckoutService.create',
    emits: ['commerce.checkout.created'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['checkouts.create'],
  },
  {
    id: 'update_checkout',
    title: 'Atualizar checkout (legado)',
    description: 'DEPRECATED — use checkouts.update',
    category: 'MUTATION_SAFE',
    tier: 3,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'checkoutId', type: 'string', label: 'Checkout', required: true }],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['checkouts.update'],
  },
  {
    id: 'delete_checkout',
    title: 'Excluir checkout (legado)',
    description: 'DEPRECATED — no canonical dotted equivalent yet; kept for backward compat',
    category: 'MUTATION_SENSITIVE',
    tier: 3,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'checkoutId', type: 'string', label: 'Checkout', required: true }],
    domainService: 'CheckoutService.delete',
    emits: ['commerce.checkout.deleted'],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
  },
];
