import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY sub-partition — Tier 0B (query / commerce).
 *
 * Read-only queries scoped to the commerce surface: products, plans, URLs,
 * reviews, coupons, checkouts, refunds. Extracted from `./tier-0b-query`
 * (Gate-fix2-D, 2026-05-28) so each domain's capability list stays reviewable
 * in isolation.
 */
export const TIER_0B_QUERY_COMMERCE_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'list_products',
    title: 'Listar produtos',
    description: 'Lista todos os produtos do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ProductService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_checkouts',
    title: 'Listar checkouts',
    description: 'Lista checkouts do workspace',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CheckoutService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_details',
    title: 'Detalhes do produto',
    description: 'Mostra detalhes completos de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'ProductService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_refunds',
    title: 'Estornos',
    description: 'Lista estornos e reembolsos',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'RefundService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_ai_config',
    title: 'Configuração IA do produto',
    description: 'Mostra configuração de IA de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'ProductAIConfigService.get',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_plans',
    title: 'Planos do produto',
    description: 'Lista todos os planos de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'PlanService.listForProduct',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_reviews',
    title: 'Avaliações',
    description: 'Lista avaliações de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'ReviewService.listForProduct',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_product_urls',
    title: 'URLs do produto',
    description: 'Lista URLs cadastradas de um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'productId', type: 'string', label: 'ID do produto', required: true }],
    domainService: 'ProductUrlService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'validate_coupon',
    title: 'Validar cupom',
    description: 'Verifica se um cupom é válido para um produto',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'code', type: 'string', label: 'Código', required: true },
      { key: 'productId', type: 'string', label: 'Produto', required: true },
    ],
    domainService: 'CouponService.validate',
    emits: [],
    surface: ['dashboard-chat'],
  },
];
