import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY sub-partition — Tier 0 (introspection).
 *
 * SELF_AWARENESS capabilities: capability discovery, system health, audit log,
 * source-code access, coverage/dependency/test introspection.
 *
 * Aggregated by '../partitions/tier-0-self-awareness' alongside tier-0b/0c
 * before being re-exported through '../capability-registry-v2.const'.
 */
export const TIER_0A_INTROSPECTION_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'self.capabilities',
    title: 'Listar capacidades',
    description: 'Mostra o que o Kloel sabe fazer no contexto atual',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CapabilityRegistry.filterFor',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp', 'flow'],
  },
  {
    id: 'self.health',
    title: 'Saúde do sistema',
    description: 'Status de serviços, filas, integrações, banco',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'HealthService.snapshot',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },
  {
    id: 'self.gaps',
    title: 'Listar lacunas',
    description: 'Mostra quais capacidades ainda não estão disponíveis ou estão quebradas',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'CapabilityRegistry.listGaps',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },
  {
    id: 'dependencies',
    title: 'Listar dependências',
    description: 'Lista dependências (SBOM) de um workspace com versões',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'workspace',
        type: 'string',
        label: 'Workspace',
        required: true,
        description: 'root|backend|frontend|frontend-admin|worker|e2e',
      },
      {
        key: 'pattern',
        type: 'string',
        label: 'Filtro',
        required: false,
        description: 'Nome do pacote (parcial)',
      },
    ],
    domainService: 'DepsCoverageService.dependencies',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'code_coverage',
    title: 'Cobertura de código',
    description:
      'Retorna cobertura de testes (lines/branches/functions/statements) com linhas não cobertas',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'filePath',
        type: 'string',
        label: 'Arquivo',
        required: false,
        description: 'Caminho do arquivo para cobertura específica',
      },
      {
        key: 'workspace',
        type: 'string',
        label: 'Workspace',
        required: false,
        description: 'root|backend|frontend|frontend-admin|worker|e2e',
      },
    ],
    domainService: 'DepsCoverageService.codeCoverage',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'affected_tests',
    title: 'Testes afetados',
    description: 'Dados arquivos fonte, retorna spec/test files que os exercitam',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'files',
        type: 'string',
        label: 'Arquivos',
        required: true,
        description: 'Lista de paths separados por vírgula',
      },
    ],
    domainService: 'DepsCoverageService.affectedTests',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'self.audit_log',
    title: 'Log de ações',
    description: 'Mostra as últimas ações executadas pelo Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: ['audit:read'],
    inputSchema: [
      {
        key: 'limit',
        type: 'number',
        label: 'Quantidade',
        required: false,
        description: 'Número de ações para mostrar',
      },
    ],
    domainService: 'AuditService.recent',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'self.explain',
    title: 'Explicar capacidade',
    description: 'Detalha uma capacidade: o que faz, como usar, status',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'capabilityId',
        type: 'string',
        label: 'ID',
        required: true,
        prompt: 'Qual capacidade você quer saber mais?',
      },
    ],
    domainService: 'CapabilityRegistry.describe',
    emits: [],
    surface: ['dashboard-chat', 'whatsapp'],
  },
  {
    id: 'read_source_file',
    title: 'Ler código fonte',
    description: 'Lê arquivo fonte do Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'path', type: 'string', label: 'Caminho', required: true }],
    domainService: 'CodeAccessService.read',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'search_codebase',
    title: 'Buscar no código',
    description: 'Busca no código-fonte do Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'query', type: 'string', label: 'Busca', required: true }],
    domainService: 'CodeAccessService.search',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_source_dir',
    title: 'Listar diretório fonte',
    description: 'Lista arquivos e diretórios do código fonte do Kloel',
    category: 'SELF_AWARENESS',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'path', type: 'string', label: 'Caminho', required: false }],
    domainService: 'CodeAccessService.listDir',
    emits: [],
    surface: ['dashboard-chat'],
  },
];
