import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY sub-partition — Tier 0B (query / workspace).
 *
 * Read-only queries scoped to workspace administration: analytics, billing,
 * settings, wallet balance and statement. Extracted from `./tier-0b-query`
 * (Gate-fix2-D, 2026-05-28).
 */
export const TIER_0B_QUERY_WORKSPACE_CAPABILITIES: CapabilityDefinition[] = [
  // ── Legacy IDs (deprecated) — superseded by canonical dotted equivalents ──
  {
    id: 'get_analytics',
    title: 'Analytics (legado)',
    description: 'DEPRECATED — use analytics.get',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'metric', type: 'string', label: 'Métrica', required: false },
      { key: 'period', type: 'string', label: 'Período', required: false },
    ],
    domainService: 'AnalyticsService.get',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['analytics.get'],
  },
  {
    id: 'get_billing_status',
    title: 'Status faturamento (legado)',
    description: 'DEPRECATED — use billing.status',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'BillingService.status',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['billing.status'],
  },
  {
    id: 'get_settings',
    title: 'Configurações (legado)',
    description: 'DEPRECATED — use workspace.get_settings',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WorkspaceService.getSettings',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['workspace.get_settings'],
  },
  {
    id: 'get_wallet_balance',
    title: 'Saldo da carteira (legado)',
    description: 'DEPRECATED — use wallet.balance',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getBalance',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['wallet.balance'],
  },
  {
    id: 'get_wallet_statement',
    title: 'Extrato da carteira (legado)',
    description: 'DEPRECATED — use wallet.statement',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'WalletService.getStatement',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['wallet.statement'],
  },
];
