import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 1 (products).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_1_PRODUCTS_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'configure_pixel',
    title: 'Configurar pixel',
    description: 'Configura pixels FB/Google do produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'pixelType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['facebook', 'google'],
      },
      { key: 'pixelId', type: 'string', label: 'ID do pixel', required: true },
    ],
    domainService: 'PixelService.configure',
    emits: ['product.pixel_configured'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'upload_product_image',
    title: 'Upload foto do produto',
    description: 'Faz upload da imagem de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'MediaService.attach + ProductService.setImage',
    emits: ['product.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_product',
    title: 'Criar produto',
    description: 'Cria novo produto no catálogo',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'price', type: 'number', label: 'Preço (R$)', required: true },
    ],
    domainService: 'ProductService.create',
    emits: ['product.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'save_product',
    title: 'Salvar produto',
    description: 'Cria ou atualiza um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'price', type: 'number', label: 'Preço (R$)', required: true },
    ],
    domainService: 'ProductService.create',
    emits: ['product.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_product',
    title: 'Atualizar produto',
    description: 'Atualiza dados de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: false },
    ],
    domainService: 'ProductService.update',
    emits: ['product.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'delete_product',
    title: 'Excluir produto',
    description: 'Remove um produto permanentemente',
    category: 'MUTATION_SENSITIVE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [{ key: 'productId', type: 'string', label: 'Produto', required: true }],
    domainService: 'ProductService.delete',
    emits: ['product.deleted'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_shipping',
    title: 'Configurar frete',
    description: 'Configura frete e entrega de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      {
        key: 'shippingType',
        type: 'select',
        label: 'Tipo',
        required: false,
        enum: ['free', 'fixed', 'variable'],
      },
    ],
    domainService: 'ShippingService.configure',
    emits: ['product.shipping_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_warranty',
    title: 'Configurar garantia',
    description: 'Define garantia em dias de um produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'warrantyDays', type: 'number', label: 'Dias de garantia', required: true },
    ],
    domainService: 'ProductService.update',
    emits: ['product.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'configure_exit_intent',
    title: 'Popup de saída',
    description: 'Ativa/desativa popup de exit intent no checkout',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'Produto', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'CheckoutService.update',
    emits: ['checkout.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.create',
    title: 'Criar produto',
    description: 'Cria um novo produto no catálogo do workspace',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: true,
    requiredPermissions: ['product:write'],
    inputSchema: [
      {
        key: 'name',
        type: 'string',
        label: 'Nome',
        required: true,
        prompt: 'Qual o nome do produto?',
      },
      { key: 'description', type: 'string', label: 'Descrição', required: false },
      { key: 'category', type: 'string', label: 'Categoria', required: false },
      {
        key: 'format',
        type: 'select',
        label: 'Formato',
        required: false,
        enum: ['físico', 'digital', 'híbrido'],
      },
      {
        key: 'price',
        type: 'number',
        label: 'Preço (R$)',
        required: true,
        prompt: 'Qual o preço?',
      },
    ],
    domainService: 'ProductService.create',
    emits: ['product.created'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.upload_image',
    title: 'Upload imagem do produto',
    description: 'Anexa uma imagem enviada no chat ao produto',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'imageFile', type: 'file', label: 'Arquivo de imagem', required: true },
    ],
    domainService: 'MediaService.attach + ProductService.setImage',
    emits: ['product.updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
  {
    id: 'products.update',
    title: 'Editar produto',
    description: 'Edita dados gerais de um produto existente',
    category: 'MUTATION_SAFE',
    tier: 1,
    requiresConfirmation: false,
    requiredPermissions: ['product:write'],
    inputSchema: [
      { key: 'productId', type: 'string', label: 'ID do produto', required: true },
      { key: 'name', type: 'string', label: 'Nome', required: false },
      { key: 'description', type: 'string', label: 'Descrição', required: false },
      { key: 'active', type: 'boolean', label: 'Disponível para venda', required: false },
      { key: 'salesPageUrl', type: 'string', label: 'URL da página de vendas', required: false },
    ],
    domainService: 'ProductService.update',
    emits: ['product.updated'],
    evidenceUrlBuilder: '/produtos/${productId}',
    surface: ['dashboard-chat'],
  },
];
