import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 10 (reports).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_10_REPORTS_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'create_broadcast',
    title: 'Criar campanha',
    description: 'Cria campanha de broadcast',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: true,
    requiredPermissions: ['campaign:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'message', type: 'string', label: 'Mensagem', required: true },
    ],
    domainService: 'CampaignService.createBroadcast',
    emits: ['campaign.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'connect_channel',
    title: 'Conectar canal',
    description: 'Conecta canal de marketing (WhatsApp, Instagram, etc)',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      {
        key: 'channel',
        type: 'select',
        label: 'Canal',
        required: true,
        enum: ['whatsapp', 'instagram', 'facebook', 'tiktok', 'email'],
      },
    ],
    domainService: 'ChannelService.connect',
    emits: ['channel.connected'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'connect_whatsapp',
    title: 'Conectar WhatsApp',
    description: 'Conecta o WhatsApp ao workspace',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [],
    domainService: 'WhatsAppService.connect',
    emits: ['whatsapp.connected'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_campaign',
    title: 'Criar campanha',
    description: 'Cria campanha de marketing',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: true,
    requiredPermissions: ['campaign:write'],
    inputSchema: [{ key: 'name', type: 'string', label: 'Nome', required: true }],
    domainService: 'CampaignService.create',
    emits: ['campaign.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_flow',
    title: 'Criar fluxo',
    description: 'Cria fluxo de automação',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['flow:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'trigger', type: 'string', label: 'Gatilho', required: true },
    ],
    domainService: 'FlowService.create',
    emits: ['flow.created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_flows',
    title: 'Listar fluxos',
    description: 'Lista fluxos de automação',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'FlowService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'send_whatsapp_message',
    title: 'Enviar WhatsApp',
    description: 'Envia mensagem via WhatsApp',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [
      { key: 'phone', type: 'string', label: 'Telefone', required: true },
      { key: 'message', type: 'string', label: 'Mensagem', required: true },
    ],
    domainService: 'MessagingService.sendWhatsApp',
    emits: ['whatsapp.message_sent'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'send_channel_message',
    title: 'Enviar por canal',
    description: 'Envia mensagem por canal específico',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['channel:write'],
    inputSchema: [
      { key: 'channel', type: 'string', label: 'Canal', required: true },
      { key: 'message', type: 'string', label: 'Mensagem', required: true },
    ],
    domainService: 'ChannelService.send',
    emits: ['channel.message_sent'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'send_audio',
    title: 'Enviar áudio',
    description: 'Envia mensagem de áudio',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [{ key: 'phone', type: 'string', label: 'Telefone', required: true }],
    domainService: 'MessagingService.sendAudio',
    emits: ['whatsapp.audio_sent'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'send_document',
    title: 'Enviar documento',
    description: 'Envia documento via WhatsApp',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [{ key: 'phone', type: 'string', label: 'Telefone', required: true }],
    domainService: 'MessagingService.sendDocument',
    emits: ['whatsapp.document_sent'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'send_voice_note',
    title: 'Enviar nota de voz',
    description: 'Envia nota de voz via WhatsApp',
    category: 'COMMUNICATION',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [{ key: 'phone', type: 'string', label: 'Telefone', required: true }],
    domainService: 'MessagingService.sendVoiceNote',
    emits: ['whatsapp.voice_sent'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'reports.operations',
    title: 'Operações',
    description: 'Mostra relatório de operações: vendas, receita, ticket médio',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'period',
        type: 'select',
        label: 'Período',
        required: false,
        enum: ['today', 'week', 'month', 'year'],
      },
    ],
    domainService: 'ReportService.getOperations',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'reports.abandonments',
    title: 'Carrinhos abandonados',
    description: 'Mostra carrinhos abandonados no período',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'period',
        type: 'select',
        label: 'Período',
        required: false,
        enum: ['today', 'week', 'month', 'year'],
      },
    ],
    domainService: 'ReportService.getAbandonments',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_whatsapp_messages',
    title: 'Mensagens WhatsApp',
    description: 'Lista mensagens de uma conversa do WhatsApp',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [{ key: 'chatId', type: 'string', label: 'Conversa', required: true }],
    domainService: 'WhatsAppService.getMessages',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'get_whatsapp_backlog',
    title: 'Backlog WhatsApp',
    description: 'Mostra backlog de mensagens não lidas do WhatsApp',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:read'],
    inputSchema: [],
    domainService: 'WhatsAppService.getBacklog',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'set_whatsapp_presence',
    title: 'Presença WhatsApp',
    description: 'Define status de presença no WhatsApp (online/ausente)',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [
      {
        key: 'presence',
        type: 'select',
        label: 'Status',
        required: true,
        enum: ['available', 'unavailable'],
      },
    ],
    domainService: 'WhatsAppService.setPresence',
    emits: ['whatsapp.presence_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'sync_whatsapp_history',
    title: 'Sincronizar WhatsApp',
    description: 'Sincroniza histórico de conversas do WhatsApp',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['whatsapp:write'],
    inputSchema: [],
    domainService: 'WhatsAppService.syncHistory',
    emits: ['whatsapp.history_synced'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'create_agent_job',
    title: 'Criar job agente',
    description: 'Cria um job automatizado para o agente executar',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: true,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: true },
      { key: 'schedule', type: 'string', label: 'Agendamento', required: false },
      { key: 'action', type: 'string', label: 'Ação', required: true },
    ],
    domainService: 'AgentJobService.create',
    emits: ['agent.job_created'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'list_agent_jobs',
    title: 'Listar jobs agente',
    description: 'Lista jobs automatizados do agente',
    category: 'QUERY',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AgentJobService.list',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'set_agent_job_enabled',
    title: 'Ativar/desativar job',
    description: 'Ativa ou desativa um job automatizado do agente',
    category: 'MUTATION_SAFE',
    tier: 10,
    requiresConfirmation: false,
    requiredPermissions: ['workspace:write'],
    inputSchema: [
      { key: 'jobId', type: 'string', label: 'Job', required: true },
      { key: 'enabled', type: 'boolean', label: 'Ativar?', required: true },
    ],
    domainService: 'AgentJobService.setEnabled',
    emits: ['agent.job_updated'],
    surface: ['dashboard-chat'],
  },
];
