import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY sub-partition — Tier 0B (query / sales-ops).
 *
 * Read-only queries scoped to the sales-operations surface: orders, sales
 * summaries, leads, abandonments, dashboard, NPS, churn, subscriptions.
 * Extracted from `./tier-0b-query` (Gate-fix2-D, 2026-05-28).
 */
export const TIER_0B_QUERY_SALES_CAPABILITIES: CapabilityDefinition[] = [
  // ── Legacy IDs (deprecated) — superseded by canonical dotted equivalents ──
  {
    id: 'get_nps',
    title: 'NPS (legado)',
    description: 'DEPRECATED — use analytics.nps',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'NpsService.get',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['analytics.nps'],
  },
  {
    id: 'get_order_details',
    title: 'Detalhes do pedido (legado)',
    description: 'DEPRECATED — use sales.get_order',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [{ key: 'orderId', type: 'string', label: 'Pedido', required: true }],
    domainService: 'OrderService.get',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['sales.get_order'],
  },
  {
    id: 'get_churn',
    title: 'Churn (legado)',
    description: 'DEPRECATED — use analytics.churn',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'ChurnService.get',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['analytics.churn'],
  },
  {
    id: 'get_dashboard_summary',
    title: 'Resumo do dashboard (legado)',
    description: 'DEPRECATED — use dashboard.summary',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'DashboardService.summary',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['dashboard.summary'],
  },
  {
    id: 'list_orders',
    title: 'Listar vendas/pedidos (legado)',
    description: 'DEPRECATED — use sales.list',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      {
        key: 'status',
        type: 'select',
        label: 'Status',
        required: false,
        enum: ['pending', 'paid', 'cancelled'],
      },
    ],
    domainService: 'OrderService.list',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['sales.list'],
  },
  {
    id: 'get_sales_summary',
    title: 'Resumo de vendas (legado)',
    description: 'DEPRECATED — use analytics.sales_summary',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'SalesService.summary',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['analytics.sales_summary'],
  },
  {
    id: 'get_abandonments',
    title: 'Carrinhos abandonados (legado)',
    description: 'DEPRECATED — use analytics.abandonments',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'AbandonmentService.list',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['analytics.abandonments'],
  },
  {
    id: 'list_subscriptions',
    title: 'Listar assinaturas (legado)',
    description: 'DEPRECATED — use subscriptions.list',
    category: 'QUERY',
    tier: 0,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [],
    domainService: 'SubscriptionService.list',
    emits: [],
    surface: ['dashboard-chat'],
    maturity: 'deprecated',
    dependsOn: ['subscriptions.list'],
  },
];
