import { type CapabilityDefinition } from '../capability-registry-v2.types';

/**
 * KLOEL CAPABILITY REGISTRY partition — Tier 11 (configuration).
 *
 * Extracted from capability-registry-v2.const.ts.
 * Consumers should import CAPABILITY_DEFINITIONS from the barrel
 * '../capability-registry-v2.const' rather than this partition directly.
 */
export const TIER_11_CONFIGURATION_CAPABILITIES: CapabilityDefinition[] = [
  {
    id: 'toggle_theme',
    title: 'Alternar tema',
    description: 'Alterna entre tema claro e escuro',
    category: 'CONFIGURATION',
    tier: 11,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'theme', type: 'select', label: 'Tema', required: true, enum: ['light', 'dark'] },
    ],
    domainService: 'ThemeService.set',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_fiscal_data',
    title: 'Atualizar dados fiscais',
    description: 'Atualiza CPF/CNPJ e dados fiscais',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'personType', type: 'select', label: 'Tipo', required: true, enum: ['PF', 'PJ'] },
      { key: 'document', type: 'string', label: 'CPF/CNPJ', required: true },
    ],
    domainService: 'AccountService.updateFiscalData',
    emits: ['account.fiscal_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.update_fiscal',
    title: 'Atualizar dados fiscais',
    description: 'Atualiza dados fiscais: CPF/CNPJ, razão social, endereço',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'personType', type: 'select', label: 'Tipo', required: true, enum: ['PF', 'PJ'] },
      { key: 'document', type: 'string', label: 'CPF/CNPJ', required: true },
      { key: 'businessName', type: 'string', label: 'Razão social', required: false },
      { key: 'zipCode', type: 'string', label: 'CEP', required: false },
    ],
    domainService: 'AccountService.updateFiscalData',
    emits: ['account.fiscal_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.update_bank',
    title: 'Atualizar dados bancários',
    description: 'Atualiza conta bancária para recebimento de saques',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'bankCode', type: 'string', label: 'Código do banco', required: true },
      { key: 'agency', type: 'string', label: 'Agência', required: true },
      { key: 'account', type: 'string', label: 'Conta', required: true },
    ],
    domainService: 'AccountService.updateBankAccount',
    emits: ['account.bank_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.set_pix_key',
    title: 'Cadastrar chave PIX',
    description: 'Cadastra ou altera a chave PIX',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'pixKey', type: 'string', label: 'Chave PIX', required: true },
      {
        key: 'pixKeyType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['CPF', 'CNPJ', 'email', 'celular', 'aleatória'],
      },
    ],
    domainService: 'AccountService.setPixKey',
    emits: ['account.pix_updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'account.upload_document',
    title: 'Enviar documento',
    description: 'Anexa um documento (PDF/imagem) enviado pelo chat aos documentos fiscais',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      {
        key: 'documentType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['identity', 'contract', 'cnpj_card'],
      },
    ],
    domainService: 'DocumentService.upload',
    emits: ['account.document_uploaded'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'ui.theme',
    title: 'Alternar tema',
    description: 'Alterna entre tema claro e escuro',
    category: 'CONFIGURATION',
    tier: 11,
    requiresConfirmation: false,
    requiredPermissions: [],
    inputSchema: [
      { key: 'theme', type: 'select', label: 'Tema', required: true, enum: ['light', 'dark'] },
    ],
    domainService: 'ThemeService.set',
    emits: [],
    surface: ['dashboard-chat'],
  },
  {
    id: 'update_personal_data',
    title: 'Atualizar dados pessoais',
    description: 'Atualiza nome, email, telefone do workspace',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'name', type: 'string', label: 'Nome', required: false },
      { key: 'email', type: 'string', label: 'Email', required: false },
      { key: 'phone', type: 'string', label: 'Telefone', required: false },
    ],
    domainService: 'AccountService.updatePersonalData',
    emits: ['account.updated'],
    surface: ['dashboard-chat'],
  },
  {
    id: 'set_pix_key',
    title: 'Cadastrar chave PIX',
    description: 'Cadastra ou altera chave PIX',
    category: 'MUTATION_SENSITIVE',
    tier: 11,
    requiresConfirmation: true,
    requiredPermissions: ['account:write'],
    inputSchema: [
      { key: 'key', type: 'string', label: 'Chave PIX', required: true },
      {
        key: 'keyType',
        type: 'select',
        label: 'Tipo',
        required: true,
        enum: ['CPF', 'CNPJ', 'email', 'celular', 'aleatoria'],
      },
    ],
    domainService: 'AccountService.setPixKey',
    emits: ['account.pix_updated'],
    surface: ['dashboard-chat'],
  },
];
