import type { Prisma } from '@prisma/client';
import type { KloelContextFormatterLimits } from './kloel-context-formatter.types';

/**
 * Builds the Prisma select object for workspace product context queries.
 * Extracted to avoid duplication between KloelWorkspaceContextService and
 * KloelWorkspaceContextLinkedProductService.
 */
export function buildWorkspaceProductSelect(limits: KloelContextFormatterLimits) {
  return {
    id: true,
    name: true,
    price: true,
    currency: true,
    description: true,
    category: true,
    sku: true,
    tags: true,
    format: true,
    paymentLink: true,
    active: true,
    featured: true,
    status: true,
    stockQuantity: true,
    trackStock: true,
    salesPageUrl: true,
    thankyouUrl: true,
    thankyouBoletoUrl: true,
    thankyouPixUrl: true,
    reclameAquiUrl: true,
    supportEmail: true,
    warrantyDays: true,
    isSample: true,
    shippingType: true,
    shippingValue: true,
    affiliateEnabled: true,
    affiliateVisible: true,
    affiliateAutoApprove: true,
    commissionType: true,
    commissionCookieDays: true,
    commissionPercent: true,
    merchandContent: true,
    affiliateTerms: true,
    afterPayDuplicateAddress: true,
    afterPayAffiliateCharge: true,
    afterPayChargeValue: true,
    afterPayShippingProvider: true,
    aiConfig: {
      select: {
        customerProfile: true,
        positioning: true,
        objections: true,
        salesArguments: true,
        upsellConfig: true,
        downsellConfig: true,
        tone: true,
        persistenceLevel: true,
        messageLimit: true,
        followUpConfig: true,
        technicalInfo: true,
      },
    },
    plans: {
      where: { active: true },
      orderBy: [{ salesCount: 'desc' }, { updatedAt: 'desc' }],
      take: limits.workspaceProductPlanLimit,
      select: {
        name: true,
        price: true,
        currency: true,
        billingType: true,
        maxInstallments: true,
        recurringInterval: true,
        trialEnabled: true,
        trialDays: true,
        trialPrice: true,
        salesCount: true,
        termsUrl: true,
        aiConfig: true,
      },
    },
    checkouts: {
      where: { active: true },
      orderBy: [{ conversionRate: 'desc' }, { updatedAt: 'desc' }],
      take: limits.workspaceProductCheckoutLimit,
      select: {
        name: true,
        code: true,
        uniqueVisits: true,
        totalVisits: true,
        abandonRate: true,
        cancelRate: true,
        conversionRate: true,
      },
    },
    coupons: {
      where: { active: true },
      orderBy: { createdAt: 'desc' as const },
      take: limits.workspaceProductCouponLimit,
      select: {
        code: true,
        discountType: true,
        discountValue: true,
        maxUses: true,
        usedCount: true,
        expiresAt: true,
      },
    },
    campaigns: {
      orderBy: [{ paidCount: 'desc' }, { updatedAt: 'desc' }],
      take: limits.workspaceProductCampaignLimit,
      select: { name: true, code: true, salesCount: true, paidCount: true },
    },
    commissions: {
      orderBy: { createdAt: 'desc' as const },
      take: limits.workspaceProductCommissionLimit,
      select: { role: true, percentage: true, agentName: true, agentEmail: true },
    },
    urls: {
      where: { active: true },
      orderBy: [{ salesFromUrl: 'desc' }, { updatedAt: 'desc' }],
      take: limits.workspaceProductUrlLimit,
      select: {
        description: true,
        url: true,
        isPrivate: true,
        aiLearning: true,
        chatEnabled: true,
        salesFromUrl: true,
      },
    },
    reviews: {
      orderBy: { createdAt: 'desc' as const },
      take: limits.workspaceProductReviewLimit,
      select: { rating: true, comment: true, authorName: true, verified: true },
    },
  } as Prisma.ProductSelect;
}
