#!/usr/bin/env bash
#
# Launch the kloel-protocol-hub MCP server — the unified cognitive interface
# layer that aggregates LSP, DAP, CDP, OpenAPI, AsyncAPI, SARIF, SBOM,
# OpenTelemetry, Tree-sitter, and Test reports under a single MCP entry.
#
# Tools exposed (see tools/cognitive-hub/protocol-hub.mjs):
#   protocol_hub_status    health check of all 10 protocols
#   protocol_hub_openapi   query NestJS HTTP routes/schemas
#   protocol_hub_asyncapi  query BullMQ event channels + payloads
#   protocol_hub_sarif     query static-analysis findings
#   protocol_hub_sbom      query dependency inventory (CycloneDX)
#   protocol_hub_manifest  full protocol inventory + agent config paths
#
# Data files consumed:
#   tools/openapi/openapi-spec.json       (generated by scripts/cognitive/openapi-extract.mjs)
#   tools/asyncapi/asyncapi-spec.json     (generated by scripts/cognitive/asyncapi-extract.mjs)
#   tools/sarif/*.sarif                   (generated by scripts/cognitive/sarif-aggregate.mjs)
#   tools/sbom/sbom-manifest.json         (generated by scripts/cognitive/sbom-aggregate.mjs)
#
# stdout is reserved for MCP stdio — this script prints nothing to stdout.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." >/dev/null 2>&1 && pwd)"
HUB="${REPO_ROOT}/tools/cognitive-hub/protocol-hub.mjs"

if [[ ! -f "${HUB}" ]]; then
  echo "[cognitive-hub-launcher] hub missing at ${HUB}" >&2
  exit 2
fi

cd "${REPO_ROOT}"
exec node "${HUB}" "$@"
