import { deriveUnitValue, deriveZeroValue } from '../../../dynamic-reality-kernel';
import type {
  PulseActorEvidence,
  PulseCapabilityState,
  PulseCodebaseTruth,
  PulseResolvedManifest,
} from '../../../types';

export function resolvedManifest(): PulseResolvedManifest {
  return {
    generatedAt: '2026-04-29T00:00:00.000Z',
    sourceManifestPath: null,
    projectId: 'test',
    projectName: 'Test',
    systemType: 'test',
    supportedStacks: [],
    surfaces: [],
    criticalDomains: [],
    modules: [],
    flowGroups: [],
    actorProfiles: [],
    scenarioSpecs: [],
    flowSpecs: [],
    invariantSpecs: [],
    temporaryAcceptances: [],
    certificationTiers: [],
    finalReadinessCriteria: {
      requireAllTiersPass: true,
      requireNoAcceptedCriticalFlows: true,
      requireNoAcceptedCriticalScenarios: true,
      requireWorldStateConvergence: true,
    },
    securityRequirements: [],
    recoveryRequirements: [],
    slos: {},
    summary: {
      totalModules: deriveZeroValue(),
      resolvedModules: deriveZeroValue(),
      unresolvedModules: deriveZeroValue(),
      scopeOnlyModuleCandidates: deriveZeroValue(),
      humanRequiredModules: deriveZeroValue(),
      totalFlowGroups: deriveZeroValue(),
      resolvedFlowGroups: deriveZeroValue(),
      unresolvedFlowGroups: deriveZeroValue(),
      orphanManualModules: deriveZeroValue(),
      orphanFlowSpecs: deriveZeroValue(),
      excludedModules: deriveZeroValue(),
      excludedFlowGroups: deriveZeroValue(),
      groupedFlowGroups: deriveZeroValue(),
      sharedCapabilityGroups: deriveZeroValue(),
      opsInternalFlowGroups: deriveZeroValue(),
      legacyNoiseFlowGroups: deriveZeroValue(),
      legacyManualModules: deriveZeroValue(),
    },
    diagnostics: {
      unresolvedModules: [],
      orphanManualModules: [],
      scopeOnlyModuleCandidates: [],
      humanRequiredModules: [],
      unresolvedFlowGroups: [],
      orphanFlowSpecs: [],
      excludedModules: [],
      excludedFlowGroups: [],
      legacyManualModules: [],
      groupedFlowGroups: [],
      sharedCapabilityGroups: [],
      opsInternalFlowGroups: [],
      legacyNoiseFlowGroups: [],
      blockerCount: deriveZeroValue(),
      warningCount: deriveZeroValue(),
    },
  };
}

export function capabilityState(): PulseCapabilityState {
  return {
    generatedAt: '2026-04-29T00:00:00.000Z',
    summary: {
      totalCapabilities: deriveUnitValue(),
      realCapabilities: deriveUnitValue(),
      partialCapabilities: deriveZeroValue(),
      latentCapabilities: deriveZeroValue(),
      phantomCapabilities: deriveZeroValue(),
      humanRequiredCapabilities: deriveZeroValue(),
      foundationalCapabilities: deriveZeroValue(),
      connectedCapabilities: deriveZeroValue(),
      operationalCapabilities: deriveUnitValue(),
      productionReadyCapabilities: deriveZeroValue(),
      runtimeObservedCapabilities: deriveZeroValue(),
      scenarioCoveredCapabilities: deriveZeroValue(),
    },
    capabilities: [
      {
        id: 'capability:opaque',
        name: 'Opaque',
        truthMode: 'inferred',
        status: 'real',
        confidence: 0.8,
        userFacing: true,
        runtimeCritical: false,
        protectedByGovernance: false,
        ownerLane: 'customer',
        executionMode: 'ai_safe',
        rolesPresent: ['interface', 'orchestration', 'persistence'],
        missingRoles: [],
        filePaths: [],
        nodeIds: ['ui:opaque', 'api:opaque', 'db:opaque'],
        routePatterns: ['/opaque/create'],
        evidenceSources: [],
        codacyIssueCount: deriveZeroValue(),
        highSeverityIssueCount: deriveZeroValue(),
        blockingReasons: [],
        validationTargets: [],
        maturity: {
          stage: 'operational',
          score: 0.8,
          dimensions: {
            interfacePresent: true,
            apiSurfacePresent: true,
            orchestrationPresent: true,
            persistencePresent: true,
            sideEffectPresent: false,
            runtimeEvidencePresent: false,
            validationPresent: true,
            scenarioCoveragePresent: false,
            codacyHealthy: true,
            simulationOnly: false,
          },
          missing: [],
        },
        dod: {
          status: 'partial',
          missingRoles: [],
          blockers: [],
          truthModeMet: false,
        },
      },
    ],
  };
}

export function codebaseTruth(): PulseCodebaseTruth {
  return {
    generatedAt: '2026-04-29T00:00:00.000Z',
    summary: {
      totalPages: deriveUnitValue(),
      userFacingPages: deriveUnitValue(),
      discoveredModules: deriveUnitValue(),
      discoveredFlows: deriveUnitValue(),
      blockerCount: deriveZeroValue(),
      warningCount: deriveZeroValue(),
    },
    pages: [],
    discoveredModules: [],
    discoveredFlows: [
      {
        id: 'flow:opaque-create',
        moduleKey: 'opaque',
        moduleName: 'Opaque',
        pageRoute: '/opaque',
        elementLabel: 'Create Opaque',
        httpMethod: 'POST',
        endpoint: '/opaque/create',
        backendRoute: '/opaque/create',
        connected: true,
        persistent: true,
        semanticTokens: ['opaque', 'create'],
        declaredFlow: null,
      },
    ],
    divergence: {
      declaredNotDiscovered: [],
      discoveredNotDeclared: [],
      declaredButInternal: [],
      frontendSurfaceWithoutBackendSupport: [],
      backendCapabilityWithoutFrontendSurface: [],
      shellWithoutPersistence: [],
      flowCandidatesWithoutOracle: [],
      blockerCount: deriveZeroValue(),
      warningCount: deriveZeroValue(),
    },
  };
}

export function actorEvidence(): PulseActorEvidence {
  return {
    actorKind: 'customer',
    declared: [],
    executed: ['opaque-create'],
    missing: [],
    passed: ['opaque-create'],
    failed: [],
    artifactPaths: [],
    summary: 'dynamic actor bucket',
    results: [
      {
        scenarioId: 'opaque-create',
        actorKind: 'customer',
        scenarioKind: 'single-session',
        critical: true,
        requested: true,
        runner: 'derived',
        status: 'passed',
        executed: true,
        summary: 'passed',
        artifactPaths: [],
        specsExecuted: [],
        durationMs: deriveUnitValue(),
        worldStateTouches: [],
        moduleKeys: ['opaque'],
        routePatterns: ['/opaque/create'],
      },
    ],
  };
}
