import { deriveUnitValue, deriveZeroValue } from '../../../dynamic-reality-kernel';
import type { PulseScopeState, PulseStructuralGraph, PulseStructuralNode } from '../../../types';

export function structuralNode(overrides: Partial<PulseStructuralNode>): PulseStructuralNode {
  return {
    id: 'node:opaque',
    kind: 'backend_route',
    role: 'orchestration',
    truthMode: 'inferred',
    adapter: 'test',
    label: 'Opaque',
    file: 'backend/src/opaque/opaque.controller.ts',
    line: deriveUnitValue(),
    userFacing: true,
    runtimeCritical: false,
    protectedByGovernance: false,
    metadata: {},
    ...overrides,
  };
}

export function structuralGraph(nodes: PulseStructuralNode[]): PulseStructuralGraph {
  return {
    generatedAt: '2026-04-29T00:00:00.000Z',
    summary: {
      totalNodes: nodes.length,
      totalEdges: deriveUnitValue() + deriveUnitValue(),
      roleCounts: {
        interface: nodes.filter((node) => node.role === 'interface').length,
        orchestration: nodes.filter((node) => node.role === 'orchestration').length,
        persistence: nodes.filter((node) => node.role === 'persistence').length,
        side_effect: nodes.filter((node) => node.role === 'side_effect').length,
        simulation: deriveZeroValue(),
      },
      interfaceChains: deriveUnitValue(),
      completeChains: deriveUnitValue(),
      partialChains: deriveZeroValue(),
      simulatedChains: deriveZeroValue(),
    },
    nodes,
    edges: [
      {
        id: 'edge:ui-api',
        from: 'ui:opaque',
        to: 'api:opaque',
        kind: 'calls',
        truthMode: 'observed',
        evidence: 'test',
      },
      {
        id: 'edge:api-db',
        from: 'api:opaque',
        to: 'db:opaque',
        kind: 'persists',
        truthMode: 'observed',
        evidence: 'test',
      },
    ],
  };
}

export function scopeState(): PulseScopeState {
  return {
    generatedAt: '2026-04-29T00:00:00.000Z',
    rootDir: '/tmp/pulse-dynamic',
    summary: {
      totalFiles: deriveUnitValue() + deriveUnitValue() + deriveUnitValue(),
      totalLines: 90,
      runtimeCriticalFiles: deriveZeroValue(),
      userFacingFiles: deriveUnitValue(),
      humanRequiredFiles: deriveZeroValue(),
      surfaceCounts: {
        frontend: deriveUnitValue(),
        'frontend-admin': deriveZeroValue(),
        backend: deriveUnitValue() + deriveUnitValue(),
        worker: deriveZeroValue(),
        prisma: deriveZeroValue(),
        e2e: deriveZeroValue(),
        scripts: deriveZeroValue(),
        docs: deriveZeroValue(),
        infra: deriveZeroValue(),
        governance: deriveZeroValue(),
        'root-config': deriveZeroValue(),
        artifacts: deriveZeroValue(),
        misc: deriveZeroValue(),
      },
      kindCounts: {
        source: deriveUnitValue() + deriveUnitValue() + deriveUnitValue(),
        spec: deriveZeroValue(),
        migration: deriveZeroValue(),
        config: deriveZeroValue(),
        document: deriveZeroValue(),
        artifact: deriveZeroValue(),
      },
      unmappedModuleCandidates: [],
      inventoryCoverage: 100,
      classificationCoverage: 100,
      structuralGraphCoverage: 100,
      testCoverage: deriveZeroValue(),
      scenarioCoverage: deriveZeroValue(),
      runtimeEvidenceCoverage: deriveZeroValue(),
      productionProofCoverage: deriveZeroValue(),
      orphanFiles: [],
      unknownFiles: [],
    },
    parity: {
      status: 'pass',
      mode: 'repo_inventory_with_codacy_spotcheck',
      confidence: 'high',
      reason: 'test',
      inventoryFiles: deriveUnitValue() + deriveUnitValue() + deriveUnitValue(),
      codacyObservedFiles: deriveZeroValue(),
      codacyObservedFilesCovered: deriveZeroValue(),
      missingCodacyFiles: [],
    },
    codacy: {
      snapshotAvailable: false,
      sourcePath: null,
      syncedAt: null,
      ageMinutes: null,
      stale: false,
      loc: deriveZeroValue(),
      totalIssues: deriveZeroValue(),
      severityCounts: {
        HIGH: deriveZeroValue(),
        MEDIUM: deriveZeroValue(),
        LOW: deriveZeroValue(),
        UNKNOWN: 0,
      },
      toolCounts: {},
      topFiles: [],
      highPriorityBatch: [],
      observedFiles: [],
    },
    files: [
      {
        path: 'frontend/src/app/opaque/page.tsx',
        extension: '.tsx',
        lineCount: 30,
        surface: 'frontend',
        kind: 'source',
        runtimeCritical: false,
        userFacing: true,
        ownerLane: 'customer',
        executionMode: 'ai_safe',
        protectedByGovernance: false,
        codacyTracked: false,
        moduleCandidate: 'opaque',
        observedCodacyIssueCount: deriveZeroValue(),
        highSeverityIssueCount: deriveZeroValue(),
        highestObservedSeverity: null,
      },
      {
        path: 'backend/src/opaque/opaque.controller.ts',
        extension: '.ts',
        lineCount: 30,
        surface: 'backend',
        kind: 'source',
        runtimeCritical: false,
        userFacing: true,
        ownerLane: 'customer',
        executionMode: 'ai_safe',
        protectedByGovernance: false,
        codacyTracked: false,
        moduleCandidate: 'opaque',
        observedCodacyIssueCount: deriveZeroValue(),
        highSeverityIssueCount: deriveZeroValue(),
        highestObservedSeverity: null,
      },
      {
        path: 'backend/src/opaque/opaque.repository.ts',
        extension: '.ts',
        lineCount: 30,
        surface: 'backend',
        kind: 'source',
        runtimeCritical: false,
        userFacing: false,
        ownerLane: 'customer',
        executionMode: 'ai_safe',
        protectedByGovernance: false,
        codacyTracked: false,
        moduleCandidate: 'opaque',
        observedCodacyIssueCount: deriveZeroValue(),
        highSeverityIssueCount: deriveZeroValue(),
        highestObservedSeverity: null,
      },
    ],
    moduleAggregates: [
      {
        moduleKey: 'opaque',
        fileCount: deriveUnitValue() + deriveUnitValue() + deriveUnitValue(),
        runtimeCriticalFileCount: deriveZeroValue(),
        userFacingFileCount: deriveUnitValue() + deriveUnitValue(),
        humanRequiredFileCount: deriveZeroValue(),
        observedCodacyIssueCount: deriveZeroValue(),
        highSeverityIssueCount: deriveZeroValue(),
        surfaces: ['frontend', 'backend'],
      },
    ],
    excludedFiles: [],
    scopeSource: 'repo_filesystem',
    manifestBoundary: false,
    manifestRole: 'semantic_overlay',
  };
}
