import type { AgentSkillDefinition } from './agent-runtime.types';

export const DEFAULT_SKILLS: AgentSkillDefinition[] = [
  {
    id: 'checkout-recovery',
    title: 'Checkout Recovery',
    summary: 'Recupera intenção de compra com memória do lead, produto e política comercial.',
    category: 'commercial',
    riskLevel: 'normal',
    allowedTools: ['get_lead_details', 'list_products', 'create_payment_link'],
    requiredEvidence: ['lead_status', 'product_offer', 'payment_policy'],
    delegationRules: [],
    validation: ['workspace_isolation', 'no_fake_discount', 'payment_link_audit'],
    rollback: ['do_not_send_without_consent', 'cancel_scheduled_followup_if_requested'],
    metrics: ['conversion_rate', 'response_rate', 'refund_rate'],
    body: 'Use histórico observado do lead e dados reais de produto. Se faltar preço, estoque, garantia ou forma de pagamento, peça dado faltante antes de prometer.',
    version: 1,
    updatedAt: new Date(0).toISOString(),
  },
  {
    id: 'objection-handling',
    title: 'Objection Handling',
    summary: 'Responde objeções usando memória de produto, casos anteriores e limites de desconto.',
    category: 'commercial',
    riskLevel: 'normal',
    allowedTools: ['get_lead_details', 'list_products', 'remember_user_info'],
    requiredEvidence: ['objection_text', 'product_claims', 'sales_policy'],
    delegationRules: [],
    validation: ['do_not_invent_claims', 'respect_discount_limit'],
    rollback: ['mark_lead_for_human_review_when_claim_uncertain'],
    metrics: ['objection_resolution_rate', 'handoff_rate'],
    body: 'Valide a emoção, responda com evidência real e avance um próximo passo simples. Não invente escassez, garantia ou resultado.',
    version: 1,
    updatedAt: new Date(0).toISOString(),
  },
  {
    id: 'pulse-self-check',
    title: 'PULSE Self Check',
    summary: 'Consulta o estado operacional PULSE antes de planejar ação autônoma.',
    category: 'pulse',
    riskLevel: 'safe',
    allowedTools: [],
    requiredEvidence: ['pulse_certificate', 'machine_readiness', 'directive'],
    delegationRules: [],
    validation: ['no_overclaim', 'authority_boundary'],
    rollback: ['stop_when_pulse_degraded'],
    metrics: ['blocked_overclaims', 'safe_next_units'],
    body: 'Trate PULSE como fonte de verdade operacional. Diferencie canWorkNow de canDeclareComplete.',
    version: 1,
    updatedAt: new Date(0).toISOString(),
  },
];
