#!/usr/bin/env node
// tools/e2e-sandbox/up.mjs — orquestra docker compose up + write .env.sandbox

import { spawn } from 'node:child_process';
import { writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..', '..');
const COMPOSE = join(__dirname, 'docker-compose.yml');

async function main() {
  console.log('[sandbox] booting postgres + redis + stripe-mock + meta-waha-mock');
  await run(['docker', 'compose', '-f', COMPOSE, 'up', '-d', '--wait']);

  const env = `
# tools/e2e-sandbox sandbox env — do NOT commit; generated by tools/e2e-sandbox/up.mjs
DATABASE_URL=postgresql://kloel:kloel@localhost:55432/kloel_sandbox
REDIS_URL=redis://localhost:56379
STRIPE_SECRET_KEY=sk_test_sandbox_mock
STRIPE_API_BASE=http://localhost:12111
STRIPE_WEBHOOK_SECRET=whsec_test_sandbox
META_GRAPH_BASE_URL=http://localhost:13030/v18.0
WAHA_API_URL=http://localhost:13030
WAHA_API_KEY=sandbox-key
NODE_ENV=test
JWT_SECRET=sandbox-test-secret
`.trimStart();
  await writeFile(join(ROOT, '.env.sandbox'), env);
  console.log('[sandbox] wrote .env.sandbox — source it before running tests:');
  console.log('         set -a; source .env.sandbox; set +a');
  console.log('[sandbox] ready');
}

function run(argv) {
  return new Promise((resolve, reject) => {
    const child = spawn(argv[0], argv.slice(1), { stdio: 'inherit' });
    child.on('exit', (code) => (code === 0 ? resolve() : reject(new Error(`${argv.join(' ')} → exit ${code}`))));
    child.on('error', reject);
  });
}

await main().catch((e) => {
  console.error('[sandbox] FAIL:', e.message);
  process.exit(1);
});
