import type {
  PulseCapability,
  PulseCapabilityState,
  PulseExecutionChain,
  PulseExecutionChainSet,
  PulseExecutionEvidence,
  PulseFlowProjection,
  PulseFlowProjectionItem,
  PulseScopeState,
  PulseStructuralGraph,
} from '../../types';
import { buildExecutionMatrix } from '../../execution-matrix';
import {
  generatedAt,
  makeCapability,
  makeChain,
  makeEvidence,
  makeFlow,
} from './execution-matrix.fixtures';

export function buildMatrix(args: {
  chain?: PulseExecutionChain;
  chains?: PulseExecutionChain[];
  capability?: PulseCapability;
  flow?: PulseFlowProjectionItem;
  evidence?: PulseExecutionEvidence;
  structuralGraph?: PulseStructuralGraph;
  scopeState?: PulseScopeState;
}) {
  const capability = args.capability ?? makeCapability();
  const flow = args.flow ?? makeFlow();
  const chains = args.chains ?? (args.chain ? [args.chain] : [makeChain()]);
  const executionChains: PulseExecutionChainSet = {
    chains,
    summary: {
      totalChains: chains.length,
      completeChains: chains.length,
      partialChains: 0,
      simulatedChains: 0,
      overallCompleteness: chains.length > 0 ? 1 : 0,
    },
  };
  const capabilityState: PulseCapabilityState = {
    generatedAt,
    summary: {
      totalCapabilities: 1,
      realCapabilities: 1,
      partialCapabilities: 0,
      latentCapabilities: 0,
      phantomCapabilities: 0,
      humanRequiredCapabilities: 0,
      foundationalCapabilities: 0,
      connectedCapabilities: 1,
      operationalCapabilities: 0,
      productionReadyCapabilities: 1,
      runtimeObservedCapabilities: 0,
      scenarioCoveredCapabilities: 0,
    },
    capabilities: [capability],
  };
  const flowProjection: PulseFlowProjection = {
    generatedAt,
    summary: {
      totalFlows: 1,
      realFlows: 1,
      partialFlows: 0,
      latentFlows: 0,
      phantomFlows: 0,
    },
    flows: [flow],
  };
  return buildExecutionMatrix({
    structuralGraph: args.structuralGraph ?? {
      generatedAt,
      summary: {
        totalNodes: 2,
        totalEdges: 1,
        roleCounts: {
          interface: 1,
          orchestration: 1,
          persistence: 0,
          side_effect: 0,
          simulation: 0,
        },
        interfaceChains: 1,
        completeChains: 1,
        partialChains: 0,
        simulatedChains: 0,
      },
      nodes: [
        {
          id: 'ui:checkout',
          kind: 'ui_element',
          role: 'interface',
          truthMode: 'inferred',
          adapter: 'test',
          label: 'checkout button',
          file: 'frontend/checkout.tsx',
          line: 1,
          userFacing: true,
          runtimeCritical: true,
          protectedByGovernance: false,
          metadata: {},
        },
        {
          id: 'api:checkout',
          kind: 'backend_route',
          role: 'orchestration',
          truthMode: 'inferred',
          adapter: 'test',
          label: 'checkout route',
          file: 'backend/checkout.controller.ts',
          line: 1,
          userFacing: false,
          runtimeCritical: true,
          protectedByGovernance: false,
          metadata: { route: '/api/checkout' },
        },
      ],
      edges: [
        {
          id: 'edge:checkout',
          from: 'ui:checkout',
          to: 'api:checkout',
          kind: 'calls',
          truthMode: 'inferred',
          evidence: 'test',
        },
      ],
    },
    scopeState: args.scopeState ?? {
      generatedAt,
      rootDir: '/repo',
      summary: {
        totalFiles: 2,
        totalLines: 20,
        runtimeCriticalFiles: 2,
        userFacingFiles: 1,
        humanRequiredFiles: 0,
        surfaceCounts: {
          frontend: 1,
          'frontend-admin': 0,
          backend: 1,
          worker: 0,
          prisma: 0,
          e2e: 0,
          scripts: 0,
          docs: 0,
          infra: 0,
          governance: 0,
          'root-config': 0,
          artifacts: 0,
          misc: 0,
        },
        kindCounts: {
          source: 2,
          spec: 0,
          migration: 0,
          config: 0,
          document: 0,
          artifact: 0,
        },
        unmappedModuleCandidates: [],
        inventoryCoverage: 100,
        classificationCoverage: 100,
        structuralGraphCoverage: 100,
        testCoverage: 0,
        scenarioCoverage: 0,
        runtimeEvidenceCoverage: 0,
        productionProofCoverage: 0,
        orphanFiles: [],
        unknownFiles: [],
      },
      parity: {
        status: 'pass',
        mode: 'repo_inventory_with_codacy_spotcheck',
        confidence: 'high',
        reason: 'test',
        inventoryFiles: 2,
        codacyObservedFiles: 0,
        codacyObservedFilesCovered: 0,
        missingCodacyFiles: [],
      },
      codacy: {
        snapshotAvailable: true,
        sourcePath: 'PULSE_CODACY_STATE.json',
        stale: false,
        syncedAt: generatedAt,
        ageMinutes: 0,
        loc: 20,
        totalIssues: 0,
        severityCounts: { HIGH: 0, MEDIUM: 0, LOW: 0, UNKNOWN: 0 },
        toolCounts: {},
        topFiles: [],
        highPriorityBatch: [],
        observedFiles: [],
      },
      files: [
        {
          path: 'frontend/checkout.tsx',
          extension: '.tsx',
          lineCount: 10,
          surface: 'frontend',
          kind: 'source',
          runtimeCritical: true,
          userFacing: true,
          ownerLane: 'customer',
          executionMode: 'ai_safe',
          protectedByGovernance: false,
          codacyTracked: false,
          moduleCandidate: 'checkout',
          observedCodacyIssueCount: 0,
          highSeverityIssueCount: 0,
          highestObservedSeverity: null,
          structuralHints: ['interface'],
        },
        {
          path: 'backend/checkout.controller.ts',
          extension: '.ts',
          lineCount: 10,
          surface: 'backend',
          kind: 'source',
          runtimeCritical: true,
          userFacing: false,
          ownerLane: 'customer',
          executionMode: 'ai_safe',
          protectedByGovernance: false,
          codacyTracked: false,
          moduleCandidate: 'checkout',
          observedCodacyIssueCount: 0,
          highSeverityIssueCount: 0,
          highestObservedSeverity: null,
          structuralHints: ['orchestration'],
        },
      ],
      moduleAggregates: [],
      excludedFiles: [],
      scopeSource: 'repo_filesystem',
      manifestBoundary: false,
      manifestRole: 'semantic_overlay',
    },
    executionChains,
    capabilityState,
    flowProjection,
    executionEvidence: args.evidence ?? makeEvidence(),
  });
}
