#!/usr/bin/env node
// tools/saas-compiler/verify-in-prod.mjs
//
// Post-merge prod verifier.
//
// CLI: node tools/saas-compiler/verify-in-prod.mjs intents/<file>.spec.json [--hours=24]
//
// For each compiled spec, monitors prod metrics (Sentry + Railway logs) for
// the configured window and decides:
//   • SHIP_OK   — primary metric trending toward target, guardrail green.
//   • ROLLBACK  — guardrail violated (errors spike / complaint up). Emits
//                 a revert PR job.
//   • INCONCLUSIVE — needs more time; rescheduled.
//
// Outputs verdict to graphify-out/verify-prod/<spec>-<timestamp>.json.
// On ROLLBACK, also emits a rollback job to graphify-out/auto-pr-jobs/.

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { argv } from 'node:process';
import { join } from 'node:path';

const ROOT = process.cwd();
const specArg = argv[2];
const HOURS = Number(argv.find((a) => a.startsWith('--hours='))?.split('=')[1] || 24);

if (!specArg) {
  console.error('usage: verify-in-prod.mjs <intents/file.spec.json> [--hours=N]');
  process.exit(2);
}

const specPath = specArg.startsWith('/') ? specArg : join(ROOT, specArg);

async function main() {
  const spec = JSON.parse(await readFile(specPath, 'utf8'));
  console.log(`[verify-in-prod] ${spec.name} window=${HOURS}h`);

  const sentry = await readSentryWindow(HOURS);
  const railway = await readRailwayWindow(HOURS);
  const baseline = await readBaseline(spec.name);

  const guardrailMetric = sentry.errorRatePerMin;
  const primaryMetric = railway.requestsToSpecRoutes;
  const verdict = decide({ spec, guardrailMetric, primaryMetric, baseline });

  const outDir = join(ROOT, 'graphify-out/verify-prod');
  await mkdir(outDir, { recursive: true });
  const outPath = join(outDir, `${spec.name}-${Date.now()}.json`);
  await writeFile(outPath, JSON.stringify({ verdict, sentry, railway, baseline, hours: HOURS, decidedAt: new Date().toISOString() }, null, 2));
  console.log(`[verify-in-prod] ${spec.name} verdict=${verdict.action} reason=${verdict.reason}`);

  if (verdict.action === 'ROLLBACK') {
    await emitRollback(spec, verdict);
  }
}

async function readSentryWindow(_hours) {
  // Reads from graphify-out/shards/runtime-sentry.json (populated by the
  // runtime-sentry extractor). If absent, returns conservative defaults.
  const path = join(ROOT, 'graphify-out/shards/runtime-sentry.json');
  if (!existsSync(path)) return { errorRatePerMin: 0, note: 'no-data' };
  const data = JSON.parse(await readFile(path, 'utf8'));
  const totalErrors = (data.nodes || []).filter((n) => n.type === 'sentry-issue').length;
  return { errorRatePerMin: totalErrors > 0 ? totalErrors / 60 : 0, totalErrors };
}

async function readRailwayWindow(_hours) {
  const path = join(ROOT, 'graphify-out/shards/runtime-railway.json');
  if (!existsSync(path)) return { requestsToSpecRoutes: 0, note: 'no-data' };
  const data = JSON.parse(await readFile(path, 'utf8'));
  return { requestsToSpecRoutes: (data.nodes || []).length, note: 'shard-based' };
}

async function readBaseline(name) {
  const path = join(ROOT, 'graphify-out/verify-prod/baseline.json');
  if (!existsSync(path)) return null;
  try {
    const data = JSON.parse(await readFile(path, 'utf8'));
    return data[name] || null;
  } catch { return null; }
}

function decide({ spec, guardrailMetric, primaryMetric, baseline }) {
  // Conservative decision logic; tunable per spec.
  const guardrailLimit = parseGuardrail(spec.metrics?.guardrail || '');
  if (guardrailLimit !== null && guardrailMetric > guardrailLimit) {
    return { action: 'ROLLBACK', reason: `guardrail violated: ${guardrailMetric} > ${guardrailLimit}`, primaryMetric, guardrailMetric };
  }
  if (primaryMetric === 0 && (!baseline || baseline.requests === 0)) {
    return { action: 'INCONCLUSIVE', reason: 'no traffic observed yet', primaryMetric, guardrailMetric };
  }
  return { action: 'SHIP_OK', reason: 'within thresholds', primaryMetric, guardrailMetric };
}

function parseGuardrail(s) {
  const m = s.match(/<\s*([\d.]+)/);
  return m ? Number(m[1]) : null;
}

async function emitRollback(spec, verdict) {
  const ts = Date.now();
  const job = {
    title: `revert(${spec.name}): rollback per verify-in-prod`,
    body: `Auto-rollback triggered.\n\nReason: ${verdict.reason}\nSpec: \`${spec.name}\`\nMetric primary: ${verdict.primaryMetric}\nGuardrail metric: ${verdict.guardrailMetric}\n\nThis revert PR is generated by tools/saas-compiler/verify-in-prod.mjs.`,
    branch: `auto/revert-${spec.name}-${ts}`,
    base: 'origin/main',
    files: [],
    shell: [
      `git revert --no-edit $(git log --grep='${spec.name}' -n 1 --format=%H) || true`,
    ],
  };
  const dir = join(ROOT, 'graphify-out/auto-pr-jobs');
  await mkdir(dir, { recursive: true });
  const out = join(dir, `revert-${spec.name}-${ts}.json`);
  await writeFile(out, JSON.stringify(job, null, 2));
  console.log(`[verify-in-prod] rollback job queued: ${out}`);
}

await main();
