[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "xvfb-run --server-args='-screen 0 1440x900x24 -ac' npm run start:prod"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
