// PULSE Browser Stress Tester — Report Generator

import * as fs from 'fs';
import * as path from 'path';
import type { StressTestResult, BrowserTestStatus, PageTestResult, ElementTestResult } from './types';
import type { FunctionalMapResult } from '../functional-map-types';

function pct(n: number, total: number): string {
  if (total === 0) return '0%';
  return Math.round((n / total) * 100) + '%';
}

function truncate(s: string, max: number): string {
  if (s.length <= max) return s;
  return s.slice(0, max - 3) + '...';
}

function esc(s: string): string {
  return s.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

function statusIcon(s: BrowserTestStatus): string {
  switch (s) {
    case 'FUNCIONA': return 'FUNCIONA';
    case 'QUEBRADO': return 'QUEBRADO';
    case 'FACHADA': return 'FACHADA';
    case 'TIMEOUT': return 'TIMEOUT';
    case 'CRASH': return 'CRASH';
    case 'NAO_TESTAVEL': return 'NAO_TESTAVEL';
  }
}

export function generateStressTestReport(
  result: StressTestResult,
  fmapResult: FunctionalMapResult | null,
  outputDir: string,
): string {
  const lines: string[] = [];
  const { summary, pages } = result;
  const totalDurSec = Math.round(summary.totalDurationMs / 1000);
  const totalDurMin = (summary.totalDurationMs / 60000).toFixed(1);

  // Header
  lines.push('# KLOEL — BROWSER STRESS TEST RESULTS');
  lines.push('');
  lines.push(`> Generated by PULSE Browser Stress Tester on ${result.timestamp}`);
  lines.push(`> Duration: ${totalDurMin}min (${totalDurSec}s) across ${summary.totalPages} pages`);
  lines.push(`> Frontend: ${result.config.frontendUrl}`);
  lines.push(`> Backend: ${result.config.backendUrl}`);
  lines.push(`> Browser: Playwright Chromium ${result.config.headless ? 'Headless' : 'Headed'}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push('| Status | Count | % |');
  lines.push('|--------|-------|---|');
  const statuses: BrowserTestStatus[] = ['FUNCIONA', 'QUEBRADO', 'FACHADA', 'TIMEOUT', 'CRASH', 'NAO_TESTAVEL'];
  for (const s of statuses) {
    const count = summary.byStatus[s] || 0;
    lines.push(`| ${statusIcon(s)} | ${count} | ${pct(count, summary.totalTested)} |`);
  }
  lines.push(`| **TOTAL TESTED** | **${summary.totalTested}** | |`);
  lines.push(`| Elements Found | ${summary.totalElements} | |`);
  lines.push('');
  lines.push(`- **Pass rate**: ${pct(summary.byStatus.FUNCIONA || 0, summary.totalTested)}`);
  lines.push(`- **Avg page load**: ${Math.round(summary.avgPageLoadMs)}ms`);
  if (summary.crashes.length > 0) {
    lines.push(`- **Crashed pages**: ${summary.crashes.join(', ')}`);
  }
  lines.push('');

  // Static vs Browser comparison
  if (fmapResult) {
    lines.push('## Static Analysis vs Browser Test');
    lines.push('');
    lines.push('| Metric | Static PULSE | Browser Test |');
    lines.push('|--------|-------------|--------------|');
    lines.push(`| Total interactions | ${fmapResult.summary.totalInteractions} | ${summary.totalElements} |`);
    lines.push(`| FUNCIONA | ${fmapResult.summary.byStatus.FUNCIONA || 0} | ${summary.byStatus.FUNCIONA || 0} |`);
    lines.push(`| QUEBRADO | ${fmapResult.summary.byStatus.QUEBRADO || 0} | ${summary.byStatus.QUEBRADO || 0} |`);
    lines.push(`| FACHADA | ${fmapResult.summary.byStatus.FACHADA || 0} | ${summary.byStatus.FACHADA || 0} |`);
    lines.push('');

    // Discrepancies: static said FUNCIONA but browser says otherwise
    const discrepancies: ElementTestResult[] = [];
    for (const page of pages) {
      for (const r of page.results) {
        if (r.fmapStatus === 'FUNCIONA' && (r.browserStatus === 'QUEBRADO' || r.browserStatus === 'CRASH')) {
          discrepancies.push(r);
        }
      }
    }

    if (discrepancies.length > 0) {
      lines.push(`## Discrepancies (${discrepancies.length})`);
      lines.push('Static said FUNCIONA but browser says QUEBRADO/CRASH:');
      lines.push('');
      for (const d of discrepancies.slice(0, 50)) {
        lines.push(`- **${d.pageRoute}** — "${esc(d.elementLabel)}" (${d.elementType}): ${esc(d.reason)}`);
      }
      if (discrepancies.length > 50) {
        lines.push(`... and ${discrepancies.length - 50} more`);
      }
      lines.push('');
    }
  }

  // Per-page results
  lines.push('## Per-Page Results');
  lines.push('');

  for (const page of pages) {
    const tested = page.results.length;
    const funciona = page.results.filter(r => r.browserStatus === 'FUNCIONA').length;
    const quebrado = page.results.filter(r => r.browserStatus === 'QUEBRADO').length;

    lines.push(`### ${page.route}`);
    lines.push(`Load: ${page.loadTimeMs}ms (${page.loadStatus}) | Found: ${page.elementsFound} | Tested: ${tested} | OK: ${funciona} | Broken: ${quebrado}`);
    lines.push('');

    if (page.loadStatus !== 'ok') {
      lines.push(`*Page load issue: ${page.loadStatus}*`);
      if (page.screenshotPath) lines.push(`Screenshot: ${page.screenshotPath}`);
      lines.push('');
      continue;
    }

    if (page.results.length === 0) {
      lines.push('*No interactive elements found*');
      lines.push('');
      continue;
    }

    lines.push('| # | Element | Type | Status | Reason | API |');
    lines.push('|---|---------|------|--------|--------|-----|');

    for (let i = 0; i < page.results.length; i++) {
      const r = page.results[i];
      const label = esc(truncate(r.elementLabel, 35));
      const api = r.apiCallObserved ? `${r.apiCallObserved.method} ${truncate(r.apiCallObserved.url, 25)} → ${r.apiCallObserved.status}` : '—';
      const reason = esc(truncate(r.reason, 45));
      lines.push(`| ${i + 1} | ${label} | ${r.elementType} | ${statusIcon(r.browserStatus)} | ${reason} | ${api} |`);
    }
    lines.push('');
  }

  // Error analysis — group by reason pattern
  const allResults = pages.flatMap(p => p.results);
  const brokenResults = allResults.filter(r => r.browserStatus === 'QUEBRADO' || r.browserStatus === 'CRASH');

  if (brokenResults.length > 0) {
    lines.push('## Error Analysis');
    lines.push('');

    // Group by reason prefix (first 50 chars)
    const reasonGroups = new Map<string, ElementTestResult[]>();
    for (const r of brokenResults) {
      const key = r.reason.slice(0, 50);
      if (!reasonGroups.has(key)) reasonGroups.set(key, []);
      reasonGroups.get(key)!.push(r);
    }

    const sorted = [...reasonGroups.entries()].sort((a, b) => b[1].length - a[1].length);
    for (const [reason, items] of sorted.slice(0, 20)) {
      lines.push(`**${reason}** (${items.length} occurrences)`);
      for (const item of items.slice(0, 5)) {
        lines.push(`  - ${item.pageRoute} → "${item.elementLabel}"`);
      }
      if (items.length > 5) lines.push(`  - ... and ${items.length - 5} more`);
      lines.push('');
    }
  }

  // Correction prompt
  if (brokenResults.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## CORRECTION PROMPT');
    lines.push('');
    lines.push('```');
    lines.push('Fix the following broken interactions found by PULSE Browser Stress Test:');
    lines.push('');
    for (const r of brokenResults.slice(0, 100)) {
      lines.push(`- ${r.pageRoute} > "${r.elementLabel}" (${r.elementType}): ${r.reason}`);
      if (r.apiCallObserved) {
        lines.push(`  API: ${r.apiCallObserved.method} ${r.apiCallObserved.url} → ${r.apiCallObserved.status}`);
      }
    }
    if (brokenResults.length > 100) {
      lines.push(`... and ${brokenResults.length - 100} more`);
    }
    lines.push('```');
  }

  const report = lines.join('\n');
  const reportPath = path.join(outputDir, 'FUNCTIONAL_TEST_RESULTS.md');
  fs.writeFileSync(reportPath, report);
  return reportPath;
}

export function renderTerminalSummary(result: StressTestResult): void {
  const R = '\x1b[0m';
  const B = '\x1b[1m';
  const D = '\x1b[2m';
  const RED = '\x1b[31m';
  const GREEN = '\x1b[32m';
  const YELLOW = '\x1b[33m';
  const CYAN = '\x1b[36m';
  const MAG = '\x1b[35m';

  const s = result.summary;
  const dur = (s.totalDurationMs / 60000).toFixed(1);
  const rate = s.totalTested > 0 ? Math.round(((s.byStatus.FUNCIONA || 0) / s.totalTested) * 100) : 0;
  const rateColor = rate >= 70 ? GREEN : rate >= 40 ? YELLOW : RED;

  console.log('');
  console.log(`  ${B}BROWSER STRESS TEST${R} ${rateColor}${rate}% pass${R}  ${D}|${R}  ${s.totalPages} pages, ${s.totalElements} elements, ${dur}min`);
  console.log(`  ${D}${'─'.repeat(65)}${R}`);
  console.log('');
  console.log(`  ${GREEN}FUNCIONA${R}      ${String(s.byStatus.FUNCIONA || 0).padStart(5)}  ${D}(interaction works in browser)${R}`);
  console.log(`  ${RED}QUEBRADO${R}      ${String(s.byStatus.QUEBRADO || 0).padStart(5)}  ${D}(error or API failure)${R}`);
  console.log(`  ${MAG}FACHADA${R}       ${String(s.byStatus.FACHADA || 0).padStart(5)}  ${D}(no effect observed)${R}`);
  console.log(`  ${YELLOW}TIMEOUT${R}       ${String(s.byStatus.TIMEOUT || 0).padStart(5)}  ${D}(timed out)${R}`);
  console.log(`  ${RED}CRASH${R}         ${String(s.byStatus.CRASH || 0).padStart(5)}  ${D}(page crashed)${R}`);
  console.log(`  ${D}NAO_TESTAVEL  ${String(s.byStatus.NAO_TESTAVEL || 0).padStart(5)}  (not testable)${R}`);
  console.log('');
}
