/** Product template shape. */
export interface ProductTemplate {
  /** Id property. */
  id: string;
  /** Name property. */
  name: string;
  /** Cat property. */
  cat: string; // category tag
  /** Fmt property. */
  fmt: string; // format label (e.g. "post-ig", "story-ig")
  /** Colors property. */
  colors: [string, string]; // gradient for card preview
  /** W property. */
  w: number;
  /** H property. */
  h: number;
  /** Json property. */
  json: object; // Fabric.js canvas JSON
}

/** Product_templates. */
export const PRODUCT_TEMPLATES: ProductTemplate[] = [
  /* ── 1. Anuncio Produto Premium ── */
  {
    id: 'tpl-anuncio-produto-premium',
    name: 'Anuncio Produto Premium',
    cat: 'Produto',
    fmt: 'post-ig',
    colors: ['#E85D30', '#0A0A0C'],
    w: 1080,
    h: 1080,
    json: {
      version: '7.0.0',
      background: '#0A0A0C',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: '#0A0A0C',
          selectable: false,
          evented: false,
        },
        {
          type: 'textbox',
          left: 100,
          top: 200,
          width: 880,
          text: 'Serum Premium',
          fontSize: 48,
          fontWeight: 'bold',
          fontFamily: 'Sora',
          fill: '#E0DDD8',
          textAlign: 'left',
        },
        {
          type: 'textbox',
          left: 100,
          top: 270,
          width: 880,
          text: 'Regeneracao celular avancada',
          fontSize: 18,
          fontFamily: 'Sora',
          fill: '#6E6E73',
          textAlign: 'left',
        },
        { type: 'rect', left: 100, top: 310, width: 200, height: 4, fill: '#E85D30' },
        {
          type: 'rect',
          left: 100,
          top: 885,
          width: 200,
          height: 44,
          fill: '#E85D30',
          rx: 4,
          ry: 4,
        },
        {
          type: 'textbox',
          left: 100,
          top: 892,
          width: 200,
          text: 'Comprar agora',
          fontSize: 14,
          fontWeight: 'bold',
          fontFamily: 'Sora',
          fill: '#0A0A0C',
          textAlign: 'center',
        },
      ],
    },
  },

  /* ── 2. Anuncio Produto B ── */
  {
    id: 'tpl-anuncio-produto-b',
    name: 'Anuncio Produto B',
    cat: 'Produto',
    fmt: 'post-ig',
    colors: ['#E85D30', '#111113'],
    w: 1080,
    h: 1080,
    json: {
      version: '7.0.0',
      background: '#0A0A0C',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: '#0A0A0C',
          selectable: false,
          evented: false,
        },
        {
          type: 'textbox',
          left: 100,
          top: 200,
          width: 880,
          text: 'Seu Produto',
          fontSize: 48,
          fontWeight: 'bold',
          fontFamily: 'Sora',
          fill: '#E0DDD8',
          textAlign: 'left',
        },
        {
          type: 'textbox',
          left: 100,
          top: 270,
          width: 880,
          text: 'Reparacao e Rejuvenescimento',
          fontSize: 18,
          fontFamily: 'Sora',
          fill: '#6E6E73',
          textAlign: 'left',
        },
        { type: 'rect', left: 100, top: 310, width: 200, height: 4, fill: '#E85D30' },
        {
          type: 'rect',
          left: 100,
          top: 885,
          width: 200,
          height: 44,
          fill: '#E85D30',
          rx: 4,
          ry: 4,
        },
        {
          type: 'textbox',
          left: 100,
          top: 892,
          width: 200,
          text: 'Comprar agora',
          fontSize: 14,
          fontWeight: 'bold',
          fontFamily: 'Sora',
          fill: '#0A0A0C',
          textAlign: 'center',
        },
      ],
    },
  },

  /* ── 3. Prova Social (Story) ── */
  {
    id: 'tpl-prova-social',
    name: 'Prova Social',
    cat: 'Depoimento',
    fmt: 'story-ig',
    colors: ['#E85D30', '#1C1C1F'],
    w: 1080,
    h: 1920,
    json: {
      version: '7.0.0',
      background: '#0A0A0C',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1920,
          fill: '#0A0A0C',
          selectable: false,
          evented: false,
        },
        {
          type: 'textbox',
          left: 100,
          top: 200,
          width: 120,
          text: '\u201C',
          fontSize: 120,
          fontFamily: 'Sora',
          fill: '#E85D30',
          textAlign: 'left',
        },
        {
          type: 'textbox',
          left: 100,
          top: 300,
          width: 880,
          text: 'Escreva o depoimento do cliente aqui. Resultados visiveis em poucas semanas de uso.',
          fontSize: 20,
          fontFamily: 'Sora',
          fill: '#E0DDD8',
          lineHeight: 1.6,
          textAlign: 'left',
        },
        {
          type: 'textbox',
          left: 100,
          top: 600,
          width: 880,
          text: '\u2014 Nome da Cliente',
          fontSize: 14,
          fontFamily: 'Sora',
          fill: '#6E6E73',
          textAlign: 'left',
        },
        {
          type: 'textbox',
          left: 100,
          top: 640,
          width: 200,
          text: '\u2605 \u2605 \u2605 \u2605 \u2605',
          fontSize: 18,
          fontFamily: 'Sora',
          fill: '#E85D30',
          textAlign: 'left',
        },
        {
          type: 'textbox',
          left: 100,
          top: 1800,
          width: 200,
          text: 'KLOEL',
          fontSize: 10,
          fontWeight: 'bold',
          fontFamily: 'Sora',
          fill: '#3A3A3F',
          charSpacing: 400,
          textAlign: 'left',
        },
      ],
    },
  },

  /* ── 4. Antes e Depois ── */
  {
    id: 'tpl-antes-depois',
    name: 'Antes e Depois',
    cat: 'Antes/Depois',
    fmt: 'post-ig',
    colors: ['#E85D30', '#0A0A0C'],
    w: 1080,
    h: 1080,
    json: {
      version: '7.0.0',
      background: '#0A0A0C',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: '#0A0A0C',
          selectable: false,
          evented: false,
        },
        { type: 'rect', left: 0, top: 80, width: 530, height: 1000, fill: '#111113' },
        { type: 'rect', left: 550, top: 80, width: 530, height: 1000, fill: '#111113' },
        { type: 'rect', left: 537, top: 0, width: 6, height: 1080, fill: '#E85D30' },
        {
          type: 'textbox',
          left: 200,
          top: 50,
          width: 160,
          text: 'ANTES',
          fontSize: 16,
          fontWeight: 'bold',
          fontFamily: 'Sora',
          fill: '#E0DDD8',
          charSpacing: 300,
          textAlign: 'center',
        },
        {
          type: 'textbox',
          left: 700,
          top: 50,
          width: 160,
          text: 'DEPOIS',
          fontSize: 16,
          fontWeight: 'bold',
          fontFamily: 'Sora',
          fill: '#E0DDD8',
          charSpacing: 300,
          textAlign: 'center',
        },
      ],
    },
  },

  /* ── 5. Mockup Frasco ── */
  {
    id: 'tpl-mockup-frasco',
    name: 'Mockup Frasco',
    cat: 'Produto',
    fmt: 'post-ig',
    colors: ['#E85D30', '#111113'],
    w: 1080,
    h: 1080,
    json: {
      version: '7.0.0',
      background: '#0A0A0C',
      objects: [
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: '#0A0A0C',
          selectable: false,
          evented: false,
        },
        {
          type: 'rect',
          left: 0,
          top: 0,
          width: 1080,
          height: 1080,
          fill: '#111113',
          opacity: 0.5,
          selectable: false,
          evented: false,
        },
        {
          type: 'textbox',
          left: 240,
          top: 150,
          width: 600,
          text: 'Nome do Produto',
          fontSize: 36,
          fontWeight: 'bold',
          fontFamily: 'Sora',
          fill: '#E0DDD8',
          textAlign: 'center',
        },
        {
          type: 'rect',
          left: 340,
          top: 250,
          width: 400,
          height: 600,
          fill: '#1C1C1F',
          rx: 8,
          ry: 8,
        },
        {
          type: 'textbox',
          left: 100,
          top: 900,
          width: 880,
          text: '\u2022  Ingrediente ativo de alta performance',
          fontSize: 13,
          fontFamily: 'Sora',
          fill: '#6E6E73',
          textAlign: 'left',
        },
        {
          type: 'textbox',
          left: 100,
          top: 930,
          width: 880,
          text: '\u2022  Resultados clinicamente comprovados',
          fontSize: 13,
          fontFamily: 'Sora',
          fill: '#6E6E73',
          textAlign: 'left',
        },
        {
          type: 'textbox',
          left: 100,
          top: 960,
          width: 880,
          text: '\u2022  Tecnologia exclusiva KLOEL',
          fontSize: 13,
          fontFamily: 'Sora',
          fill: '#6E6E73',
          textAlign: 'left',
        },
      ],
    },
  },
];
