/* ═══════════════════════════════════════════
   KLOEL CANVAS — Format Data Tables
   Pure data tables extracted from canvas-formats.ts
   to keep that module lean. All entries are
   side-effect-free constants.
   ═══════════════════════════════════════════ */

import { colors } from './design-tokens';
import { externalBrands } from './external-brand-tokens';
import { canvasPalette } from './canvas-palette-tokens';
import type { FormatItem } from './canvas-formats-types';

/* ═══ FORMAT DATA BY CATEGORY ═══ */
export const FORMAT_DATA: Record<string, FormatItem[]> = {
  'para-voce': [
    {
      l: 'Apresentacao',
      s: '1920x1080',
      m: 'desktop-chart',
      c: [colors.semantic.warning, canvasPalette.amberLight],
      w: 1920,
      h: 1080,
    },
    {
      l: 'Post Instagram (4:5)',
      s: '1080x1350',
      m: 'phone-post',
      c: [externalBrands.instagramPurple, externalBrands.instagramPink],
      w: 1080,
      h: 1350,
    },
    { l: 'Documento (A4)', s: '210x297mm', m: 'doc', c: [externalBrands.emailPurple, colors.semantic.purpleText], w: 2480, h: 3508 },
    {
      l: 'Story do Instagram',
      s: '1080x1920',
      m: 'phone-story',
      c: [externalBrands.instagramPink, externalBrands.instagramOrange],
      w: 1080,
      h: 1920,
    },
    { l: 'Doc (digital)', s: 'Livre', m: 'desktop', c: [colors.canvas.cyan, canvasPalette.cyanLight], w: 1280, h: 720 },
    { l: 'Panfleto (A4)', s: '210x297mm', m: 'doc', c: [externalBrands.emailPurple, canvasPalette.violetDeep], w: 2480, h: 3508 },
    {
      l: 'Quadro branco',
      s: 'Infinito',
      m: 'desktop',
      c: [colors.semantic.success, canvasPalette.emeraldLight],
      w: 1920,
      h: 1080,
    },
    {
      l: 'Video horizontal',
      s: '1920x1080',
      m: 'desktop',
      c: [colors.canvas.pink, canvasPalette.pinkLight],
      w: 1920,
      h: 1080,
    },
  ],
  'redes-sociais': [
    {
      l: 'Post Instagram (4:5)',
      s: '1080x1350',
      m: 'phone-post',
      c: [externalBrands.instagramPurple, externalBrands.instagramPink],
      p: 'Instagram',
      w: 1080,
      h: 1350,
    },
    {
      l: 'Story do Instagram',
      s: '1080x1920',
      m: 'phone-story',
      c: [externalBrands.instagramPink, externalBrands.instagramOrange],
      p: 'Instagram',
      w: 1080,
      h: 1920,
    },
    {
      l: 'Video Reels',
      s: '1080x1920',
      m: 'phone-story',
      c: [externalBrands.instagramPurple, externalBrands.instagramOrange],
      p: 'Instagram',
      w: 1080,
      h: 1920,
    },
    {
      l: 'Foto de perfil IG',
      s: '320x320',
      m: 'circle',
      c: [externalBrands.instagramPink, externalBrands.instagramPurple],
      p: 'Instagram',
      w: 320,
      h: 320,
    },
    {
      l: 'Post Facebook',
      s: '1200x628',
      m: 'desktop',
      c: [externalBrands.facebook, externalBrands.fbBlueLight],
      p: 'Facebook',
      w: 1200,
      h: 628,
    },
    {
      l: 'Capa Facebook',
      s: '851x315',
      m: 'desktop',
      c: [externalBrands.facebook, externalBrands.fbBlueDark],
      p: 'Facebook',
      w: 851,
      h: 315,
    },
    {
      l: 'Story Facebook',
      s: '1080x1920',
      m: 'phone-story',
      c: [externalBrands.facebook, externalBrands.fbBlueLight],
      p: 'Facebook',
      w: 1080,
      h: 1920,
    },
    {
      l: 'Anuncio Facebook',
      s: '1200x628',
      m: 'desktop',
      c: [externalBrands.facebook, externalBrands.fbBlueLight],
      p: 'Facebook',
      w: 1200,
      h: 628,
    },
    {
      l: 'Foto perfil FB',
      s: '320x320',
      m: 'circle',
      c: [externalBrands.facebook, externalBrands.fbBlueLight],
      p: 'Facebook',
      w: 320,
      h: 320,
    },
    {
      l: 'Post LinkedIn',
      s: '1200x627',
      m: 'desktop',
      c: [externalBrands.linkedinBlue, externalBrands.linkedinDark],
      p: 'LinkedIn',
      w: 1200,
      h: 627,
    },
    {
      l: 'Capa LinkedIn',
      s: '1584x396',
      m: 'desktop',
      c: [externalBrands.linkedinBlue, externalBrands.linkedinDark],
      p: 'LinkedIn',
      w: 1584,
      h: 396,
    },
    {
      l: 'Foto perfil LI',
      s: '400x400',
      m: 'circle',
      c: [externalBrands.linkedinBlue, externalBrands.linkedinDarker],
      p: 'LinkedIn',
      w: 400,
      h: 400,
    },
    {
      l: 'Pin Pinterest',
      s: '1000x1500',
      m: 'phone-post',
      c: [externalBrands.pinterestRed, externalBrands.pinterestDarkRed],
      p: 'Pinterest',
      w: 1000,
      h: 1500,
    },
    {
      l: 'Video TikTok',
      s: '1080x1920',
      m: 'phone-story',
      c: [externalBrands.tiktokPink, externalBrands.tiktokTeal],
      p: 'TikTok',
      w: 1080,
      h: 1920,
    },
    {
      l: 'Foto perfil TT',
      s: '200x200',
      m: 'circle',
      c: [externalBrands.tiktokPink, externalBrands.tiktokTeal],
      p: 'TikTok',
      w: 200,
      h: 200,
    },
    {
      l: 'Post Twitter/X',
      s: '1600x900',
      m: 'desktop',
      c: [externalBrands.twitterBlue, externalBrands.twitterDark],
      p: 'Twitter',
      w: 1600,
      h: 900,
    },
    {
      l: 'Cabecalho X',
      s: '1500x500',
      m: 'desktop',
      c: [externalBrands.twitterBlue, externalBrands.twitterBlueDark],
      p: 'Twitter',
      w: 1500,
      h: 500,
    },
    {
      l: 'Shorts YouTube',
      s: '1080x1920',
      m: 'phone-story',
      c: [externalBrands.youtubeRed, externalBrands.youtubeDarkRed],
      p: 'YouTube',
      w: 1080,
      h: 1920,
    },
    {
      l: 'Miniatura YT',
      s: '1280x720',
      m: 'desktop',
      c: [externalBrands.youtubeRed, externalBrands.youtubeDarkRed],
      p: 'YouTube',
      w: 1280,
      h: 720,
    },
    {
      l: 'Banner YT',
      s: '2560x1440',
      m: 'desktop',
      c: [externalBrands.youtubeRed, externalBrands.youtubeDarkRed],
      p: 'YouTube',
      w: 2560,
      h: 1440,
    },
    {
      l: 'Foto perfil YT',
      s: '800x800',
      m: 'circle',
      c: [externalBrands.youtubeRed, canvasPalette.redDark],
      p: 'YouTube',
      w: 800,
      h: 800,
    },
  ],
  videos: [
    {
      l: 'Video horizontal',
      s: '1920x1080',
      m: 'desktop',
      c: [colors.canvas.pink, canvasPalette.pinkLight],
      w: 1920,
      h: 1080,
    },
    {
      l: 'Video vertical',
      s: '1080x1920',
      m: 'phone-story',
      c: [externalBrands.emailPurple, colors.semantic.purpleText],
      w: 1080,
      h: 1920,
    },
    {
      l: 'Video TikTok',
      s: '1080x1920',
      m: 'phone-story',
      c: [externalBrands.tiktokPink, externalBrands.tiktokTeal],
      w: 1080,
      h: 1920,
    },
    {
      l: 'Video YouTube',
      s: '1920x1080',
      m: 'desktop',
      c: [externalBrands.youtubeRed, externalBrands.youtubeDarkRed],
      w: 1920,
      h: 1080,
    },
    {
      l: 'Video Reels',
      s: '1080x1920',
      m: 'phone-story',
      c: [externalBrands.instagramPurple, externalBrands.instagramPink],
      w: 1080,
      h: 1920,
    },
    {
      l: 'Video quadrado',
      s: '1080x1080',
      m: 'square',
      c: [colors.text.muted, canvasPalette.gray],
      w: 1080,
      h: 1080,
    },
  ],
  impressao: [
    { l: 'Cartaz (A2)', s: '420x594mm', m: 'doc', c: [externalBrands.emailPurple, canvasPalette.violetDeep], w: 4961, h: 7016 },
    { l: 'Panfleto (A4)', s: '210x297mm', m: 'doc', c: [externalBrands.emailPurple, colors.semantic.purpleText], w: 2480, h: 3508 },
    { l: 'Convite', s: '148x210mm', m: 'doc', c: [externalBrands.emailPurple, canvasPalette.violetMid], w: 1748, h: 2480 },
    { l: 'Cartao visita', s: '85x55mm', m: 'desktop', c: [externalBrands.emailPurple, canvasPalette.violetDeep], w: 1004, h: 650 },
    { l: 'Folder', s: 'A4 paisagem', m: 'desktop', c: [externalBrands.emailPurple, colors.semantic.purpleText], w: 3508, h: 2480 },
  ],
  docs: [
    { l: 'Doc (digital)', s: 'Livre', m: 'desktop', c: [colors.canvas.cyan, canvasPalette.cyanLight], w: 1280, h: 720 },
    { l: 'Doc (A4)', s: '210x297mm', m: 'doc', c: [colors.canvas.cyan, canvasPalette.cyanLight], w: 2480, h: 3508 },
    { l: 'Doc (A3)', s: '297x420mm', m: 'doc', c: [colors.canvas.cyan, canvasPalette.cyanMid], w: 3508, h: 4961 },
  ],
  anuncios: [
    {
      l: 'Criativo Feed',
      s: '1080x1080',
      m: 'square',
      c: [colors.ember.primary, colors.canvas.accent],
      w: 1080,
      h: 1080,
    },
    {
      l: 'Criativo Story',
      s: '1080x1920',
      m: 'phone-story',
      c: [colors.ember.primary, colors.semantic.warning],
      w: 1080,
      h: 1920,
    },
    {
      l: 'Banner Display',
      s: '1200x628',
      m: 'desktop',
      c: [colors.ember.primary, colors.canvas.accent],
      w: 1200,
      h: 628,
    },
  ],
  quadros: [
    {
      l: 'Quadro branco',
      s: 'Infinito',
      m: 'desktop',
      c: [colors.semantic.success, canvasPalette.emeraldLight],
      w: 1920,
      h: 1080,
    },
  ],
  planilhas: [
    { l: 'Planilha', s: 'Livre', m: 'desktop-chart', c: [colors.semantic.info, canvasPalette.blueLight], w: 1920, h: 1080 },
  ],
  sites: [{ l: 'Site', s: '1440xauto', m: 'desktop', c: [canvasPalette.indigo, canvasPalette.indigoLight], w: 1440, h: 900 }],
  emails: [{ l: 'E-mail', s: '600xauto', m: 'doc', c: [externalBrands.emailPurple, colors.semantic.purpleText], w: 600, h: 800 }],
};
