/** Kloel_tokens. */
export const KLOEL_TOKENS = {
  borderRadius: {
    max: 16,
    values: [0, 4, 6, 8, 12, 14, 16],
  },
  fonts: {
    allowed: [
      'Inter',
      "'Inter'",
      '"Inter"',
      'Geist Sans',
      "'Geist Sans'",
      '"Geist Sans"',
      'Sora',
      "'Sora'",
      '"Sora"',
      'JetBrains Mono',
      "'JetBrains Mono'",
      '"JetBrains Mono"',
      'sans-serif',
      'system-ui',
      'monospace',
      'var(--font-sora)',
      'var(--font-jetbrains-mono)',
      'var(--font-geist-sans)',
      'var(--font-geist-mono)',
    ],
  },
  colors: {
    allowed: [
      '#0A0A0A',
      'colors.background.void',
      '#0F0F0F',
      '#141414',
      '#1A1A1A',
      '#212121',
      '#262626',
      'colors.background.surface',
      'colors.background.elevated',
      'colors.border.space',
      'colors.border.default',
      'colors.text.silver',
      'colors.text.muted',
      'colors.text.dim',
      'colors.ember.primary',
      '#F5F5F5',
      '#FFFFFF',
    ],
  },
  contracts: {
    minChatFontSizePx: 16,
    allowGradients: false,
    allowEmojiInProductUi: false,
  },
} as const;
