import { KLOEL_THEME } from '@/lib/kloel-theme';

export const UI = {
  bg: KLOEL_THEME.bgPrimary,
  surface: KLOEL_THEME.bgSecondary,
  card: KLOEL_THEME.bgCard,
  elevated: KLOEL_THEME.bgElevated,
  overlay: KLOEL_THEME.bgOverlay,
  border: KLOEL_THEME.borderPrimary,
  borderSoft: KLOEL_THEME.borderSecondary,
  text: KLOEL_THEME.textPrimary,
  muted: KLOEL_THEME.textSecondary,
  tertiary: KLOEL_THEME.textTertiary,
  inverse: KLOEL_THEME.textInverse,
  placeholder: KLOEL_THEME.textPlaceholder,
  accent: KLOEL_THEME.accent,
  accentLight: KLOEL_THEME.accentLight,
  success: KLOEL_THEME.success,
  successBg: KLOEL_THEME.successBg,
  warning: KLOEL_THEME.warning,
  warningBg: KLOEL_THEME.warningBg,
  error: KLOEL_THEME.error,
  errorBg: KLOEL_THEME.errorBg,
  info: KLOEL_THEME.info,
  infoBg: KLOEL_THEME.infoBg,
  radiusSm: 'var(--radius-sm)',
  radiusMd: 'var(--radius-md)',
  radiusLg: 'var(--radius-lg)',
  radiusFull: 'var(--radius-xl)',
} as const;
