// PULSE — Functional Map Report Generator
// Produces FUNCTIONAL_MAP.md with per-page interaction tables
import { safeJoin, safeResolve } from './safe-path';

import * as path from 'path';
import type {
  FunctionalMapResult,
  InteractionStatus,
  PageFunctionalMap,
} from './functional-map-types';
import { escapeMarkdownTableCell } from './markdown-utils';
import { writeTextFile } from './safe-fs';

function statusEmoji(status: InteractionStatus): string {
  switch (status) {
    case 'FUNCIONA':
      return 'FUNCIONA';
    case 'FACHADA':
      return 'FACHADA';
    case 'QUEBRADO':
      return 'QUEBRADO';
    case 'INCOMPLETO':
      return 'INCOMPLETO';
    case 'AUSENTE':
      return 'AUSENTE';
  }
}

function healthBar(score: number): string {
  const filled = Math.round(score / 5);
  const empty = 20 - filled;
  return '\u2588'.repeat(filled) + '\u2591'.repeat(empty);
}

function pct(count: number, total: number): string {
  if (total === 0) {
    return '0%';
  }
  return Math.round((count / total) * 100) + '%';
}

function truncate(s: string, max: number): string {
  if (s.length <= max) {
    return s;
  }
  return s.slice(0, max - 3) + '...';
}

function escapeMarkdown(s: string): string {
  return escapeMarkdownTableCell(s);
}

/** Generate functional map report. */
export function generateFunctionalMapReport(result: FunctionalMapResult, rootDir: string): string {
  const lines: string[] = [];
  const { summary, pages } = result;

  // Header
  lines.push(`# KLOEL — FUNCTIONAL MAP`);
  lines.push('');
  lines.push(`> Generated by PULSE on ${result.timestamp.slice(0, 19)}`);
  lines.push(
    `> Functional Score: **${summary.functionalScore}/100** \`${healthBar(summary.functionalScore)}\``,
  );
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Status | Count | % |`);
  lines.push(`|--------|-------|---|`);
  const statuses: InteractionStatus[] = [
    'FUNCIONA',
    'FACHADA',
    'QUEBRADO',
    'INCOMPLETO',
    'AUSENTE',
  ];
  for (const status of statuses) {
    const count = summary.byStatus[status] || 0;
    lines.push(`| ${statusEmoji(status)} | ${count} | ${pct(count, summary.totalInteractions)} |`);
  }
  lines.push(`| **TOTAL** | **${summary.totalInteractions}** | |`);
  lines.push('');
  lines.push(`- **Pages**: ${summary.totalPages} (${summary.redirectPages} redirects)`);
  lines.push('');

  // Coverage by group
  lines.push('## Coverage by Group');
  lines.push('');
  lines.push('| Group | Pages | FUNCIONA | FACHADA | QUEBRADO | INCOMPLETO | AUSENTE |');
  lines.push('|-------|-------|----------|---------|----------|------------|---------|');
  const groups = Object.keys(summary.byGroup).sort();
  for (const group of groups) {
    const g = summary.byGroup[group];
    const groupPages = pages.filter((p) => p.group === group).length;
    lines.push(
      `| ${group} | ${groupPages} | ${g.FUNCIONA || 0} | ${g.FACHADA || 0} | ${g.QUEBRADO || 0} | ${g.INCOMPLETO || 0} | ${g.AUSENTE || 0} |`,
    );
  }
  lines.push('');

  // Per-page tables — organized by groups discovered from the scan summary.
  for (const group of groups) {
    const groupPages = pages.filter((p) => p.group === group);
    if (groupPages.length === 0) {
      continue;
    }

    lines.push(`## ${group.toUpperCase()} Pages`);
    lines.push('');

    for (const page of groupPages) {
      lines.push(`### ${page.route}`);

      if (page.isRedirect) {
        lines.push(`*Redirect to ${page.redirectTarget}*`);
        lines.push('');
        continue;
      }

      // Files
      const files = page.componentFiles.filter((f) => !f.includes('node_modules'));
      if (files.length > 0) {
        lines.push(
          `Files: ${files
            .slice(0, 5)
            .map((f) => `\`${f}\``)
            .join(', ')}${files.length > 5 ? ` +${files.length - 5} more` : ''}`,
        );
      }

      // Status summary
      const c = page.counts;
      lines.push(
        `Status: ${c.FUNCIONA} funciona, ${c.FACHADA} fachada, ${c.QUEBRADO} quebrado, ${c.INCOMPLETO} incompleto, ${c.AUSENTE} ausente`,
      );
      lines.push('');

      // Data sources
      if (page.dataSources.length > 0) {
        lines.push('**Data Sources:**');
        for (const ds of page.dataSources) {
          const routeStatus = ds.hasBackendRoute ? 'OK' : 'NO ROUTE';
          lines.push(`- \`${ds.endpoint}\` (${ds.hook}) — ${routeStatus}`);
        }
        lines.push('');
      }

      // Interactions table
      if (page.interactions.length === 0) {
        lines.push('*No interactive elements detected*');
        lines.push('');
        continue;
      }

      lines.push('| Elemento | Tipo | Handler | API | Backend | Status | Reason |');
      lines.push('|----------|------|---------|-----|---------|--------|--------|');

      for (const i of page.interactions) {
        const label = escapeMarkdown(truncate(i.elementLabel, 30));
        const handler = i.handler ? escapeMarkdown(truncate(i.handler, 25)) : '—';
        const api = i.apiCall ? `${i.apiCall.method} ${truncate(i.apiCall.endpoint, 25)}` : '—';
        const backend = i.backendRoute ? truncate(i.backendRoute.fullPath, 30) : '—';
        const status = statusEmoji(i.status);
        const reason = escapeMarkdown(truncate(i.statusReason, 40));

        lines.push(
          `| ${label} | ${i.elementType} | ${handler} | ${api} | ${backend} | ${status} | ${reason} |`,
        );
      }
      lines.push('');
    }
  }

  // Correction prompt — FACHADA + QUEBRADO + AUSENTE
  const fixable = pages.flatMap((p) =>
    p.interactions.filter(
      (i) => i.status === 'FACHADA' || i.status === 'QUEBRADO' || i.status === 'AUSENTE',
    ),
  );

  if (fixable.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## CORRECTION PROMPT');
    lines.push('');
    lines.push('Copy and paste into Claude Code to fix all non-functional interactions:');
    lines.push('');
    lines.push('```');
    lines.push('Fix the following non-functional UI interactions found by PULSE Functional Map:');
    lines.push('');

    // Group by status
    for (const status of ['QUEBRADO', 'FACHADA', 'AUSENTE'] as InteractionStatus[]) {
      const items = fixable.filter((i) => i.status === status);
      if (items.length === 0) {
        continue;
      }

      lines.push(`## ${status} (${items.length})`);
      let idx = 1;
      for (const item of items.slice(0, 50)) {
        // Cap at 50 per status
        lines.push(
          `${idx}. **${item.componentFile}:${item.elementLine}** — ${item.elementType} "${item.elementLabel}"`,
        );
        lines.push(`   Page: ${item.pageRoute}`);
        lines.push(`   Reason: ${item.statusReason}`);
        if (item.apiCall) {
          lines.push(`   API: ${item.apiCall.method} ${item.apiCall.endpoint}`);
        }
        idx++;
      }
      if (items.length > 50) {
        lines.push(`... and ${items.length - 50} more`);
      }
      lines.push('');
    }
    lines.push('```');
  }

  // Write file
  const report = lines.join('\n');
  const reportPath = safeJoin(rootDir, 'FUNCTIONAL_MAP.md');
  writeTextFile(reportPath, report);
  return reportPath;
}

// Terminal summary for --fmap mode
export function renderFunctionalMapSummary(result: FunctionalMapResult): void {
  const RESET = '\x1b[0m';
  const BOLD = '\x1b[1m';
  const DIM = '\x1b[2m';
  const RED = '\x1b[31m';
  const GREEN = '\x1b[32m';
  const YELLOW = '\x1b[33m';
  const CYAN = '\x1b[36m';
  const MAGENTA = '\x1b[35m';

  const { summary } = result;
  const scoreColor =
    summary.functionalScore >= 70 ? GREEN : summary.functionalScore >= 40 ? YELLOW : RED;

  console.log('');
  console.log(
    `  ${BOLD}FUNCTIONAL MAP${RESET} ${scoreColor}${summary.functionalScore}%${RESET}  ${DIM}|${RESET}  ${summary.totalPages} pages, ${summary.totalInteractions} interactions`,
  );
  console.log(`  ${DIM}${'─'.repeat(60)}${RESET}`);
  console.log('');
  console.log(
    `  ${GREEN}FUNCIONA${RESET}    ${String(summary.byStatus.FUNCIONA || 0).padStart(4)}  ${DIM}(complete chain: UI → API → backend → DB)${RESET}`,
  );
  console.log(
    `  ${MAGENTA}FACHADA${RESET}     ${String(summary.byStatus.FACHADA || 0).padStart(4)}  ${DIM}(handler exists but no real API call)${RESET}`,
  );
  console.log(
    `  ${RED}QUEBRADO${RESET}    ${String(summary.byStatus.QUEBRADO || 0).padStart(4)}  ${DIM}(API call but no backend route)${RESET}`,
  );
  console.log(
    `  ${YELLOW}INCOMPLETO${RESET}  ${String(summary.byStatus.INCOMPLETO || 0).padStart(4)}  ${DIM}(partial chain)${RESET}`,
  );
  console.log(
    `  ${DIM}AUSENTE${RESET}     ${String(summary.byStatus.AUSENTE || 0).padStart(4)}  ${DIM}(no handler / noop / dead)${RESET}`,
  );
  console.log('');
}
