import type { RuntimeChecks } from './readiness-runtime-checks';
import type {
  PulseHealth,
  PulseWorldState,
  PulseCodacyState,
  FinalProductionChecklist,
  ProductionReadinessAudit,
} from './readiness-builders';

export function buildMarkdownReport(
  health: PulseHealth,
  worldState: PulseWorldState,
  codacy: PulseCodacyState,
  runtime: RuntimeChecks,
  checklist: FinalProductionChecklist,
  audit: ProductionReadinessAudit,
): string {
  const totalScenarios = worldState.sessions.reduce((a, s) => a + s.declaredScenarios, 0);
  const executedScenarios = worldState.sessions.reduce((a, s) => a + s.executedScenarios, 0);
  const passedScenarios = worldState.sessions.reduce((a, s) => a + s.passedScenarios, 0);
  const missingEvidence = worldState.asyncExpectationsStatus.filter(
    (e) => e.status === 'missing_evidence',
  ).length;

  const lines: string[] = [
    `# PULSE REPORT — ${audit.generatedAt}`,
    '',
    '## UNIFIED READINESS VERDICT',
    '',
    `- Pipeline: \`scripts/pulse/unified-readiness-report.ts\``,
    `- Health Score: ${health.overall.score}/100 (${health.overall.status})`,
    `- Certification: ${health.certification.status}`,
    `- Readiness Status: ${audit.readinessStatus}`,
    `- Codacy Grade: ${codacy.repositorySummary.gradeLetter} (${codacy.repositorySummary.grade})`,
    `- Checklist: ${checklist.summary.pass}/${checklist.summary.total} pass, ${checklist.summary.fail} fail, ${checklist.summary.warn} warn`,
    '',
    '## Runtime Checks',
    '',
    `| Check | Status | Detail |`,
    `|-------|--------|--------|`,
    `| Build Artifacts | ${runtime.build.pass ? 'PASS' : 'FAIL'} | ${runtime.build.detail} |`,
    `| CI Last Run | ${runtime.ciLastRun.pass ? 'PASS' : 'WARN'} | ${runtime.ciLastRun.detail} |`,
    `| Git Status | ${runtime.gitStatus.pass ? 'PASS' : 'WARN'} | ${runtime.gitStatus.detail} |`,
    `| Test Coverage | ${runtime.testCoverage.pass ? 'PASS' : 'FAIL'} | ${runtime.testCoverage.detail} |`,
    `| Env Files | ${runtime.envFiles.pass ? 'PASS' : 'FAIL'} | ${runtime.envFiles.detail} |`,
    `| Hooks Integrity | ${runtime.hooksIntegrity.pass ? 'PASS' : 'FAIL'} | ${runtime.hooksIntegrity.detail} |`,
    '',
    '## Codacy State',
    '',
    `- Total Issues: ${codacy.totalIssues}`,
    `- HIGH: ${codacy.bySeverity.HIGH ?? 0}`,
    `- MEDIUM: ${codacy.bySeverity.MEDIUM ?? 0}`,
    `- LOW: ${codacy.bySeverity.LOW ?? 0}`,
    `- Security: ${codacy.byCategory.Security ?? 0}`,
    `- Synced: ${codacy.syncedAt}`,
    '',
    '## World State',
    '',
    `- Scenarios: ${executedScenarios}/${totalScenarios} executed, ${passedScenarios}/${executedScenarios} passing`,
    `- Missing Evidence: ${missingEvidence} expectations`,
    `- Generated: ${worldState.generatedAt}`,
    '',
    '### Session Summary',
    '',
    `| Actor | Declared | Executed | Passed |`,
    `|-------|----------|----------|--------|`,
  ];

  for (const session of worldState.sessions) {
    lines.push(
      `| ${session.kind} | ${session.declaredScenarios} | ${session.executedScenarios} | ${session.passedScenarios} |`,
    );
  }

  lines.push(
    '',
    '## Checklist Summary',
    '',
  );

  for (const cat of checklist.categories) {
    lines.push(`### ${cat.category}`, '');
    for (const item of cat.items) {
      const icon = item.status === 'pass' ? 'PASS' : item.status === 'fail' ? 'FAIL' : 'WARN';
      lines.push(`- [${icon}] **${item.label}** (${item.priority}): ${item.detail}`);
    }
    lines.push('');
  }

  lines.push(
    '## Critical Gaps',
    '',
  );

  if (audit.criticalGaps.length === 0) {
    lines.push('No critical gaps detected.', '');
  } else {
    for (const gap of audit.criticalGaps) {
      lines.push(
        `### ${gap.rank}. ${gap.issue}`,
        '',
        `- **Impact**: ${gap.impact}`,
        `- **Fix**: ${gap.fix}`,
        '',
      );
    }
  }

  lines.push(
    '## Source Artifacts',
    '',
    `- PULSE_HEALTH.json: ${health.generatedAt}`,
    `- PULSE_WORLD_STATE.json: ${worldState.generatedAt}`,
    `- PULSE_CODACY_STATE.json: ${codacy.syncedAt}`,
    '',
    '---',
    '',
    `Generated by \`scripts/pulse/unified-readiness-report.ts\` at ${audit.generatedAt}`,
    '',
  );

  return lines.join('\n');
}
